
//static const char *V_CarErrorMSG_DEU[88]={
//chpark.24.10.10
static const char *V_CarErrorMSG_DEU[95]={
	"ACC-Schlüsselerkennung nicht\nmöglich",
	"CAN0-Kommunikationsfehler",
	"CAN-Kommunikationsfehler (ECM)",
	"CAN-Kommunikationsfehler\n(DEF-Tank)",
	"CAN-Kommunikationsfehler\n(Cluster-Messgerät)",
	"CAN-Kommunikationsfehler (HVAC)",
	"CAN-Kommunikationsfehler (DCU)",
	"CAN-Kommunikationsfehler\n(Steuergerät)",
	"CAN-Kommunikationsfehler\n(Schalterbaugruppe)",
	"CAN-Kommunikationsfehler (Wählrad)",
	"CAN-Kommunikationsfehler (Radio)",
	"CAN-Kommunikationsfehler\n(Fahrhebel)",
	"CAN-Kommunikationsfehler\n(270°-Kameraeinheit)",
	"Fehler der Versorgungsspannung der\nHauptsteuerung (hoch)",
	"Fehler der Versorgungsspannung der\nHauptsteuerung (niedrig)",
	"Fehler der Spannung des\nHauptsteuerungssensors (hoch)",
	"Fehler der Spannung des\nHauptsteuerungssensors (niedrig)",
	"Fehler beim Laden der Lichtmaschine",
	"Fehler im Kühlmittelstand",
	"Fehler des Kühlmittelstandsschalters",
	"Motoröldruckfehler",
	"Überhitzung",
	"Verstopfung des Luftfilters",
	"Wasserabscheider-Fehler",
	"Überhitzung des Hydrauliköls",
	"Kabel des\nHydrauliköltemperatursensors\nunterbrochen",
	"Fehler Gaspedalsensor (Kurzschluss)",
	"Fehler Gaspedalsensor (Kabelbruch)",
	"Spannungsfehler des Kraftstoffgebers\n(hoch)",
	"Spannungsfehler des Kraftstoffgebers\n(niedrig)",
	"Hubalarmsensor Spannungsfehler\n(Kurzschluss)",
	"Hubalarmsensor Spannungsfehler\n(Kabelbruch)",
	"Fehler in der Neutralstellung linker\nFahrhebel",
	"Fehler in der Neutralstellung rechter\nFahrhebel",
	"Spannungsfehler des Ausleger\nschwenken/2. Ausleger-Pedal\n(hoch)",//"Spannungsfehler des Pedals (hoch)", //chpark.24.10.10
	"Spannungsfehler des Ausleger\nschwenken/2. Ausleger-Pedal\n(niedrig)",//"Spannungsfehler des Pedals (niedrig)",//chpark.24.10.10
	"Spannungsfehler des Ausleger\nschwenken/2. Ausleger-Pedal\n(drift)",//"Spannungsfehler des Pedals (Drift)",//chpark.24.10.10
	"Fehler in der Neutralstellung\nAusleger schwenken/2.\nAusleger-Pedal",//"Fehler in der Neutralstellung Pedal",//chpark.24.10.10
	"Spannungsfehler Schildhebel (hoch)",
	"Spannungsfehler Schildhebel (niedrig)",
	"Spannungsfehler Schildhebel (Drift)",
	"Neutralpositionsfehler Schildhebel",
	"Spannungsfehler P4-Drucksensor\n(hoch)",
	"Spannungsfehler P4-Drucksensor\n(niedrig)",
	"Spannungsfehler linker Standardgriff-\nSchiebeschalter (hoch)",
	"Spannungsfehler linker Standardgriff-\nSchiebeschalter (niedrig)",
	"Spannungsfehler rechter\nStandardgriff-Schiebeschalter (hoch)",
	"Spannungsfehler rechter\nStandardgriff-Schiebeschalter\n(niedrig)",
	"Spannungsfehler linker\nMultifunktionsgriff-Schiebeschalter 1\n(hoch)",
	"Spannungsfehler linker\nMultifunktionsgriff-Schiebeschalter 1\n(niedrig)",
	"Spannungsfehler linker\nMultifunktionsgriff-Schiebeschalter 2\n(hoch)",
	"Spannungsfehler linker\nMultifunktionsgriff-Schiebeschalter 2\n(niedrig)",
	"Spannungsfehler linker\nMultifunktionsgriff-Schiebeschalter 3\n(hoch)",
	"Spannungsfehler linker\nMultifunktionsgriff-Schiebeschalter 3\n(niedrig)",
	"Spannungsfehler rechter\nMultifunktionsgriff-Schiebeschalter 1\n(hoch)",
	"Spannungsfehler rechter\nMultifunktionsgriff-Schiebeschalter 1\n(niedrig)",
	"Spannungsfehler rechter\nMultifunktionsgriff-Schiebeschalter 2\n(hoch)",
	"Spannungsfehler rechter\nMultifunktionsgriff-Schiebeschalter 2\n(niedrig)",
	"Spannungsfehler rechter\nMultifunktionsgriff-Schiebeschalter 3\n(hoch)",
	"Spannungsfehler rechter\nMultifunktionsgriff-Schiebeschalter 3\n(niedrig)",
	"AUX1 Fehler Schiebeschalter\nNeutralstellung",
	"AUX1 (L) Schalterfehler",
	"AUX1 (R) Schalterfehler",
	"AUX2 Fehler Schiebeschalter\nNeutralstellung",
	"AUX4 Fehler Schiebeschalter\nNeutralstellung",
	"AUX3-Schalterfehler (Griff)",
	"AUX3-Schalterfehler (Fuß)",
	"Niedriger Fettstand",
	"Unterbrechung der\nMotoranlasser-Sicherung",
	"PWM-Ausgangsstromfehler der\nPumpe (niedrig)",
	"PWM-Ausgangsstromfehler von AUX1\n(L) (niedrig)",
	"PWM-Ausgangsstromfehler von AUX1\n(R) (niedrig)",
	"PWM-Ausgangsstromfehler von AUX2\n(L) (niedrig)",
	"PWM-Ausgangsstromfehler von AUX2\n(R) (niedrig)",
	"Autotank-Solenoid Ausgangsfehler",
	"Erweiterungsausgang 1\nSchaltfehler", //chpark.24.10.10
	"Erweiterungsausgang 2\nSchaltfehler", //chpark.24.10.10
	"Erweiterungsausgang 3\nSchaltfehler", //chpark.24.10.10
	"Erweiterungsausgang 4\nSchaltfehler", //chpark.24.10.10
	"Erweiterungsausgang 5\nFehler bei\nSchiebeschalter-Neutralstellung",	//chpark.24.10.10
	"Erweiterungsausgang 5\nA-seitiger PWM-Ausgangsstromfehler\n(niedrig)",	//chpark.24.10.10
	"Erweiterungsausgang 5\nB-seitiger PWM-Ausgangsstromfehler\n(niedrig)",	//chpark.24.10.10
	"AUX1-Druck\nSOL-Ausgangsstromfehler (niedrig)",
	"AUX2-Druck\nSOL-Ausgangsstromfehler (niedrig)",
	"PWM-Ausgangsstromfehler von AUX4\n(L) (niedrig)",
	"PWM-Ausgangsstromfehler von AUX4\n(R) (niedrig)",
	"Vorwärtsfahrt links\nPWM-Ausgangsstromfehler (niedrig)",
	"Vorwärtsfahrt rechts\nPWM-Ausgangsstromfehler (niedrig)",
	"Rückwärtsfahrt links\nPWM-Ausgangsstromfehler (niedrig)",
	"Rückwärtsfahrt rechts\nPWM-Ausgangsstromfehler (niedrig)",
	"Magnet-Ausgangsstromfehler für das\nAnheben des Schildes (niedrig)",
	"Magnet-Ausgangsstromfehler für das\nAbsenken des Schildes (niedrig)",
	"Magnet-Ausgangsstromfehler beim\nAusfahren des Einstellers (niedrig)",
	"Magnet-Ausgangsstromfehler beim\nEinfahren des Einstellers (niedrig)",
	"Änderung TFM-Parameter"};
