
//static const char *H_CarErrorMSG_ESP[88]={
//chpark.24.10.10
static const char *H_CarErrorMSG_ESP[95]={	
	"No se puede detectar la llave\nACC",
	"Error de comunicación de CAN0",
	"Error de comunicación de CAN\n(ECM)",
	"Error de comunicación de CAN\n(tanque de DEF)",
	"Error de comunicación de CAN\n(panel de instrumentos)",
	"Error de comunicación de CAN\n(climatización)",
	"Error de comunicación de CAN\n(DCU)",
	"Error de comunicación de CAN\n(unidad de control)",
	"Error de comunicación de CAN\n(conjunto de interruptores)",
	"Error de comunicación de CAN\n(disco selector)",
	"Error de comunicación de CAN\n(radio)",
	"Error de comunicación de CAN\n(palanca de desplazamiento)",
	"Error de comunicación de CAN\n(unidad de cámara de 270\ngrados)",
	"Error de tensión de\nalimentación del controlador\nprincipal (alta)",
	"Error de tensión de\nalimentación del controlador\nprincipal (baja)",
	"Error de tensión del sensor del\ncontrolador principal (alta)",
	"Error de tensión del sensor del\ncontrolador principal (baja)",
	"Fallo de carga del alternador",
	"Error de nivel de refrigerante",
	"Fallo del interruptor de nivel de\nrefrigerante",
	"Error de presión del aceite del\nmotor",
	"Sobrecalentamiento",
	"Obstrucción del filtro de aire",
	"Error del separador de agua",
	"Sobrecalentamiento del aceite\nhidráulico",
	"Rotura del cableado del sensor\nde temperatura del aceite\nhidráulico",
	"Error del sensor del acelerador\n(cortocircuito)",
	"Error del sensor del acelerador\n(rotura del cableado)",
	"Error de tensión del emisor de\ncombustible (alta)",
	"Error de tensión del emisor de\ncombustible (baja)",
	"Error del sensor de la alarma de\nelevación (cortocircuito)",
	"Error del sensor de la alarma de\nelevación (rotura del cableado)",
	"Error de posición neutra de la\npalanca de desplazamiento\nizquierda",
	"Error de posición neutra de la\npalanca de desplazamiento\nderecha",
	"Error de tensión del pedal de\noscilación de la\npluma/segunda pluma (alta)",//"Error de tensión del pedal (alta)", //chpark.24.10.10
	"Error de tensión del pedal de\noscilación de la\npluma/segunda pluma (baja)",//"Error de tensión del pedal (baja)",//chpark.24.10.10
	"Error de tensión del pedal de\noscilación de la\npluma/segunda pluma (deriva)",//"Error de tensión del pedal\n(deriva)",//chpark.24.10.10
	"Error de posición neutra del\npedal de oscilación de la\npluma/segunda pluma",//"Error de posición neutra del\npedal",//chpark.24.10.10
	"Error de tensión de la palanca\nde la cuchilla (alta)",
	"Error de tensión de la palanca\nde la cuchilla (baja)",
	"Error de tensión de la palanca\nde la cuchilla (deriva)",
	"Error de posición neutra de la\npalanca de la cuchilla",
	"Error de tensión del sensor de\npresión P4 (alta)",
	"Error de tensión del sensor de\npresión P4 (baja)",
	"Error de tensión del interruptor\ndeslizante de la empuñadura\nestándar izquierda (alta)",
	"Error de tensión del interruptor\ndeslizante de la empuñadura\nestándar izquierda (baja)",
	"Error de tensión del interruptor\ndeslizante de la empuñadura\nestándar derecha (alta)",
	"Error de tensión del interruptor\ndeslizante de la empuñadura\nestándar derecha (baja)",
	"Error de tensión del interruptor\ndeslizante 1 de la empuñadura\nmultifunción izquierda (alta)",
	"Error de tensión del interruptor\ndeslizante 1 de la empuñadura\nmultifunción izquierda (baja)",
	"Error de tensión del interruptor\ndeslizante 2 de la empuñadura\nmultifunción izquierda (alta)",
	"Error de tensión del interruptor\ndeslizante 2 de la empuñadura\nmultifunción izquierda (baja)",
	"Error de tensión del interruptor\ndeslizante 3 de la empuñadura\nmultifunción izquierda (alta)",
	"Error de tensión del interruptor\ndeslizante 3 de la empuñadura\nmultifunción izquierda (baja)",
	"Error de tensión del interruptor\ndeslizante 1 de la empuñadura\nmultifunción derecha (alta)",
	"Error de tensión del interruptor\ndeslizante 1 de la empuñadura\nmultifunción derecha (baja)",
	"Error de tensión del interruptor\ndeslizante 2 de la empuñadura\nmultifunción derecha (alta)",
	"Error de tensión del interruptor\ndeslizante 2 de la empuñadura\nmultifunción derecha (baja)",
	"Error de tensión del interruptor\ndeslizante 3 de la empuñadura\nmultifunción derecha (alta)",
	"Error de tensión del interruptor\ndeslizante 3 de la empuñadura\nmultifunción derecha (baja)",
	"Error de posición neutra del\ninterruptor deslizante AUX1",
	"Error del interruptor AUX1\n(Izquierda)",
	"Error del interruptor AUX1\n(Derecha)",
	"Error de posición neutra del\ninterruptor deslizante AUX2",
	"Error de posición neutra del\ninterruptor deslizante AUX4",
	"Error del interruptor AUX3\n(empuñadura)",
	"Error del interruptor AUX3 (pie)",
	"Nivel de grasa bajo",
	"Rotura del cableado del fusible\nde arranque del motor",
	"Error de corriente de salida de\nPWM de la bomba (baja)",
	"Error de corriente de salida de\nPWM (baja) de AUX1 (Izquierda)",
	"Error de corriente de salida de\nPWM (baja) de AUX1 (Derecha)",
	"Error de corriente de salida de\nPWM (baja) de AUX2 (Izquierda)",
	"Error de corriente de salida de\nPWM (baja) de AUX2 (Derecha)",
	"Error de salida del solenoide del\ndepósito automático",
	"Error del interruptor de la salida\nde extensión 1",//chpark.24.10.10
	"Error del interruptor de la salida\nde extensión 2",//chpark.24.10.10
	"Error del interruptor de la salida\nde extensión 3",//chpark.24.10.10
	"Error del interruptor de la salida\nde extensión 4",//chpark.24.10.10
	"Error de posición neutra del\ninterruptor deslizante\nde salida de extensión 5",		//chpark.24.10.10
	"Error de corriente de salida\n(baja) de PWM del lado A\nde la salida de extensión 5",	//chpark.24.10.10
	"Error de corriente de salida\n(baja) de PWM del lado B\nde la salida de extensión 5",	//chpark.24.10.10
	"Error de corriente de salida de\nSOL (baja) de presión AUX1",
	"Error de corriente de salida de\nSOL (baja) de presión AUX2",
	"Error de corriente de salida de\nPWM (baja) de AUX4 (Izquierda)",
	"Error de corriente de salida de\nPWM (baja) de AUX4 (Derecha)",
	"Error de corriente de salida de\nPWM de avance hacia la\nizquierda (baja)",
	"Error de corriente de salida de\nPWM de avance hacia la\nderecha (baja)",
	"Error de corriente de salida de\nPWM de retroceso hacia la\nizquierda (baja)",
	"Error de corriente de salida de\nPWM de retroceso hacia la\nderecha (baja)",
	"Error de corriente de salida del\nsolenoide de elevación de la\ncuchilla (baja)",
	"Error de corriente de salida del\nsolenoide de descenso de la\ncuchilla (baja)",
	"Error de corriente de salida del\nsolenoide de extensión del\nregulador (baja)",
	"Error de corriente de salida del\nsolenoide de retracción del\nregulador (baja)",
	"Cambio de los parámetros del\nTFM"};
