
//static const char *H_CarErrorMSG_ENG[88]={
//chpark.24.10.10	
static const char *H_CarErrorMSG_ENG[95]={	
	"ACC key detection not possible",
	"CAN0 communication error",
	"CAN communication error (ECM)",
	"CAN communication error (DEF\ntank)",
	"CAN communication error\n(cluster gauge)",
	"CAN communication error\n(HVAC)",
	"CAN communication error (DCU)",
	"CAN communication error\n(control unit)",
	"CAN communication error\n(switch assembly)",
	"CAN communication error (jog\ndial)",
	"CAN communication error\n(radio)",
	"CAN communication error\n(travel lever)",
	"CAN communication error (270-\ndegree camera unit)",
	"Main controller power supply\nvoltage error (high)",
	"Main controller power supply\nvoltage error (low)",
	"Main controller sensor voltage\nerror (high)",
	"Main controller sensor voltage\nerror (low)",
	"Alternator charge fault",
	"Coolant level error",
	"Coolant level switch fault",
	"Engine oil pressure error",
	"Overheating",
	"Air cleaner clogging",
	"Water separator error",
	"Hydraulic oil overheating",
	"Hydraulic oil temperature\nsensor wiring break",
	"Accelerator sensor error (short\ncircuit)",
	"Accelerator sensor error (wiring\nbreak)",
	"Fuel sender voltage error (high)",
	"Fuel sender voltage error (low)",
	"Lift alarm sensor error (short\ncircuit)",
	"Lift alarm sensor error (wiring\nbreak)",
	"Left travel lever neutral position\nerror",
	"Right travel lever neutral\nposition error",
	"Boom swing/Second boom\npedal voltage error\n(high)", 	//"Pedal voltage error (high)", 	//chpark.24.10.10
	"Boom swing/Second boom\npedal voltage error\n(low)",		//"Pedal voltage error (low)",	//chpark.24.10.10
	"Boom swing/Second boom\npedal voltage error\n(drift)",	//"Pedal voltage error (drift)",	//chpark.24.10.10
	"Boom swing/Second boom\npedal neutral position error",	//"Pedal neutral position error",	//chpark.24.10.10
	"Blade lever voltage error (high)",
	"Blade lever voltage error (low)",
	"Blade lever voltage error (drift)",
	"Blade lever neutral position\nerror",
	"P4 pressure sensor voltage error\n(high)",
	"P4 pressure sensor voltage error\n(low)",
	"Left standard grip slide switch\nvoltage error (high)",
	"Left standard grip slide switch\nvoltage error (low)",
	"Right standard grip slide switch\nvoltage error (high)",
	"Right standard grip slide switch\nvoltage error (low)",
	"Left multifunctional grip slide\nswitch 1 voltage error (high)",
	"Left multifunctional grip slide\nswitch 1 voltage error (low)",
	"Left multifunctional grip slide\nswitch 2 voltage error (high)",
	"Left multifunctional grip slide\nswitch 2 voltage error (low)",
	"Left multifunctional grip slide\nswitch 3 voltage error (high)",
	"Left multifunctional grip slide\nswitch 3 voltage error (low)",
	"Right multifunctional grip slide\nswitch 1 voltage error (high)",
	"Right multifunctional grip slide\nswitch 1 voltage error (low)",
	"Right multifunctional grip slide\nswitch 2 voltage error (high)",
	"Right multifunctional grip slide\nswitch 2 voltage error (low)",
	"Right multifunctional grip slide\nswitch 3 voltage error (high)",
	"Right multifunctional grip slide\nswitch 3 voltage error (low)",
	"AUX1 slide switch neutral\nposition error",
	"AUX1 (L) switch error",
	"AUX1 (R) switch error",
	"AUX2 slide switch neutral\nposition error",
	"AUX4 slide switch neutral\nposition error",
	"AUX3 switch error (grip)",
	"AUX3 switch error (foot)",
	"Low grease level",
	"Engine starting fuse wiring\nbreak",
	"Pump PWM output current error\n(low)",
	"AUX1 (L) PWM output current\nerror (low)",
	"AUX1 (R) PWM output current\nerror (low)",
	"AUX2 (L) PWM output current\nerror (low)",
	"AUX2 (R) PWM output current\nerror (low)",
	"Auto tank solenoid output error",
	"Extension output 1\nswitch error", //chpark.24.10.10
	"Extension output 2\nswitch error", //chpark.24.10.10
	"Extension output 3\nswitch error", //chpark.24.10.10
	"Extension output 4\nswitch error", //chpark.24.10.10
	"Extension output 5 slide switch\nneutral position error",		//chpark.24.10.10
	"Extension output 5 A-side\nPWM output current error (low)",	//chpark.24.10.10
	"Extension output 5 B-side\nPWM output current error (low)",	//chpark.24.10.10
	"AUX1 pressure SOL output\ncurrent error (low)",
	"AUX2 pressure SOL output\ncurrent error (low)",
	"AUX4 (L) PWM output current\nerror (low)",
	"AUX4 (R) PWM output current\nerror (low)",
	"Left-forward travel PWM output\ncurrent error (low)",
	"Right-forward travel PWM\noutput current error (low)",
	"Left-reverse travel PWM output\ncurrent error (low)",
	"Right-reverse travel PWM\noutput current error (low)",
	"Blade raising solenoid output\ncurrent error (low)",
	"Blade lowering solenoid output\ncurrent error (low)",
	"Adjuster extension solenoid\noutput current error (low)",
	"Adjuster retraction solenoid\noutput current error (low)",
	"TFM parameter change"};
	