
//static const char *V_CarErrorMSG_FRA[88]={	
//chpark.24.10.10
static const char *V_CarErrorMSG_FRA[95]={	
	"Détection de la clé ACC impossible",
	"Erreur de communication CAN0",
	"Erreur de communication CAN (ECM)",
	"Erreur de communication CAN\n(réservoir de DEF)",
	"Erreur de communication CAN\n(jauge de groupe d’instruments)",
	"Erreur de communication CAN (HVAC)",
	"Erreur de communication CAN (DCU)",
	"Erreur de communication CAN\n(unité de commande)",
	"Erreur de communication CAN\n(ensemble commutateur)",
	"Erreur de communication CAN\n(molette)",
	"Erreur de communication CAN (radio)",
	"Erreur de communication CAN\n(levier de translation)",
	"Erreur de communication CAN\n(unité de caméra à 270 degrés)",
	"Erreur de tension d’alimentation du\ncontrôleur principal (élevé)",
	"Erreur de tension d’alimentation du\ncontrôleur principal (faible)",
	"Erreur de tension du capteur de\ncontrôleur principal (élevé)",
	"Erreur de tension du capteur de\ncontrôleur principal (faible)",
	"Défaut de charge de l’alternateur",
	"Erreur de niveau de liquide de\nrefroidissement",
	"Défaut du commutateur de niveau de\nliquide de refroidissement",
	"Erreur de pression d’huile moteur",
	"Surchauffe",
	"Obstruction du filtre à air",
	"Erreur du séparateur d’eau",
	"Surchauffe de l’huile hydraulique",
	"Rupture du câblage du capteur de\ntempérature de l’huile hydraulique",
	"Erreur du capteur d’accélération\n(court-circuit)",
	"Erreur du capteur d’accélération\n(rupture du câblage)",
	"Erreur de tension de l’émetteur de\ncarburant (élevé)",
	"Erreur de tension de l’émetteur de\ncarburant (faible)",
	"Erreur de tension du capteur d’alarme\nde levage (court-circuit)",
	"Erreur de tension du capteur d’alarme\nde levage (rupture du câblage)",
	"Erreur de position neutre du levier de\ntranslation gauche",
	"Erreur de position neutre du levier de\ntranslation droit",
	"Erreur de tension de la orientation de\nflèche/pédale deuxième flèche\n(élevée)",//"Erreur de tension de la pédale\n(élevée)",//chpark.24.10.10
	"Erreur de tension de la orientation de\nflèche/pédale deuxième flèche\n(faible)",//"Erreur de tension de la pédale\n(faible)",//chpark.24.10.10
	"Erreur de tension de la orientation de\nflèche/pédale deuxième flèche\n(dérive)",//"Erreur de tension de la pédale\n(dérive)",//chpark.24.10.10
	"Erreur de position neutre de la\norientation de flèche/pédale\ndeuxième flèche",//"Erreur de position neutre de la\npédale",//chpark.24.10.10
	"Erreur de tension du levier de lame\n(élevée)",
	"Erreur de tension du levier de lame\n(faible)",
	"Erreur de tension du levier de lame\n(dérive)",
	"Erreur de position neutre du levier de\nlame",
	"Erreur de tension du capteur de\npression P4 (élevée)",
	"Erreur de tension du capteur de\npression P4 (faible)",
	"Erreur de tension du commutateur\ncoulissant de la poignée standard\ngauche (élevée)",
	"Erreur de tension du commutateur\ncoulissant de la poignée standard\ngauche (faible)",
	"Erreur de tension du commutateur\ncoulissant de la poignée standard\ndroite (élevée)",
	"Erreur de tension du commutateur\ncoulissant de la poignée standard\ndroite (faible)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle gauche 1 (élevée)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle gauche 1 (faible)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle gauche 2 (élevée)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle gauche 2 (faible)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle gauche 3 (élevée)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle gauche 3 (faible)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle droite 1 (élevée)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle droite 1 (faible)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle droite 2 (élevée)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle droite 2 (faible)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle droite 3 (élevée)",
	"Erreur de tension du commutateur\ncoulissant de la poignée\nmultifonctionnelle droite 3 (faible)",
	"Erreur de position neutre du\ncommutateur coulissant AUX1",
	"Erreur du commutateur AUX1 (G)",
	"Erreur du commutateur AUX1 (D)",
	"Erreur de position neutre du\ncommutateur coulissant AUX2",
	"Erreur de position neutre du\ncommutateur coulissant AUX4",
	"Erreur du commutateur AUX3\n(poignée)",
	"Erreur du commutateur AUX3\n(pédale)",
	"Faible niveau de graisse",
	"Rupture du câblage du fusible de\ndémarrage du moteur",
	"Erreur de courant de sortie de PWM\nde pompe (faible)",
	"Erreur de courant de sortie de PWM\nAUX1 (G) (faible)",
	"Erreur de courant de sortie de PWM\nAUX1 (D) (faible)",
	"Erreur de courant de sortie de PWM\nAUX2 (G) (faible)",
	"Erreur de courant de sortie de PWM\nAUX2 (D) (faible)",
	"Erreur de sortie de solénoïde de\nréservoir automatique",
	"Erreur de commutateur de sortie\nd’extension 1", //chpark.24.10.10
	"Erreur de commutateur de sortie\nd’extension 2", //chpark.24.10.10
	"Erreur de commutateur de sortie\nd’extension 3", //chpark.24.10.10
	"Erreur de commutateur de sortie\nd’extension 4", //chpark.24.10.10
	"Erreur de position neutre du\ncommutateur coulissant\nde sortie d’extension 5",//chpark.24.10.10
	"Erreur de courant de sortie de PWM\nde sortie d’extension\ncôté 5 A (faible)",//chpark.24.10.10
	"Erreur de courant de sortie de PWM\nde sortie d’extension\ncôté 5 B (faible)",//chpark.24.10.10
	"Erreur de courant de sortie SOL de la\npression AUX1 (faible)",
	"Erreur de courant de sortie SOL de la\npression AUX2 (faible)",
	"Erreur de courant de sortie de PWM\nAUX4 (G) (faible)",
	"Erreur de courant de sortie de PWM\nAUX4 (D) (faible)",
	"Erreur de courant de sortie de PWM\nde translation avant gauche (faible)",
	"Erreur de courant de sortie de PWM\nde translation avant droite (faible)",
	"Erreur de courant de sortie de PWM\nde translation arrière gauche (faible)",
	"Erreur de courant de sortie de PWM\nde translation arrière droite (faible)",
	"Erreur de courant de sortie du\nsolénoïde de levage de la lame\n(faible)",
	"Erreur de courant de sortie du\nsolénoïde d’abaissement de la lame\n(faible)",
	"Erreur de courant de sortie du\nsolénoïde d’extension du dispositif de\nréglage (faible)",
	"Erreur de courant de sortie du\nsolénoïde de rétraction du dispositif\nde réglage (faible)",
	"Changement de paramètre TFM"};
