
//static const char *V_CarErrorMSG_ENG[88]={
//chpark.24.10.10
static const char *V_CarErrorMSG_ENG[95]={	
	"ACC key detection not possible",
	"CAN0 communication error",
	"CAN communication error (ECM)",
	"CAN communication error (DEF tank)",
	"CAN communication error (cluster\ngauge)",
	"CAN communication error (HVAC)",
	"CAN communication error (DCU)",
	"CAN communication error (control\nunit)",
	"CAN communication error (switch\nassembly)",
	"CAN communication error (jog dial)",
	"CAN communication error (radio)",
	"CAN communication error (travel\nlever)",
	"CAN communication error\n(270-degree camera unit)",
	"Main controller power supply voltage\nerror (high)",
	"Main controller power supply voltage\nerror (low)",
	"Main controller sensor voltage error\n(high)",
	"Main controller sensor voltage error\n(low)",
	"Alternator charge fault",
	"Coolant level error",
	"Coolant level switch fault",
	"Engine oil pressure error",
	"Overheating",
	"Air cleaner clogging",
	"Water separator error",
	"Hydraulic oil overheating",
	"Hydraulic oil temperature sensor\nwiring break",
	"Accelerator sensor error (short circuit)",
	"Accelerator sensor error (wiring\nbreak)",
	"Fuel sender voltage error (high)",
	"Fuel sender voltage error (low)",
	"Lift alarm sensor error (short circuit)",
	"Lift alarm sensor error (wiring break)",
	"Left travel lever neutral position error",
	"Right travel lever neutral position\nerror",
	"Boom swing/Second boom pedal\nvoltage error (high)", 	//"Pedal voltage error (high)", 	//chpark.24.10.10
	"Boom swing/Second boom pedal\nvoltage error (low)",		//"Pedal voltage error (low)",	//chpark.24.10.10
	"Boom swing/Second boom pedal\nvoltage error (drift)",	//"Pedal voltage error (drift)",	//chpark.24.10.10
	"Boom swing/Second boom pedal\nneutral position error",	//"Pedal neutral position error",	//chpark.24.10.10
	"Blade lever voltage error (high)",
	"Blade lever voltage error (low)",
	"Blade lever voltage error (drift)",
	"Blade lever neutral position error",
	"P4 pressure sensor voltage error\n(high)",
	"P4 pressure sensor voltage error (low)",
	"Left standard grip slide switch voltage\nerror (high)",
	"Left standard grip slide switch voltage\nerror (low)",
	"Right standard grip slide switch\nvoltage error (high)",
	"Right standard grip slide switch\nvoltage error (low)",
	"Left multifunctional grip slide switch 1\nvoltage error (high)",
	"Left multifunctional grip slide switch 1\nvoltage error (low)",
	"Left multifunctional grip slide switch 2\nvoltage error (high)",
	"Left multifunctional grip slide switch 2\nvoltage error (low)",
	"Left multifunctional grip slide switch 3\nvoltage error (high)",
	"Left multifunctional grip slide switch 3\nvoltage error (low)",
	"Right multifunctional grip slide switch\n1 voltage error (high)",
	"Right multifunctional grip slide switch\n1 voltage error (low)",
	"Right multifunctional grip slide switch\n2 voltage error (high)",
	"Right multifunctional grip slide switch\n2 voltage error (low)",
	"Right multifunctional grip slide switch\n3 voltage error (high)",
	"Right multifunctional grip slide switch\n3 voltage error (low)",
	"AUX1 slide switch neutral position\nerror",
	"AUX1 (L) switch error",
	"AUX1 (R) switch error",
	"AUX2 slide switch neutral position\nerror",
	"AUX4 slide switch neutral position\nerror",
	"AUX3 switch error (grip)",
	"AUX3 switch error (foot)",
	"Low grease level",
	"Engine starting fuse wiring break",
	"Pump PWM output current error (low)",
	"AUX1 (L) PWM output current error\n(low)",
	"AUX1 (R) PWM output current error\n(low)",
	"AUX2 (L) PWM output current error\n(low)",
	"AUX2 (R) PWM output current error\n(low)",
	"Auto tank solenoid output error",
	"Extension output 1 switch error", //chpark.24.10.10
	"Extension output 2 switch error", //chpark.24.10.10
	"Extension output 3 switch error", //chpark.24.10.10
	"Extension output 4 switch error", //chpark.24.10.10
	"Extension output 5 slide switch\nneutral position error",		//chpark.24.10.10
	"Extension output 5 A-side\nPWM output current error (low)",	//chpark.24.10.10
	"Extension output 5 B-side\nPWM output current error (low)",	//chpark.24.10.10
	"AUX1 pressure SOL output current\nerror (low)",
	"AUX2 pressure SOL output current\nerror (low)",
	"AUX4 (L) PWM output current error\n(low)",
	"AUX4 (R) PWM output current error\n(low)",
	"Left-forward travel PWM output\ncurrent error (low)",
	"Right-forward travel PWM output\ncurrent error (low)",
	"Left-reverse travel PWM output\ncurrent error (low)",
	"Right-reverse travel PWM output\ncurrent error (low)",
	"Blade raising solenoid output current\nerror (low)",
	"Blade lowering solenoid output\ncurrent error (low)",
	"Adjuster extension solenoid output\ncurrent error (low)",
	"Adjuster retraction solenoid output\ncurrent error (low)",
	"TFM parameter change"};
	