
//static const char *V_CarErrorMSG_ESP[88]={
//chpark.24.10.10
static const char *V_CarErrorMSG_ESP[95]={	
	"No se puede detectar la llave ACC",
	"Error de comunicación de CAN0",
	"Error de comunicación de CAN (ECM)",
	"Error de comunicación de CAN\n(tanque de DEF)",
	"Error de comunicación de CAN (panel\nde instrumentos)",
	"Error de comunicación de CAN\n(climatización)",
	"Error de comunicación de CAN (DCU)",
	"Error de comunicación de CAN\n(unidad de control)",
	"Error de comunicación de CAN\n(conjunto de interruptores)",
	"Error de comunicación de CAN (disco\nselector)",
	"Error de comunicación de CAN (radio)",
	"Error de comunicación de CAN\n(palanca de desplazamiento)",
	"Error de comunicación de CAN\n(unidad de cámara de 270 grados)",
	"Error de tensión de alimentación del\ncontrolador principal (alta)",
	"Error de tensión de alimentación del\ncontrolador principal (baja)",
	"Error de tensión del sensor del\ncontrolador principal (alta)",
	"Error de tensión del sensor del\ncontrolador principal (baja)",
	"Fallo de carga del alternador",
	"Error de nivel de refrigerante",
	"Fallo del interruptor de nivel de\nrefrigerante",
	"Error de presión del aceite del motor",
	"Sobrecalentamiento",
	"Obstrucción del filtro de aire",
	"Error del separador de agua",
	"Sobrecalentamiento del aceite\nhidráulico",
	"Rotura del cableado del sensor de\ntemperatura del aceite hidráulico",
	"Error del sensor del acelerador\n(cortocircuito)",
	"Error del sensor del acelerador\n(rotura del cableado)",
	"Error de tensión del emisor de\ncombustible (alta)",
	"Error de tensión del emisor de\ncombustible (baja)",
	"Error del sensor de la alarma de\nelevación (cortocircuito)",
	"Error del sensor de la alarma de\nelevación (rotura del cableado)",
	"Error de posición neutra de la\npalanca de desplazamiento izquierda",
	"Error de posición neutra de la\npalanca de desplazamiento derecha",
	"Error de tensión del pedal de\noscilación de la\npluma/segunda pluma (alta)",//"Error de tensión del pedal (alta)", //chpark.24.10.10
	"Error de tensión del pedal de\noscilación de la\npluma/segunda pluma (baja)",//"Error de tensión del pedal (baja)",//chpark.24.10.10
	"Error de tensión del pedal de\noscilación de la\npluma/segunda pluma (deriva)",//"Error de tensión del pedal\n(deriva)",//chpark.24.10.10
	"Error de posición neutra del\npedal de oscilación de la\npluma/segunda pluma",//"Error de posición neutra del\npedal",//chpark.24.10.10
	"Error de tensión de la palanca de la\ncuchilla (alta)",
	"Error de tensión de la palanca de la\ncuchilla (baja)",
	"Error de tensión de la palanca de la\ncuchilla (deriva)",
	"Error de posición neutra de la palanca\nde la cuchilla",
	"Error de tensión del sensor de presión\nP4 (alta)",
	"Error de tensión del sensor de presión\nP4 (baja)",
	"Error de tensión del interruptor\ndeslizante de la empuñadura\nestándar izquierda (alta)",
	"Error de tensión del interruptor\ndeslizante de la empuñadura\nestándar izquierda (baja)",
	"Error de tensión del interruptor\ndeslizante de la empuñadura\nestándar derecha (alta)",
	"Error de tensión del interruptor\ndeslizante de la empuñadura\nestándar derecha (baja)",
	"Error de tensión del interruptor\ndeslizante 1 de la empuñadura\nmultifunción izquierda (alta)",
	"Error de tensión del interruptor\ndeslizante 1 de la empuñadura\nmultifunción izquierda (baja)",
	"Error de tensión del interruptor\ndeslizante 2 de la empuñadura\nmultifunción izquierda (alta)",
	"Error de tensión del interruptor\ndeslizante 2 de la empuñadura\nmultifunción izquierda (baja)",
	"Error de tensión del interruptor\ndeslizante 3 de la empuñadura\nmultifunción izquierda (alta)",
	"Error de tensión del interruptor\ndeslizante 3 de la empuñadura\nmultifunción izquierda (baja)",
	"Error de tensión del interruptor\ndeslizante 1 de la empuñadura\nmultifunción derecha (alta)",
	"Error de tensión del interruptor\ndeslizante 1 de la empuñadura\nmultifunción derecha (baja)",
	"Error de tensión del interruptor\ndeslizante 2 de la empuñadura\nmultifunción derecha (alta)",
	"Error de tensión del interruptor\ndeslizante 2 de la empuñadura\nmultifunción derecha (baja)",
	"Error de tensión del interruptor\ndeslizante 3 de la empuñadura\nmultifunción derecha (alta)",
	"Error de tensión del interruptor\ndeslizante 3 de la empuñadura\nmultifunción derecha (baja)",
	"Error de posición neutra del\ninterruptor deslizante AUX1",
	"Error del interruptor AUX1 (Izquierda)",
	"Error del interruptor AUX1 (Derecha)",
	"Error de posición neutra del\ninterruptor deslizante AUX2",
	"Error de posición neutra del\ninterruptor deslizante AUX4",
	"Error del interruptor AUX3\n(empuñadura)",
	"Error del interruptor AUX3 (pie)",
	"Nivel de grasa bajo",
	"Rotura del cableado del fusible de\narranque del motor",
	"Error de corriente de salida de PWM\nde la bomba (baja)",
	"Error de corriente de salida de PWM\n(baja) de AUX1 (Izquierda)",
	"Error de corriente de salida de PWM\n(baja) de AUX1 (Derecha)",
	"Error de corriente de salida de PWM\n(baja) de AUX2 (Izquierda)",
	"Error de corriente de salida de PWM\n(baja) de AUX2 (Derecha)",
	"Error de salida del solenoide del\ndepósito automático",
	"Error del interruptor de la salida\nde extensión 1",//chpark.24.10.10
	"Error del interruptor de la salida\nde extensión 2",//chpark.24.10.10
	"Error del interruptor de la salida\nde extensión 3",//chpark.24.10.10
	"Error del interruptor de la salida\nde extensión 4",//chpark.24.10.10
	"Error de posición neutra del\ninterruptor deslizante\nde salida de extensión 5",		//chpark.24.10.10
	"Error de corriente de salida\n(baja) de PWM del lado A\nde la salida de extensión 5",	//chpark.24.10.10
	"Error de corriente de salida\n(baja) de PWM del lado B\nde la salida de extensión 5",	//chpark.24.10.10
	"Error de corriente de salida de SOL\n(baja) de presión AUX1",
	"Error de corriente de salida de SOL\n(baja) de presión AUX2",
	"Error de corriente de salida de PWM\n(baja) de AUX4 (Izquierda)",
	"Error de corriente de salida de PWM\n(baja) de AUX4 (Derecha)",
	"Error de corriente de salida de PWM\nde avance hacia la izquierda (baja)",
	"Error de corriente de salida de PWM\nde avance hacia la derecha (baja)",
	"Error de corriente de salida de PWM\nde retroceso hacia la izquierda (baja)",
	"Error de corriente de salida de PWM\nde retroceso hacia la derecha (baja)",
	"Error de corriente de salida del\nsolenoide de elevación de la cuchilla\n(baja)",
	"Error de corriente de salida del\nsolenoide de descenso de la cuchilla\n(baja)",
	"Error de corriente de salida del\nsolenoide de extensión del regulador\n(baja)",
	"Error de corriente de salida del\nsolenoide de retracción del regulador\n(baja)",
	"Cambio de los parámetros del TFM"};
