
//static const char *V_CarErrorMSG_ITA[88]={
//chpark.24.10.10
static const char *V_CarErrorMSG_ITA[95]={	
	"Impossibile rilevare il tasto ACC",
	"Errore di comunicazione CAN0",
	"Errore di comunicazione CAN (ECM)",
	"Errore di comunicazione CAN\n(serbatoio DEF)",
	"Errore di comunicazione CAN\n(manometro cluster)",
	"Errore di comunicazione CAN (HVAC)",
	"Errore di comunicazione CAN (DCU)",
	"Errore di comunicazione CAN\n(centralina)",
	"Errore di comunicazione CAN (gruppo\ninterruttori)",
	"Errore di comunicazione CAN (jog\ndial)",
	"Errore di comunicazione CAN (radio)",
	"Errore di comunicazione CAN (leva di\ntraslazione)",
	"Errore di comunicazione CAN\n(telecamera a 270°)",
	"Errore di tensione alimentazione\ncontroller principale (alta)",
	"Errore di tensione alimentazione\ncontroller principale (bassa)",
	"Errore di tensione sensore controller\nprincipale (alta)",
	"Errore di tensione sensore controller\nprincipale (bassa)",
	"Guasto di carica dell’alternatore",
	"Errore livello liquido refrigerante",
	"Guasto interruttore livello liquido\nrefrigerante",
	"Errore di pressione dell’olio motore",
	"Surriscaldamento",
	"Intasamento del filtro dell’aria",
	"Errore separatore acqua",
	"Surriscaldamento olio idraulico",
	"Guasto cablaggio sensore\ntemperatura olio idraulico",
	"Errore sensore acceleratore\n(cortocircuito)",
	"Errore sensore acceleratore (guasto\ncablaggio)",
	"Errore di tensione galleggiante\ncarburante (alta)",
	"Errore di tensione galleggiante\ncarburante (bassa)",
	"Errore sensore allarme sollevamento\n(cortocircuito)",
	"Errore sensore allarme sollevamento\n(guasto cablaggio)",
	"Errore posizione neutra leva di\ntraslazione sinistra",
	"Errore posizione neutra leva di\ntraslazione destra",
	"Errore di tensione pedale di\ncomando brandeggio del\nbraccio/secondo braccio\n(alta)",//"Errore di tensione pedale (alta)",//chpark.24.10.10
	"Errore di tensione pedale di\ncomando brandeggio del\nbraccio/secondo braccio\n(bassa)",//"Errore di tensione pedale\n(bassa)",//chpark.24.10.10
	"Errore di tensione pedale di\ncomando brandeggio del\nbraccio/secondo braccio\n(abbassamento)",//"Errore di tensione pedale\n(abbassamento)",//chpark.24.10.10
	"Errore posizione neutra\npedale di comando brandeggio\ndel braccio/secondo braccio",//"Errore posizione neutra pedale",//chpark.24.10.10
	"Errore di tensione leva lama (alta)",
	"Errore di tensione leva lama (bassa)",
	"Errore di tensione leva lama\n(abbassamento)",
	"Errore posizione neutra leva lama",
	"Errore di tensione sensore pressione\nP4 (alta)",
	"Errore di tensione sensore pressione\nP4 (bassa)",
	"Errore di tensione interruttore a\nscorrimento impugnatura standard\nsinistra (alta)",
	"Errore di tensione interruttore a\nscorrimento impugnatura standard\nsinistra (bassa)",
	"Errore di tensione interruttore a\nscorrimento impugnatura standard\ndestra (alta)",
	"Errore di tensione interruttore a\nscorrimento impugnatura standard\ndestra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 1 impugnatura\nmultifunzionale sinistra (alta)",
	"Errore di tensione interruttore a\nscorrimento 1 impugnatura\nmultifunzionale sinistra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 2 impugnatura\nmultifunzionale sinistra (alta)",
	"Errore di tensione interruttore a\nscorrimento 2 impugnatura\nmultifunzionale sinistra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 3 impugnatura\nmultifunzionale sinistra (alta)",
	"Errore di tensione interruttore a\nscorrimento 3 impugnatura\nmultifunzionale sinistra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 1 impugnatura\nmultifunzionale destra (alta)",
	"Errore di tensione interruttore a\nscorrimento 1 impugnatura\nmultifunzionale destra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 2 impugnatura\nmultifunzionale destra (alta)",
	"Errore di tensione interruttore a\nscorrimento 2 impugnatura\nmultifunzionale destra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 3 impugnatura\nmultifunzionale destra (alta)",
	"Errore di tensione interruttore a\nscorrimento 3 impugnatura\nmultifunzionale destra (bassa)",
	"Errore posizione neutra interruttore a\nscorrimento AUX1",
	"Errore interruttore AUX1 (S)",
	"Errore interruttore AUX1 (D)",
	"Errore posizione neutra interruttore a\nscorrimento AUX2",
	"Errore posizione neutra interruttore a\nscorrimento AUX4",
	"Errore interruttore AUX3\n(impugnatura)",
	"Errore interruttore AUX3 (pedale)",
	"Basso livello di grasso",
	"Interruzione cablaggio fusibile\navviamento motore",
	"Errore corrente di uscita PWM pompa\n(bassa)",
	"Errore corrente di uscita PWM (S)\nAUX1 (bassa)",
	"Errore corrente di uscita PWM (D)\nAUX1 (bassa)",
	"Errore corrente di uscita PWM (S)\nAUX2 (bassa)",
	"Errore corrente di uscita PWM (D)\nAUX2 (bassa)",
	"Errore di uscita solenoide serbatoio\nautomatico",
	"Errore interruttore uscita di\nestensione 1",//chpark.24.10.10
	"Errore interruttore uscita di\nestensione 2",//chpark.24.10.10
	"Errore interruttore uscita di\nestensione 3",//chpark.24.10.10
	"Errore interruttore uscita di\nestensione 4",//chpark.24.10.10
	"Errore di posizione neutra \ndell’interruttore a scorrimento\nuscita di estensione 5",//chpark.24.10.10
	"Errore corrente di uscita PWM\nlato A (bassa) uscita di\nestensione 5",//chpark.24.10.10
	"Errore corrente di uscita PWM\nlato B (bassa) uscita di\nestensione 5",//chpark.24.10.10
	"Errore corrente di uscita SOL\npressione AUX1 (bassa)",
	"Errore corrente di uscita SOL\npressione AUX2 (bassa)",
	"Errore corrente di uscita PWM (S)\nAUX4 (bassa)",
	"Errore corrente di uscita PWM (D)\nAUX4 (bassa)",
	"Errore corrente di uscita PWM marcia\navanti sinistra (bassa)",
	"Errore corrente di uscita PWM marcia\navanti destra (bassa)",
	"Errore corrente di uscita PWM marcia\nindietro sinistra (bassa)",
	"Errore corrente di uscita PWM marcia\nindietro destra (bassa)",
	"Errore corrente di uscita\nelettrovalvola sollevamento lama\n(bassa)",
	"Errore corrente di uscita\nelettrovalvola abbassamento lama\n(bassa)",
	"Errore corrente di uscita\nelettrovalvola estensione regolatore\n(bassa)",
	"Errore corrente di uscita\nelettrovalvola retrazione regolatore\n(bassa)",
	"Cambiamento parametro TFM"};
