
//static const char *H_CarErrorMSG_DEU[88]={
//chpark.24.10.10
static const char *H_CarErrorMSG_DEU[95]={
	"ACC-Schlüsselerkennung nicht\nmöglich",
	"CAN0-Kommunikationsfehler",
	"CAN-Kommunikationsfehler\n(ECM)",
	"CAN-Kommunikationsfehler\n(DEF-Tank)",
	"CAN-Kommunikationsfehler\n(Cluster-Messgerät)",
	"CAN-Kommunikationsfehler\n(HVAC)",
	"CAN-Kommunikationsfehler\n(DCU)",
	"CAN-Kommunikationsfehler\n(Steuergerät)",
	"CAN-Kommunikationsfehler\n(Schalterbaugruppe)",
	"CAN-Kommunikationsfehler\n(Wählrad)",
	"CAN-Kommunikationsfehler\n(Radio)",
	"CAN-Kommunikationsfehler\n(Fahrhebel)",
	"CAN-Kommunikationsfehler\n(270°-Kameraeinheit)",
	"Fehler der\nVersorgungsspannung der\nHauptsteuerung (hoch)",
	"Fehler der\nVersorgungsspannung der\nHauptsteuerung (niedrig)",
	"Fehler der Spannung des\nHauptsteuerungssensors (hoch)",
	"Fehler der Spannung des\nHauptsteuerungssensors\n(niedrig)",
	"Fehler beim Laden der\nLichtmaschine",
	"Fehler im Kühlmittelstand",
	"Fehler des\nKühlmittelstandsschalters",
	"Motoröldruckfehler",
	"Überhitzung",
	"Verstopfung des Luftfilters",
	"Wasserabscheider-Fehler",
	"Überhitzung des Hydrauliköls",
	"Kabel des\nHydrauliköltemperatursensors\nunterbrochen",
	"Fehler Gaspedalsensor\n(Kurzschluss)",
	"Fehler Gaspedalsensor\n(Kabelbruch)",
	"Spannungsfehler des\nKraftstoffgebers (hoch)",
	"Spannungsfehler des\nKraftstoffgebers (niedrig)",
	"Hubalarmsensor\nSpannungsfehler (Kurzschluss)",
	"Hubalarmsensor\nSpannungsfehler (Kabelbruch)",
	"Fehler in der Neutralstellung\nlinker Fahrhebel",
	"Fehler in der Neutralstellung\nrechter Fahrhebel",
	"Spannungsfehler des \nAusleger schwenken/2.\nAusleger-Pedal (hoch)",//"Spannungsfehler des Pedals (hoch)", //chpark.24.10.10
	"Spannungsfehler des \nAusleger schwenken/2.\nAusleger-Pedal (niedrig)",//"Spannungsfehler des Pedals (niedrig)",//chpark.24.10.10
	"Spannungsfehler des \nAusleger schwenken/2.\nAusleger-Pedal (drift)",//"Spannungsfehler des Pedals (Drift)",//chpark.24.10.10
	"Fehler in der Neutralstellung\nAusleger schwenken/2.\nAusleger-Pedal",//"Fehler in der Neutralstellung Pedal",//chpark.24.10.10
	"Spannungsfehler Schildhebel\n(hoch)",
	"Spannungsfehler Schildhebel\n(niedrig)",
	"Spannungsfehler Schildhebel\n(Drift)",
	"Neutralpositionsfehler\nSchildhebel",
	"Spannungsfehler P4-\nDrucksensor (hoch)",
	"Spannungsfehler P4-\nDrucksensor (niedrig)",
	"Spannungsfehler linker\nStandardgriff-Schiebeschalter\n(hoch)",
	"Spannungsfehler linker\nStandardgriff-Schiebeschalter\n(niedrig)",
	"Spannungsfehler rechter\nStandardgriff-Schiebeschalter\n(hoch)",
	"Spannungsfehler rechter\nStandardgriff-Schiebeschalter\n(niedrig)",
	"Spannungsfehler linker\nMultifunktionsgriff-\nSchiebeschalter 1 (hoch)",
	"Spannungsfehler linker\nMultifunktionsgriff-\nSchiebeschalter 1 (niedrig)",
	"Spannungsfehler linker\nMultifunktionsgriff-\nSchiebeschalter 2 (hoch)",
	"Spannungsfehler linker\nMultifunktionsgriff-\nSchiebeschalter 2 (niedrig)",
	"Spannungsfehler linker\nMultifunktionsgriff-\nSchiebeschalter 3 (hoch)",
	"Spannungsfehler linker\nMultifunktionsgriff-\nSchiebeschalter 3 (niedrig)",
	"Spannungsfehler rechter\nMultifunktionsgriff-\nSchiebeschalter 1 (hoch)",
	"Spannungsfehler rechter\nMultifunktionsgriff-\nSchiebeschalter 1 (niedrig)",
	"Spannungsfehler rechter\nMultifunktionsgriff-\nSchiebeschalter 2 (hoch)",
	"Spannungsfehler rechter\nMultifunktionsgriff-\nSchiebeschalter 2 (niedrig)",
	"Spannungsfehler rechter\nMultifunktionsgriff-\nSchiebeschalter 3 (hoch)",
	"Spannungsfehler rechter\nMultifunktionsgriff-\nSchiebeschalter 3 (niedrig)",
	"AUX1 Fehler Schiebeschalter\nNeutralstellung",
	"AUX1 (L) Schalterfehler",
	"AUX1 (R) Schalterfehler",
	"AUX2 Fehler Schiebeschalter\nNeutralstellung",
	"AUX4 Fehler Schiebeschalter\nNeutralstellung",
	"AUX3-Schalterfehler (Griff)",
	"AUX3-Schalterfehler (Fuß)",
	"Niedriger Fettstand",
	"Unterbrechung der\nMotoranlasser-Sicherung",
	"PWM-Ausgangsstromfehler der\nPumpe (niedrig)",
	"PWM-Ausgangsstromfehler von\nAUX1 (L) (niedrig)",
	"PWM-Ausgangsstromfehler von\nAUX1 (R) (niedrig)",
	"PWM-Ausgangsstromfehler von\nAUX2 (L) (niedrig)",
	"PWM-Ausgangsstromfehler von\nAUX2 (R) (niedrig)",
	"Autotank-Solenoid\nAusgangsfehler",
	"Erweiterungsausgang 1\nSchaltfehler", //chpark.24.10.10
	"Erweiterungsausgang 2\nSchaltfehler", //chpark.24.10.10
	"Erweiterungsausgang 3\nSchaltfehler", //chpark.24.10.10
	"Erweiterungsausgang 4\nSchaltfehler", //chpark.24.10.10
	"Erweiterungsausgang 5\nFehler bei\nSchiebeschalter-Neutralstellung",	//chpark.24.10.10
	"Erweiterungsausgang 5\nA-seitiger\nPWM-Ausgangsstromfehler\n(niedrig)",	//chpark.24.10.10
	"Erweiterungsausgang 5\nB-seitiger\nPWM-Ausgangsstromfehler\n(niedrig)",	//chpark.24.10.10
	"AUX1-Druck SOL-\nAusgangsstromfehler (niedrig)",
	"AUX2-Druck SOL-\nAusgangsstromfehler (niedrig)",
	"PWM-Ausgangsstromfehler von\nAUX4 (L) (niedrig)",
	"PWM-Ausgangsstromfehler von\nAUX4 (R) (niedrig)",
	"Vorwärtsfahrt links PWM-\nAusgangsstromfehler (niedrig)",
	"Vorwärtsfahrt rechts PWM-\nAusgangsstromfehler (niedrig)",
	"Rückwärtsfahrt links PWM-\nAusgangsstromfehler (niedrig)",
	"Rückwärtsfahrt rechts PWM-\nAusgangsstromfehler (niedrig)",
	"Magnet-Ausgangsstromfehler\nfür das Anheben des Schildes\n(niedrig)",
	"Magnet-Ausgangsstromfehler\nfür das Absenken des Schildes\n(niedrig)",
	"Magnet-Ausgangsstromfehler\nbeim Ausfahren des Einstellers\n(niedrig)",
	"Magnet-Ausgangsstromfehler\nbeim Einfahren des Einstellers\n(niedrig)",
	"Änderung TFM-Parameter"};
