
//static const char *H_CarErrorMSG_ITA[88]={
//chpark.24.10.10
static const char *H_CarErrorMSG_ITA[95]={		
	"Impossibile rilevare il tasto ACC",
	"Errore di comunicazione CAN0",
	"Errore di comunicazione CAN\n(ECM)",
	"Errore di comunicazione CAN\n(serbatoio DEF)",
	"Errore di comunicazione CAN\n(manometro cluster)",
	"Errore di comunicazione CAN\n(HVAC)",
	"Errore di comunicazione CAN\n(DCU)",
	"Errore di comunicazione CAN\n(centralina)",
	"Errore di comunicazione CAN\n(gruppo interruttori)",
	"Errore di comunicazione CAN\n(jog dial)",
	"Errore di comunicazione CAN\n(radio)",
	"Errore di comunicazione CAN\n(leva di traslazione)",
	"Errore di comunicazione CAN\n(telecamera a 270°)",
	"Errore di tensione\nalimentazione controller\nprincipale (alta)",
	"Errore di tensione\nalimentazione controller\nprincipale (bassa)",
	"Errore di tensione sensore\ncontroller principale (alta)",
	"Errore di tensione sensore\ncontroller principale (bassa)",
	"Guasto di carica dell’alternatore",
	"Errore livello liquido\nrefrigerante",
	"Guasto interruttore livello\nliquido refrigerante",
	"Errore di pressione dell’olio\nmotore",
	"Surriscaldamento",
	"Intasamento del filtro dell’aria",
	"Errore separatore acqua",
	"Surriscaldamento olio idraulico",
	"Guasto cablaggio sensore\ntemperatura olio idraulico",
	"Errore sensore acceleratore\n(cortocircuito)",
	"Errore sensore acceleratore\n(guasto cablaggio)",
	"Errore di tensione galleggiante\ncarburante (alta)",
	"Errore di tensione galleggiante\ncarburante (bassa)",
	"Errore sensore allarme\nsollevamento (cortocircuito)",
	"Errore sensore allarme\nsollevamento (guasto cablaggio)",
	"Errore posizione neutra leva di\ntraslazione sinistra",
	"Errore posizione neutra leva di\ntraslazione destra",
	"Errore di tensione pedale di\ncomando brandeggio del\nbraccio/secondo braccio\n(alta)",//"Errore di tensione pedale (alta)",//chpark.24.10.10
	"Errore di tensione pedale di\ncomando brandeggio del\nbraccio/secondo braccio\n(bassa)",//"Errore di tensione pedale\n(bassa)",//chpark.24.10.10
	"Errore di tensione pedale di\ncomando brandeggio del\nbraccio/secondo braccio\n(abbassamento)",//"Errore di tensione pedale\n(abbassamento)",//chpark.24.10.10
	"Errore posizione neutra\npedale di comando brandeggio\ndel braccio/secondo braccio",//"Errore posizione neutra pedale",//chpark.24.10.10
	"Errore di tensione leva lama\n(alta)",
	"Errore di tensione leva lama\n(bassa)",
	"Errore di tensione leva lama\n(abbassamento)",
	"Errore posizione neutra leva\nlama",
	"Errore di tensione sensore\npressione P4 (alta)",
	"Errore di tensione sensore\npressione P4 (bassa)",
	"Errore di tensione interruttore a\nscorrimento impugnatura\nstandard sinistra (alta)",
	"Errore di tensione interruttore a\nscorrimento impugnatura\nstandard sinistra (bassa)",
	"Errore di tensione interruttore a\nscorrimento impugnatura\nstandard destra (alta)",
	"Errore di tensione interruttore a\nscorrimento impugnatura\nstandard destra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 1 impugnatura\nmultifunzionale sinistra (alta)",
	"Errore di tensione interruttore a\nscorrimento 1 impugnatura\nmultifunzionale sinistra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 2 impugnatura\nmultifunzionale sinistra (alta)",
	"Errore di tensione interruttore a\nscorrimento 2 impugnatura\nmultifunzionale sinistra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 3 impugnatura\nmultifunzionale sinistra (alta)",
	"Errore di tensione interruttore a\nscorrimento 3 impugnatura\nmultifunzionale sinistra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 1 impugnatura\nmultifunzionale destra (alta)",
	"Errore di tensione interruttore a\nscorrimento 1 impugnatura\nmultifunzionale destra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 2 impugnatura\nmultifunzionale destra (alta)",
	"Errore di tensione interruttore a\nscorrimento 2 impugnatura\nmultifunzionale destra (bassa)",
	"Errore di tensione interruttore a\nscorrimento 3 impugnatura\nmultifunzionale destra (alta)",
	"Errore di tensione interruttore a\nscorrimento 3 impugnatura\nmultifunzionale destra (bassa)",
	"Errore posizione neutra\ninterruttore a scorrimento AUX1",
	"Errore interruttore AUX1 (S)",
	"Errore interruttore AUX1 (D)",
	"Errore posizione neutra\ninterruttore a scorrimento AUX2",
	"Errore posizione neutra\ninterruttore a scorrimento AUX4",
	"Errore interruttore AUX3\n(impugnatura)",
	"Errore interruttore AUX3\n(pedale)",
	"Basso livello di grasso",
	"Interruzione cablaggio fusibile\navviamento motore",
	"Errore corrente di uscita PWM\npompa (bassa)",
	"Errore corrente di uscita PWM\n(S) AUX1 (bassa)",
	"Errore corrente di uscita PWM\n(D) AUX1 (bassa)",
	"Errore corrente di uscita PWM\n(S) AUX2 (bassa)",
	"Errore corrente di uscita PWM\n(D) AUX2 (bassa)",
	"Errore di uscita solenoide\nserbatoio automatico",
	"Errore interruttore uscita di\nestensione 1",//chpark.24.10.10
	"Errore interruttore uscita di\nestensione 2",//chpark.24.10.10
	"Errore interruttore uscita di\nestensione 3",//chpark.24.10.10
	"Errore interruttore uscita di\nestensione 4",//chpark.24.10.10
	"Errore di posizione neutra \ndell’interruttore a scorrimento\nuscita di estensione 5",//chpark.24.10.10
	"Errore corrente di uscita PWM\nlato A (bassa) uscita di\nestensione 5",//chpark.24.10.10
	"Errore corrente di uscita PWM\nlato B (bassa) uscita di\nestensione 5",//chpark.24.10.10
	"Errore corrente di uscita SOL\npressione AUX1 (bassa)",
	"Errore corrente di uscita SOL\npressione AUX2 (bassa)",
	"Errore corrente di uscita PWM\n(S) AUX4 (bassa)",
	"Errore corrente di uscita PWM\n(D) AUX4 (bassa)",
	"Errore corrente di uscita PWM\nmarcia avanti sinistra (bassa)",
	"Errore corrente di uscita PWM\nmarcia avanti destra (bassa)",
	"Errore corrente di uscita PWM\nmarcia indietro sinistra (bassa)",
	"Errore corrente di uscita PWM\nmarcia indietro destra (bassa)",
	"Errore corrente di uscita\nelettrovalvola sollevamento\nlama (bassa)",
	"Errore corrente di uscita\nelettrovalvola abbassamento\nlama (bassa)",
	"Errore corrente di uscita\nelettrovalvola estensione\nregolatore (bassa)",
	"Errore corrente di uscita\nelettrovalvola retrazione\nregolatore (bassa)",
	"Cambiamento parametro TFM"};
