
static const char *H_EngErrorMSG_ITA[308]={	
    "Errore di tensione sensore 2\nacceleratore (alta)",
    "Errore di tensione sensore 2\nacceleratore (bassa)",
    "Errore posizione aperta sensore\npedale",
    "Errore posizione chiusa sensore\npedale",
    "Errore di tensione sensore 3\nacceleratore (alta)",
    "Errore di tensione sensore 3\nacceleratore (bassa)",
    "Errore di tensione sensore\nposizione valvola a farfalla di\naspirazione (alta)",
    "Errore di tensione sensore\nposizione valvola a farfalla di\naspirazione (bassa)",
    "Errore di tensione sensore 1\nacceleratore (alta)",
    "Errore di tensione sensore 1\nacceleratore (bassa)",
    "Errore di tensione sensore\npressione olio (alta)",
    "Errore di tensione sensore\npressione olio (bassa)",
    "Calo di pressione olio",
    "Errore di tensione sensore\npressione lato bassa pressione\nEGR (alta)",
    "Errore di tensione sensore\npressione lato bassa pressione\nEGR (bassa)",
    "Anomalia valore di\napprendimento sensore\npressione lato bassa pressione\nEGR",
    "Errore valore rilevato sensore\npressione lato bassa pressione\nEGR",
    "Errore di tensione sensore\ntemperatura collettore di\naspirazione (alta)",
    "Errore di tensione sensore\ntemperatura collettore di\naspirazione (bassa)",
    "Errore valore rilevato sensore\ntemperatura collettore di\naspirazione",
    "Errore di tensione sensore\npressione atmosferica (alta)",
    "Errore di tensione sensore\npressione atmosferica (bassa)",
    "Errore caratteristiche sensore\npressione atmosferica",
    "Errore di tensione sensore\ntemperatura refrigerante\nmotore (alta)",
    "Errore di tensione sensore\ntemperatura refrigerante\nmotore (bassa)",
    "Aumento temperatura\nrefrigerante motore\n(surriscaldamento)",
    "Errore valore rilevato sensore\ntemperatura refrigerante\nmotore",
    "Errore di tensione sensore\npressione condotto (alta)",
    "Errore di tensione sensore\npressione condotto (bassa)",
    "Aumento eccessivo pressione\ncondotto",
    "Errore scostamento pressione\ncondotto (bassa pressione\ncondotto)",
    "Interruzione cablaggio\ninterruttore di carica",
    "Errore di carica",
    "Errore di tensione sensore\ntemperatura aria ambiente\n(alta)",
    "Errore di tensione sensore\ntemperatura aria ambiente\n(bassa)",
    "Errore valore rilevato sensore\ntemperatura aria ambiente",
    "Ricezione non valida valore\ntemperatura aria ambiente ECU",
    "Errore di tensione sensore\ntemperatura collettore di\nscarico (alta)",
    "Errore di tensione sensore\ntemperatura collettore di\nscarico (bassa)",
    "Errore valore rilevato sensore\ntemperatura collettore di\nscarico",
    "Errore di tensione sensore\ntemperatura carburante (alta)",
    "Errore di tensione sensore\ntemperatura carburante (bassa)",
    "Aumento temperatura\ncarburante",
    "Velocità eccessiva",
    "Timeout ricezione CAN (VI)",
    "Errore dati ricevuti CAN (VI)",
    "Errore di tensione sensore\ntemperatura gas EGR (alta)",
    "Errore di tensione sensore\ntemperatura gas EGR (bassa)",
    "Errore valore rilevato sensore\ntemperatura gas EGR",
    "Errore di verifica dati tra ECU e\nDCU (mancata corrispondenza\nmodello motore)",
    "Errore di verifica dati tra ECU e\nDCU (mancata corrispondenza\nN. di matricola)",
    "Errore EEPROM",
    "Cortocircuito VB lato H/L\nvalvola di comando aspirazione\n(valvola proporzionale\nmagnetica)",
    "Cortocircuito/interruzione\ncablaggio GND lato H valvola\ndi comando aspirazione\n(valvola proporzionale\nmagnetica)",
    "Errore circuito di comando\n(inceppamento valvola di\ncomando aspirazione)",
    "Interruzione cablaggio specifico\niniettore cilindro N. 1",
    "Cortocircuito tra terminali COM\ne TWV bobina iniettore cilindro\nN. 1",
    "Circuito aperto MOS scarica\niniettore cilindro N. 1",
    "Interruzione cablaggio specifico\niniettore cilindro N. 2",
    "Cortocircuito tra terminali COM\ne TWV bobina iniettore cilindro\nN. 2",
    "Circuito aperto MOS scarica\niniettore cilindro N. 2",
    "Interruzione cablaggio specifico\niniettore cilindro N. 3",
    "Cortocircuito tra terminali COM\ne TWV bobina iniettore cilindro\nN. 3",
    "Circuito aperto MOS scarica\niniettore cilindro N. 3",
    "Interruzione cablaggio specifico\niniettore cilindro N. 4",
    "Cortocircuito tra terminali COM\ne TWV bobina iniettore cilindro\nN. 4",
    "Circuito aperto MOS scarica\niniettore cilindro N. 4",
    "Errore di tensione sensore\npressione lato alta pressione\nEGR (alta)",
    "Errore di tensione sensore\npressione lato alta pressione\nEGR (bassa)",
    "Anomalia valore di\napprendimento sensore\npressione lato alta pressione\nEGR",
    "Errore valore rilevato sensore\npressione lato alta pressione\nEGR",
    "Errore di protezione pompa ad\nalta pressione",
    "Errore di sostituzione pompa\nad alta pressione",
    "Spegnimento senza\nautoritenuta relè principale",
    "Basso livello serbatoio urea\nacquosa (invito 1)",
    "Basso livello serbatoio urea\nacquosa (invito 2)",
    "Interruzione cablaggio sensore\nlivello serbatoio urea acquosa",
    "Cortocircuito sensore livello\nserbatoio urea acquosa\n(AT1T1I)",
    "Errore controller interno\nsensore livello serbatoio urea\nacquosa (AT1T1I)",
    "Errore valore rilevato sensore\nlivello serbatoio urea acquosa",
    "Interruzione cablaggio bobina\nmotore EGR",
    "Errore feedback EGR",
    "Errore dati ECM EGR",
    "Errore di tensione EGR\n(sovratensione)",
    "Errore di tensione EGR (bassa)",
    "Cortocircuito +B banco iniettori\n1",
    "Cortocircuito GND banco\niniettori 1 ",
    "Interruzione cablaggio banco\niniettori 1",
    "Errore clock interno VDIC3 IC-1\ndriver iniettori",
    "Errore di comunicazione tra\nVDIC3 e microcomputer IC-1\ndriver iniettori",
    "Cortocircuito +B banco iniettori\n2",
    "Cortocircuito GND banco\niniettori 2 ",
    "Interruzione cablaggio banco\niniettori 2",
    "Errore clock interno VDIC3 IC-2\ndriver iniettori",
    "Errore di comunicazione tra\nVDIC3 e microcomputer IC-2\ndriver iniettori",
    "Interruzione cablaggio circuito\ndi comando valvola a farfalla di\naspirazione",
    "Cortocircuito VB/GND circuito\ndi comando valvola a farfalla di\naspirazione ",
    "Errore scostamento circuito di\ncomando valvola a farfalla di\naspirazione",
    "Errore servizio di comando\ncircuito di comando valvola a\nfarfalla di aspirazione",
    "Aumento temperatura sensore\ntemperatura serbatoio urea\nacquosa/controller sensore\nlivello serbatoio urea acquosa\n(AT1T1I)",
    "Interruzione cablaggio circuito\ninterno sensore temperatura\nserbatoio urea acquosa\n(AT1T1I)",
    "Cortocircuito circuito interno\nsensore temperatura serbatoio\nurea acquosa (AT1T1I)",
    "Guasto interno controller\nsensore temperatura serbatoio\nurea acquosa (AT1T1I)",
    "Aumento temperatura\nserbatoio urea acquosa",
    "Errore valore rilevato sensore\ntemperatura serbatoio urea\nacquosa (errore limite\nsuperiore)",
    "Errore valore rilevato sensore\ntemperatura serbatoio urea\nacquosa (errore limite inferiore)",
    "Errore valore rilevato sensore\nNOx a monte SCR (errore\nlimite superiore)",
    "Errore valore rilevato sensore\nNOx a monte SCR (errore\nlimite inferiore)",
    "Errore di tensione sensore\ntemperatura ingresso DPF (alta)",
    "Errore di tensione sensore\ntemperatura ingresso DPF\n(bassa)",
    "Errore valore rilevato sensore\ntemperatura ingresso DPF",
    "Aumento temperatura ingresso\nDPF",
    "Errore di tensione sensore\ntemperatura intermedia DPF\n(alta)",
    "Errore di tensione sensore\ntemperatura intermedia DPF\n(bassa)",
    "Errore valore rilevato sensore\ntemperatura intermedia DPF",
    "Calo temperatura intermedia\nDPF",
    "Aumento temperatura\nintermedia DPF (guasto post\niniezione)",
    "Errore di tensione sensore\npressione differenziale DPF\n(alta)",
    "Errore di tensione sensore\npressione differenziale DPF\n(bassa)",
    "Anomalia valore di\napprendimento sensore\npressione differenziale DPF",
    "Aumento pressione\ndifferenziale DPF",
    "Aumento temperatura\ncontroller sensore qualità urea\nacquosa/sensore temperatura\nserbatoio urea acquosa\n(A1DEFI)",
    "Interruzione cablaggio circuito\ninterno sensore temperatura\nserbatoio urea acquosa\n(A1DEFI)",
    "Cortocircuito circuito interno\nsensore temperatura serbatoio\nurea acquosa (A1DEFI)",
    "Guasto interno controller\nsensore temperatura serbatoio\nurea acquosa (A1DEFI)",
    "Interruzione cablaggio circuito\ninterno sensore qualità urea\nacquosa",
    "Cortocircuito circuito interno\nsensore qualità urea acquosa",
    "Guasto interno controller\nsensore qualità urea acquosa",
    "Errore concentrazione sensore\nqualità urea acquosa (piccolo\nscostamento)",
    "Errore concentrazione sensore\nqualità urea acquosa (grande\nscostamento)",
    "Contaminazione serbatoio urea\nacquosa",
    "Errore di tensione sensore\npressione lato alta pressione\nDPF (alta)",
    "Errore di tensione sensore\npressione lato alta pressione\nDPF (bassa)",
    "Errore valore rilevato sensore\npressione lato alta pressione\nDPF",
    "Standby rigenerazione\nparcheggiata DPF",
    "Guasto rigenerazione DPF\n(guasto rigenerazione recovery)",
    "Inibizione rigenerazione\nrecovery DPF",
    "Modalità backup DPF",
    "Richiesta pulizia cenere DPF 1",
    "Richiesta pulizia cenere DPF 2",
    "Errore di tensione sensore\npressione pompa modulo\nalimentazione (alta)",
    "Errore di tensione sensore\npressione pompa modulo\nalimentazione (bassa)",
    "Errore valore rilevato sensore\npressione pompa modulo\nalimentazione (errore limite\nsuperiore)",
    "Errore valore rilevato sensore\npressione pompa modulo\nalimentazione (errore limite\ninferiore)",
    "Cortocircuito VB lato L\nriscaldatore tubo urea acquosa\n(pressione)",
    "Cortocircuito GND lato L\nriscaldatore tubo urea acquosa\n(pressione)",
    "Interruzione cablaggio\nriscaldatore tubo urea acquosa\n(pressione)",
    "Cortocircuito VB lato L\nriscaldatore tubo urea acquosa\n(riflusso)",
    "Cortocircuito GND lato L\nriscaldatore tubo urea acquosa\n(riflusso)",
    "Interruzione cablaggio\nriscaldatore tubo urea acquosa\n(riflusso)",
    "Cortocircuito VB lato L\nriscaldatore tubo urea acquosa\n(aspirazione)",
    "Cortocircuito GND lato L\nriscaldatore tubo urea acquosa\n(aspirazione)",
    "Interruzione cablaggio\nriscaldatore tubo urea acquosa\n(aspirazione)",
    "Errore di tensione sensore\ntemperatura a monte\ncatalizzatore SCR (alta)",
    "Errore di tensione sensore\ntemperatura a monte\ncatalizzatore SCR (bassa)",
    "Aumento temperatura a monte\ncatalizzatore SCR",
    "Errore valore rilevato sensore\ntemperatura a monte\ncatalizzatore SCR (errore limite\nsuperiore)",
    "Errore valore rilevato sensore\ntemperatura a monte\ncatalizzatore SCR (errore limite\ninferiore)",
    "Errore valore rilevato al\ncontrollo avviamento a freddo\nsensore temperatura a monte\ncatalizzatore SCR",
    "Cortocircuito VB cablaggio\nsegnale PWM modulo\nalimentazione (motore pompa)",
    "Cortocircuito GND cablaggio\nsegnale PWM modulo\nalimentazione (motore pompa)",
    "Interruzione cablaggio segnale\nPWM modulo alimentazione\n(motore pompa)",
    "Errore comando modulo\nalimentazione (motore pompa)\n1",
    "Errore comando modulo\nalimentazione (motore pompa)\n2",
    "Errore validità rimozione\nmateriale base DPF/sensore\npressione differenziale DPF",
    "Cortocircuito GND lato L\nvalvola riscaldamento serbatoio",
    "Interruzione cablaggio valvola\nriscaldamento serbatoio",
    "Errore di comunicazione ECU\ntra microcomputer (errore di\ncomunicazione MSC)",
    "Errore di comunicazione ECU\ntra microcomputer (errore di\ncomunicazione SPI basato su\ndiagnosi di errore sensore\npressione atmosferica SPI)",
    "Errore di comunicazione ECU\ntra microcomputer (errore di\ncomunicazione SPI basato su\ndiagnosi di errore\nmicrocomputer di\nmonitoraggio)",
    "Errore convertitore A/D\nmicrocomputer ECU",
    "Anomalia percorso arresto\niniezione su errore\nmicrocomputer ECU",
    "Cortocircuito +B spia\npreriscaldamento",
    "Cortocircuito +B spia guasto",
    "Cortocircuito +B relè\navviamento",
    "Cortocircuito +B calo idraulico",
    "Cortocircuito +B spia\navvertenza ambra",
    "Cortocircuito +B spia display\ncambio velocità",
    "Cortocircuito +B spia allarme\ntemperatura scarico",
    "Cortocircuito +B spia allarme\ntemperatura refrigerante\nmotore",
    "Cortocircuito +B cicalino",
    "Cortocircuito +B spia arresto\nmotore rossa",
    "Cortocircuito +B spia isocrona",
    "Cortocircuito +B spia\napprovazione rigenerazione\nDPF",
    "Cortocircuito +B spia divieto\nrigenerazione DPF",
    "Cortocircuito +B spia richiesta\nrigenerazione DPF",
    "Errore sistema EGR (invito 1)",
    "Errore sistema EGR (invito 2)",
    "Istruzione azione FS sistema\nECU 2",
    "Errore valore rilevato sensore\nNOx a monte SCR\n(concentrazione O2)",
    "Interruzione\ncablaggio/cortocircuito VB relè\npartenza assistita",
    "Cortocircuito GND relè\npartenza assistita",
    "Intasamento del filtro dell’aria",
    "Errore separatore acqua e olio",
    "Errore segnale albero motore",
    "Nessun segnale da albero\nmotore",
    "Errore segnale albero a camme",
    "Nessun segnale da albero a\ncamme",
    "Accumulo PM eccessivo DPF\n(metodo C)",
    "Accumulo PM eccessivo DPF\n(metodo P)",
    "Errore rigenerazione DPF\n(guasto rigenerazione\nparcheggiata)",
    "Errore rigenerazione DPF\n(rigenerazione parcheggiata\nnon azionata)",
    "Cortocircuito bobina motore\nEGR",
    "Errore sensore posizione EGR",
    "Inceppamento valvola EGR",
    "Errore inizializzazione EGR",
    "Errore termistore alta\ntemperatura EGR",
    "Errore termistore bassa\ntemperatura EGR",
    "Timeout ricezione CAN (TSC1\n(SA1))",
    "Timeout ricezione CAN (TSC1\n(SA2))",
    "Timeout ricezione CAN\n(Y_ECR1)",
    "Timeout ricezione CAN (Y_EC)",
    "Timeout ricezione CAN (Y_RSS)",
    "Timeout ricezione CAN da\nvalvola EGR",
    "Valore target EGR fuori\nintervallo",
    "Timeout ricezione CAN (EBC1)",
    "Timeout ricezione CAN\n(Y_DRFIF)",
    "Errore posizione aperta sensore\nacceleratore doppio",
    "Errore posizione chiusa sensore\nacceleratore doppio",
    "Apprendimento pompa ad alta\npressione non eseguito",
    "Errore IC monitoraggio CPU\nECU",
    "Errore CPU ECU",
    "Errore di immissione correzione\ndati QR",
    "Errore di carica circuito\ncomando iniettori (carica\nbassa)",
    "Errore di carica circuito\ncomando iniettori\n(sovraccarico)",
    "Errore checksum ROM flash\nECU",
    "Errore di tensione sensore\ncircuito 1 5V sensore ECU\n(bassa)",
    "Errore di tensione sensore\ncircuito 1 5V sensore ECU (alta)",
    "Errore di tensione sensore\ncircuito 2 5V sensore ECU\n(bassa)",
    "Errore di tensione sensore\ncircuito 2 5V sensore ECU (alta)",
    "Dati QR non scritti",
    "Errore dati QR",
    "Nessun ingresso sensore\nvelocità albero motore/sensore\nvelocità albero a camme\n(simultaneo)",
    "Timeout ricezione CAN da DCU",
    "Cortocircuito VB lato H modulo\nalimentazione (valvola\ninversione)",
    "Cortocircuito GND lato H\nmodulo alimentazione (valvola\ninversione)",
    "Cortocircuito VB lato H relè\nriscaldatore tubo/valvola\nriscaldamento serbatoio",
    "Cortocircuito GND lato H relè\nriscaldatore tubo/valvola\nriscaldamento serbatoio",
    "Cortocircuito VB lato H modulo\nalimentazione (riscaldatore\nmodulo alimentazione) ",
    "Cortocircuito GND lato H\nmodulo alimentazione\n(riscaldatore modulo\nalimentazione) ",
    "Interruzione cablaggio modulo\nalimentazione (riscaldatore\nmodulo alimentazione)",
    "Errore valore rilevato modulo\nalimentazione (riscaldatore\nmodulo alimentazione)",
    "Interruzione forzata sistema\nSCR",
    "Errore di tensione\nalimentazione DCU (alta 1)",
    "Errore di tensione\nalimentazione DCU (bassa 2)",
    "Errore di tensione\nalimentazione DCU (alta 2)",
    "Errore di tensione\nalimentazione DCU (bassa 1)",
    "Inceppamento relè principale",
    "Apertura anticipata relè\nprincipale",
    "Errore ricezione CAN da\nsensore NOx a monte SCR",
    "Errore ricezione CAN da\nsensore NOx a valle SCR",
    "Timeout ricezione CAN da ECU\n",
    "Errore di tensione\nalimentazione sensore DCU",
    "Errore di comunicazione SPI\nDCU 1",
    "Errore di comunicazione SPI\nDCU 2",
    "Cortocircuito lato H/L modulo\ndosaggio",
    "Interruzione cablaggio modulo\ndosaggio",
    "Cortocircuito VB lato H modulo\ndosaggio",
    "Cortocircuito GND modulo\ndosaggio",
    "Inceppamento valvola modulo\ndosaggio",
    "Errore di lettura memoria\nEEPROM",
    "Errore di scrittura memoria\nEEPROM",
    "Cortocircuito VB lato L relè\nriscaldatore tubo",
    "Cortocircuito GND lato L relè\nriscaldatore tubo",
    "Interruzione cablaggio relè\nriscaldatore tubo",
    "Cortocircuito VB lato L modulo\nalimentazione (riscaldatore\nmodulo alimentazione) ",
    "Cortocircuito VB lato L valvola\nriscaldamento serbatoio",
    "Aumento valore NOx a monte\nSCR",
    "Cortocircuito circuito interno\nsensore NOx a monte SCR",
    "Interruzione cablaggio circuito\ninterno sensore NOx a monte\nSCR",
    "Aumento valore NOx a valle\nSCR",
    "Cortocircuito circuito interno\nsensore NOx a valle SCR",
    "Interruzione cablaggio circuito\ninterno sensore NOx a valle\nSCR",
    "Riscaldamento incompleto\nsensore NOx a monte SCR",
    "Riscaldamento incompleto\nsensore NOx a valle SCR",
    "Cortocircuito VB lato L modulo\nalimentazione (valvola\ninversione)",
    "Cortocircuito GND lato L\nmodulo alimentazione (valvola\ninversione)",
    "Interruzione cablaggio modulo\nalimentazione (valvola\ninversione)",
    "Pulizia NOx inefficiente sistema\nSCR",
    "Errore valore rilevato modulo\nalimentazione (sensore\ntemperatura riscaldatore\nmodulo alimentazione)",
    "Errore valore rilevato al\ncontrollo avviamento a freddo\nmodulo alimentazione (sensore\ntemperatura riscaldatore\nmodulo alimentazione)",
    "Errore valore rilevato modulo\nalimentazione (sensore\ntemperatura modulo\nalimentazione)",
    "Errore valore rilevato al\ncontrollo avviamento a freddo\nmodulo alimentazione (sensore\ntemperatura modulo\nalimentazione)",
    "Ricevuto valore errato modulo\nalimentazione (sensore\ntemperatura riscaldatore\nmodulo alimentazione) per\nvalore servizio informazioni\ntemperatura",
    "Ricevuto valore non valido\nmodulo alimentazione (sensore\ntemperatura riscaldatore\nmodulo alimentazione) per\nvalore servizio informazioni\ntemperatura",
    "Errore ciclo PWM informazioni\ntemperatura modulo\nalimentazione (motore pompa)",
    "Errore segnale PWM\ninformazioni temperatura\nmodulo alimentazione (motore\npompa)",
    "Ricevuto valore errato modulo\nalimentazione (sensore\ntemperatura modulo\nalimentazione) per valore\nservizio informazioni\ntemperatura",
    "Ricevuto valore non valido\nmodulo alimentazione (sensore\ntemperatura modulo\nalimentazione) per valore\nservizio informazioni\ntemperatura",
    "Mancato avvio modulo\nalimentazione (motore pompa)\nper misurare temperatura",
    "Aumento pressione modulo\nalimentazione (motore pompa)\n1",
    "Errore riduzione pressione\nmodulo alimentazione (motore\npompa)",
    "Aumento pressione lato riflusso\ntubo urea acquosa",
    "Aumento pressione lato\npressione tubo urea acquosa",
    "Errore di stabilità pressione\nmodulo alimentazione (motore\npompa)",
    "Guasto modulo alimentazione\n(valvola inversione)",
    "Errore risucchio urea acquosa\nmodulo alimentazione",
    "Aumento pressione modulo\nalimentazione (motore pompa)\n2",
    "Calo pressione modulo\nalimentazione",
    "Aumento pressione urea\nacquosa modulo alimentazione",
    "Aumento temperatura\nserbatoio urea acquosa",
    "Timeout ricezione CAN\n(A1DEFI)",
    "Timeout ricezione CAN\n(AT1T1I)",
    "Errore sistema SCR (invito 1)",
    "Errore sistema SCR (invito 2)",
    "Istruzione azione FS sistema\nECU 1",
    "Interruzione cablaggio\ninterruttore di avviamento a\nchiave",
    "Errore di verifica dati tra ECU e\nDCU (timeout verifica)"
	};
