
static const char *H_EngErrorMSG_FRA[308]={	
    "Erreur de tension du capteur\nde l’accélérateur 2 (élevée)",
    "Erreur de tension du capteur\nde l’accélérateur 2 (faible)",
    "Erreur de position ouverte du\ncapteur de pédale",
    "Erreur de position fermée du\ncapteur de pédale",
    "Erreur de tension du capteur\nde l’accélérateur 3 (élevée)",
    "Erreur de tension du capteur\nde l’accélérateur 3 (faible)",
    "Erreur de tension du capteur\nde position du papillon des\ngaz d’admission (élevée)",
    "Erreur de tension du capteur\nde position du papillon des\ngaz d’admission (faible)",
    "Erreur de tension du capteur\nde l’accélérateur 1 (élevée)",
    "Erreur de tension du capteur\nde l’accélérateur 1 (faible)",
    "Erreur de tension du capteur\nde pression d’huile (élevée)",
    "Erreur de tension du capteur\nde pression d’huile (faible)",
    "Chute de pression d’huile",
    "Erreur de tension du capteur\nde pression côté EGR basse\npression (élevée)",
    "Erreur de tension du capteur\nde pression côté EGR basse\npression (faible)",
    "Valeur d’apprentissage\nanormale du capteur de\npression côté EGR basse\npression",
    "Erreur de valeur détectée au\nniveau du capteur de pression\ncôté EGR basse pression",
    "Erreur de tension du capteur\nde température du collecteur\nd’admission (élevée)",
    "Erreur de tension du capteur\nde température du collecteur\nd’admission (faible)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature du collecteur\nd’admission",
    "Erreur de tension du capteur\nde pression atmosphérique\n(élevée)",
    "Erreur de tension du capteur\nde pression atmosphérique\n(faible)",
    "Erreur caractéristique du\ncapteur de pression\natmosphérique",
    "Erreur de tension du capteur\nde température du liquide de\nrefroidissement du moteur\n(élevée)",
    "Erreur de tension du capteur\nde température du liquide de\nrefroidissement du moteur\n(faible)",
    "Augmentation de la\ntempérature du liquide de\nrefroidissement du moteur\n(surchauffe)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature du liquide de\nrefroidissement du moteur",
    "Erreur de tension du capteur\nde pression de la rampe\n(élevée)",
    "Erreur de tension du capteur\nde pression de la rampe\n(faible)",
    "Augmentation excessive de la\npression de la rampe",
    "Erreur d’écart de la pression de\nla rampe (faible pression de la\nrampe)",
    "Rupture du câblage du\ncommutateur de charge",
    "Erreur de charge",
    "Erreur de tension du capteur\nde température de l’air\nambiant (élevée)",
    "Erreur de tension du capteur\nde température de l’air\nambiant (faible)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature de l’air ambiant",
    "Réception d’une valeur de\ntempérature de l’air ambiant\nincorrecte de l’ECU",
    "Erreur de tension du capteur\nde température du collecteur\nd’échappement (élevée)",
    "Erreur de tension du capteur\nde température du collecteur\nd’échappement (faible)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature du collecteur\nd’échappement",
    "Erreur de tension du capteur\nde température du carburant\n(élevée)",
    "Erreur de tension du capteur\nde température du carburant\n(faible)",
    "Augmentation de la\ntempérature du carburant",
    "Vitesse excessive",
    "Expiration de la réception CAN\n(VI)",
    "Erreur des données reçues du\nCAN (VI)",
    "Erreur de tension du capteur\nde température des gaz EGR\n(élevée)",
    "Erreur de tension du capteur\nde température des gaz EGR\n(faible)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature des gaz EGR",
    "Erreur de vérification des\ndonnées entre l’ECU et le DCU\n(non-correspondance du\nmodèle de moteur)",
    "Erreur de vérification des\ndonnées entre l’ECU et le DCU\n(non-correspondance du\nnuméro de série)",
    "Erreur EEPROM",
    "Court-circuit VB côté H/L de la\nsoupape de commande\nd’aspiration (soupape\nproportionnelle magnétique)",
    "Rupture du\ncâblage/court-circuit à la masse\ncôté H de la soupape de\ncommande d’aspiration\n(soupape proportionnelle\nmagnétique)",
    "Erreur du circuit d’entraînement\n(blocage de la soupape de\ncommande d’aspiration)",
    "Rupture du câblage spécifique\nà l’injecteur du vérin numéro 1",
    "Court-circuit de la bobine de\nl’injecteur du vérin numéro 1\nentre les bornes COM et TWV",
    "Circuit ouvert MOS de\ndécharge de l’injecteur du vérin\nnuméro 1",
    "Rupture du câblage spécifique\nà l’injecteur du vérin numéro 2",
    "Court-circuit de la bobine de\nl’injecteur du vérin numéro 2\nentre les bornes COM et TWV",
    "Circuit ouvert MOS de\ndécharge de l’injecteur du vérin\nnuméro 2",
    "Rupture du câblage spécifique\nà l’injecteur du vérin numéro 3",
    "Court-circuit de la bobine de\nl’injecteur du vérin numéro 3\nentre les bornes COM et TWV",
    "Circuit ouvert MOS de\ndécharge de l’injecteur du vérin\nnuméro 3",
    "Rupture du câblage spécifique\nà l’injecteur du vérin numéro 4",
    "Court-circuit de la bobine de\nl’injecteur du vérin numéro 4\nentre les bornes COM et TWV",
    "Circuit ouvert MOS de\ndécharge de l’injecteur du vérin\nnuméro 4",
    "Erreur de tension du capteur\nde pression côté EGR haute\npression (élevée)",
    "Erreur de tension du capteur\nde pression côté EGR haute\npression (faible)",
    "Valeur d’apprentissage\nanormale du capteur de\npression côté EGR haute\npression",
    "Erreur de valeur détectée au\nniveau du capteur de pression\ncôté EGR haute pression",
    "Erreur de protection de la\npompe haute pression",
    "Erreur de remplacement de la\npompe haute pression",
    "Mise hors tension sans\nmaintien du relais principal",
    "Faible niveau du réservoir\nd’urée aqueuse (incitation 1)",
    "Faible niveau du réservoir\nd’urée aqueuse (incitation 2)",
    "Rupture du câblage du capteur\nde niveau du réservoir d’urée\naqueuse",
    "Court-circuit du capteur de\nniveau du réservoir d’urée\naqueuse (AT1T1I)",
    "Erreur interne du contrôleur du\ncapteur de niveau du réservoir\nd’urée aqueuse (AT1T1I)",
    "Erreur de valeur détectée au\nniveau du capteur de niveau\ndu réservoir d’urée aqueuse",
    "Rupture du câblage de la\nbobine du moteur EGR",
    "Erreur de retour EGR",
    "Erreur de données EGR de\nl’ECM",
    "Erreur de tension EGR (tension\nexcessive)",
    "Erreur de tension EGR (faible)",
    "Court-circuit +B de la rangée\nd’injecteurs 1",
    "Court-circuit à la masse de la\nrangée d’injecteurs 1 ",
    "Rupture du câblage de la\nrangée d’injecteurs 1",
    "Erreur de l’horloge interne\nVDIC3 du pilote d’injecteur\nIC-1",
    "Erreur de communication du\npilote d’injecteur IC-1 entre\nVDIC3 et le micro-ordinateur",
    "Court-circuit +B de la rangée\nd’injecteurs 2",
    "Court-circuit à la masse de la\nrangée d’injecteurs 2 ",
    "Rupture du câblage de la\nrangée d’injecteurs 2",
    "Erreur de l’horloge interne\nVDIC3 du pilote d’injecteur\nIC-2",
    "Erreur de communication du\npilote d’injecteur IC-2 entre\nVDIC3 et le micro-ordinateur",
    "Rupture du câblage du circuit\nd’entraînement du papillon des\ngaz d’admission",
    "Court-circuit VB/à la masse du\ncircuit d’entraînement du\npapillon des gaz d’admission ",
    "Erreur d’écart du circuit\nd’entraînement du papillon des\ngaz d’admission",
    "Erreur du cycle d’entraînement\ndu circuit d’entraînement du\npapillon des gaz d’admission",
    "Augmentation de la\ntempérature du contrôleur du\ncapteur de température du\nréservoir d’urée aqueuse/du\ncapteur de niveau du réservoir\nd’urée aqueuse (AT1T1I)",
    "Rupture du câblage du circuit\ninterne du capteur de\ntempérature du réservoir\nd’urée aqueuse (AT1T1I)",
    "Court-circuit du circuit interne\ndu capteur de température du\nréservoir d’urée aqueuse\n(AT1T1I)",
    "Panne interne du contrôleur du\ncapteur de température du\nréservoir d’urée aqueuse\n(AT1T1I)",
    "Augmentation de la\ntempérature du réservoir\nd’urée aqueuse",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature du réservoir\nd’urée aqueuse (erreur de\nlimite supérieure)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature du réservoir\nd’urée aqueuse (erreur de\nlimite inférieure)",
    "Erreur de valeur détectée au\nniveau du capteur NOx en\namont SCR (erreur de limite\nsupérieure)",
    "Erreur de valeur détectée au\nniveau du capteur NOx en\namont SCR (erreur de limite\ninférieure)",
    "Erreur de tension du capteur\nde température d’admission du\nDPF (élevée)",
    "Erreur de tension du capteur\nde température d’admission du\nDPF (faible)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature d’admission du\nDPF",
    "Augmentation de la\ntempérature d’admission du\nDPF",
    "Erreur de tension du capteur\nde température intermédiaire\ndu DPF (élevée)",
    "Erreur de tension du capteur\nde température intermédiaire\ndu DPF (faible)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature intermédiaire du\nDPF",
    "Chute de la température\nintermédiaire du DPF",
    "Augmentation de la\ntempérature intermédiaire du\nDPF (panne après injection)",
    "Erreur de tension du capteur\nde pression différentielle du\nDPF (élevée)",
    "Erreur de tension du capteur\nde pression différentielle du\nDPF (faible)",
    "Valeur d’apprentissage\nanormale du capteur de\npression différentielle du DPF",
    "Augmentation de la pression\ndifférentielle du DPF",
    "Augmentation de la\ntempérature du contrôleur du\ncapteur de qualité de l’urée\naqueuse/du capteur de\ntempérature du réservoir\nd’urée aqueuse (A1DEFI)",
    "Rupture du câblage du circuit\ninterne du capteur de\ntempérature du réservoir\nd’urée aqueuse (A1DEFI)",
    "Court-circuit du circuit interne\ndu capteur de température du\nréservoir d’urée aqueuse\n(A1DEFI)",
    "Panne interne du contrôleur du\ncapteur de température du\nréservoir d’urée aqueuse\n(A1DEFI)",
    "Rupture du câblage du circuit\ninterne du capteur de qualité\nde l’urée aqueuse",
    "Court-circuit du circuit interne\ndu capteur de qualité de l’urée\naqueuse",
    "Panne interne du contrôleur du\ncapteur de qualité de l’urée\naqueuse",
    "Erreur de concentration du\ncapteur de qualité de l’urée\naqueuse (petit écart)",
    "Erreur de concentration du\ncapteur de qualité de l’urée\naqueuse (grand écart)",
    "Contamination du réservoir\nd’urée aqueuse",
    "Erreur de tension du capteur\nde pression côté DPF haute\npression (élevée)",
    "Erreur de tension du capteur\nde pression côté DPF haute\npression (faible)",
    "Erreur de valeur détectée au\nniveau du capteur de pression\ncôté DPF haute pression",
    "Régénération fixe en mode\nveille du DPF",
    "Échec de la régénération du\nDPF (échec de la régénération\nde récupération)",
    "Régénération de récupération\ndu DPF inhibée",
    "Mode de secours du DPF",
    "Demande de nettoyage des\ncendres du DPF 1",
    "Demande de nettoyage des\ncendres du DPF 2",
    "Erreur de tension du capteur\nde pression de la pompe du\nmodule d’alimentation (élevée)",
    "Erreur de tension du capteur\nde pression de la pompe du\nmodule d’alimentation (faible)",
    "Erreur de valeur détectée au\nniveau du capteur de pression\nde la pompe du module\nd’alimentation (erreur de limite\nsupérieure)",
    "Erreur de valeur détectée au\nniveau du capteur de pression\nde la pompe du module\nd’alimentation (erreur de limite\ninférieure)",
    "Court-circuit VB côté L du\nchauffage du flexible d’urée\naqueuse (pression)",
    "Court-circuit à la masse côté L\ndu chauffage du flexible d’urée\naqueuse (pression)",
    "Rupture du câblage du\nchauffage du flexible d’urée\naqueuse (pression)",
    "Court-circuit VB côté L du\nchauffage du flexible d’urée\naqueuse (refoulement)",
    "Court-circuit à la masse côté L\ndu chauffage du flexible d’urée\naqueuse (refoulement)",
    "Rupture du câblage du\nchauffage du flexible d’urée\naqueuse (refoulement)",
    "Court-circuit VB côté L du\nchauffage du flexible d’urée\naqueuse (aspiration)",
    "Court-circuit à la masse côté L\ndu chauffage du flexible d’urée\naqueuse (aspiration)",
    "Rupture du câblage du\nchauffage du flexible d’urée\naqueuse (aspiration)",
    "Erreur de tension du capteur\nde température en amont du\ncatalyseur SCR (élevée)",
    "Erreur de tension du capteur\nde température en amont du\ncatalyseur SCR (faible)",
    "Augmentation de la\ntempérature en amont du\ncatalyseur SCR",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature en amont du\ncatalyseur SCR (erreur de limite\nsupérieure)",
    "Erreur de valeur détectée au\nniveau du capteur température\nen amont du catalyseur SCR\n(erreur de limite inférieure)",
    "Erreur de valeur détectée au\nniveau du capteur de\ntempérature en amont du\ncatalyseur SCR lors de la\nvérification du démarrage à\nfroid",
    "Court-circuit VB du câblage du\nsignal PWM du module\nd’approvisionnement (moteur\nde la pompe)",
    "Court-circuit à la masse du\ncâblage du signal PWM du\nmodule d’approvisionnement\n(moteur de la pompe)",
    "Rupture du câblage du signal\nPWM du module\nd’approvisionnement (moteur\nde la pompe)",
    "Erreur d’entraînement du\nmodule d’approvisionnement\n(moteur de la pompe) 1",
    "Erreur d’entraînement du\nmodule d’approvisionnement\n(moteur de la pompe) 2",
    "Erreur de validité du capteur\nde pression différentielle du\nDPF/retrait du matériel de la\nbase du DPF",
    "Court-circuit à la masse côté L\nde la soupape de chauffage du\nréservoir",
    "Rupture du câblage de la\nsoupape de chauffage du\nréservoir",
    "Erreur de communication de\nl’ECU entre les\nmicro-ordinateurs (erreur de\ncommunication MSC)",
    "Erreur de communication de\nl’ECU entre les\nmicro-ordinateurs (erreur de\ncommunication SPI basée sur\nle diagnostic d’erreur du\ncapteur de pression\natmosphérique)",
    "Erreur de communication de\nl’ECU entre les\nmicro-ordinateurs (erreur de\ncommunication SPI basée sur\nle diagnostic d’erreur du\nmicro-ordinateur de\nsurveillance)",
    "Erreur du convertisseur A/D du\nmicro-ordinateur de l’ECU",
    "Trajectoire d’arrêt d’injection\nanormale au niveau du\nmicro-ordinateur de l’ECU",
    "Court-circuit +B du témoin de\npréchauffage",
    "Court-circuit +B du témoin\nd’anomalie",
    "Court-circuit +B du relais du\ndémarreur",
    "Court-circuit +B du témoin de\nchute hydraulique",
    "Court-circuit +B du témoin\nd’avertissement orange",
    "Court-circuit +B du témoin\nd’affichage du changement de\nvitesse",
    "Court-circuit +B du témoin\nd’alarme de la température\nd’échappement",
    "Court-circuit +B du témoin\nd’alarme de la température du\nliquide de refroidissement du\nmoteur",
    "Court-circuit +B de l’avertisseur",
    "Court-circuit +B du témoin\nd’arrêt du moteur rouge",
    "Court-circuit +B du témoin\nisochrone",
    "Court-circuit +B du témoin\nd’approbation de la\nrégénération du DPF",
    "Court-circuit +B du témoin\nd’interdiction de la\nrégénération du DPF",
    "Court-circuit +B du témoin de\ndemande de régénération du\nDPF",
    "Erreur du système EGR\n(incitation 1)",
    "Erreur du système EGR\n(incitation 2)",
    "Consigne d’action FS du\nsystème ECU 2",
    "Erreur de valeur détectée au\nniveau du capteur NOx en\namont SCR (concentration O2)",
    "Court-circuit VB/rupture du\ncâblage du relais d’aide au\ndémarrage",
    "Court-circuit à la masse du\nrelais d’aide au démarrage",
    "Obstruction du filtre à air",
    "Erreur du séparateur d’eau et\nd’huile",
    "Erreur du signal du vilebrequin",
    "Aucun signal du vilebrequin",
    "Erreur du signal de l’arbre à\ncame",
    "Aucun signal de l’arbre à came",
    "Accumulation excessive de PM\ndu DPF (méthode C)",
    "Accumulation excessive de PM\ndu DPF (méthode P)",
    "Erreur de régénération du DPF\n(échec de la régénération fixe)",
    "Erreur de régénération du DPF\n(régénération fixe non\neffectuée)",
    "Court-circuit de la bobine du\nmoteur EGR",
    "Erreur du capteur de position\nEGR",
    "Blocage de la soupape EGR",
    "Erreur d’initialisation EGR",
    "Erreur de la thermistance haute\ntempérature EGR",
    "Erreur de la thermistance basse\ntempérature EGR",
    "Expiration de la réception CAN\n(TSC1 (SA1))",
    "Expiration de la réception CAN\n(TSC1 (SA2))",
    "Expiration de la réception CAN\n(Y_ECR1)",
    "Expiration de la réception CAN\n(Y_EC)",
    "Expiration de la réception CAN\n(Y_RSS)",
    "Expiration de la réception CAN\nde la soupape EGR",
    "Valeur cible EGR hors de\nportée",
    "Expiration de la réception CAN\n(EBC1)",
    "Expiration de la réception CAN\n(Y_DRFIF)",
    "Erreur de position ouverte du\ndouble capteur d’accélération",
    "Erreur de position fermée du\ndouble capteur d’accélération",
    "Apprentissage de la pompe\nhaute pression non effectué",
    "Erreur IC de surveillance du\nprocesseur de l’ECU",
    "Erreur du processeur de l’ECU",
    "Erreur de saisie de correction\ndes données QR",
    "Erreur de charge du circuit\nd’entraînement de l’injecteur\n(faible charge)",
    "Erreur de charge du circuit\nd’entraînement de l’injecteur\n(surcharge)",
    "Erreur de la somme de\ncontrôle de la mémoire Flash\nROM de l’ECU",
    "Erreur de tension du circuit 5 V\ndu capteur de l’ECU 1 (faible)",
    "Erreur de tension du circuit 5 V\ndu capteur de l’ECU 1 (élevée)",
    "Erreur de tension du circuit 5 V\ndu capteur de l’ECU 2 (faible)",
    "Erreur de tension du circuit 5 V\ndu capteur de l’ECU 2 (élevée)",
    "Données QR non écrites",
    "Erreur des données QR",
    "Pas de saisie du capteur de\nvitesse du vilebrequin/du\ncapteur de vitesse de l’arbre à\ncale (simultanée)",
    "Expiration de la réception CAN\ndu DCU",
    "Court-circuit VB côté H du\nmodule d’approvisionnement\n(soupape d’inversion)",
    "Court-circuit GND côté H du\nmodule d’approvisionnement\n(soupape d’inversion)",
    "Court-circuit VB côté H du\nrelais du chauffage du\nflexible/de la soupape de\nchauffage du réservoir",
    "Court-circuit à la masse côté H\ndu relais du chauffage du\nflexible/de la soupape de\nchauffage du réservoir",
    "Court-circuit VB côté H du\nmodule d’approvisionnement\n(chauffage du module\nd’approvisionnement) ",
    "Court-circuit à la masse côté H\ndu module\nd’approvisionnement\n(chauffage du module\nd’approvisionnement) ",
    "Rupture du câblage du module\nd’approvisionnement\n(chauffage du module\nd’approvisionnement)",
    "Erreur de valeur détectée au\nniveau du module\nd’approvisionnement\n(chauffage du module\nd’approvisionnement)",
    "Fin forcée du système SCR",
    "Erreur de la tension\nd’alimentation DCU (élevée 1)",
    "Erreur de la tension\nd’alimentation DCU (faible 2)",
    "Erreur de la tension\nd’alimentation DCU (élevée 2)",
    "Erreur de la tension\nd’alimentation DCU (faible 1)",
    "Blocage du relais principal",
    "Ouverture anticipée du relais\nprincipal",
    "Expiration de la réception CAN\ndu capteur NOx en amont SCR",
    "Expiration de la réception CAN\ndu capteur NOx en aval SCR",
    "Expiration de la réception CAN\ndu ECU ",
    "Erreur de tension de\nl’alimentation du capteur DCU",
    "Erreur de communication SPI\nDCU 1",
    "Erreur de communication SPI\nDCU 2",
    "Court-circuit côté H/L du\nmodule de dosage",
    "Rupture du câblage du module\nde dosage",
    "Court-circuit VB côté H du\nmodule de dosage",
    "Court-circuit à la masse du\nmodule de dosage",
    "Blocage de la soupape du\nmodule de dosage",
    "Erreur de lecture de la\nmémoire EEPROM",
    "Erreur d’écriture dans la\nmémoire EEPROM",
    "Court-circuit VB côté L du\nrelais du chauffage du flexible",
    "Court-circuit à la masse côté L\ndu relais du chauffage du\nflexible",
    "Rupture du câblage du relais\ndu chauffage du flexible",
    "Court-circuit VB côté L du\nmodule d’approvisionnement\n(chauffage du module\nd’approvisionnement) ",
    "Court-circuit VB côté L de la\nsoupape de chauffage du\nréservoir",
    "Augmentation de la valeur\nNOx en amont SCR",
    "Court-circuit du circuit interne\ndu capteur NOx en amont SCR",
    "Rupture du câblage du circuit\ninterne du capteur NOx en\namont SCR",
    "Augmentation de la valeur\nNOx en aval SCR",
    "Court-circuit du circuit interne\ndu capteur NOx en aval SCR",
    "Rupture du câblage du circuit\ninterne du capteur NOx en aval\nSCR",
    "Chauffage incomplet du\ncapteur NOx en amont SCR",
    "Chauffage incomplet du\ncapteur NOx en aval SCR",
    "Court-circuit VB côté L du\nmodule d’approvisionnement\n(soupape d’inversion)",
    "Court-circuit à la masse côté L\ndu module\nd’approvisionnement (soupape\nd’inversion)",
    "Rupture du câblage du module\nd’approvisionnement (soupape\nd’inversion)",
    "Nettoyage NOx inefficace du\nsystème SCR",
    "Erreur de valeur détectée au\nniveau du module\nd’approvisionnement (capteur\nde température du chauffage\ndu module\nd’approvisionnement)",
    "Erreur de valeur détectée au\nniveau du module\nd’approvisionnement (capteur\nde température du chauffage\ndu module\nd’approvisionnement) lors de la\nvérification du démarrage à\nfroid",
    "Erreur de valeur détectée au\nniveau du module\nd’approvisionnement (capteur\nde température du module\nd’approvisionnement)",
    "Erreur de valeur détectée au\nniveau du module\nd’approvisionnement (capteur\nde température du module\nd’approvisionnement) lors de la\nvérification du démarrage à\nfroid",
    "Valeur erronée du module\nd’approvisionnement (capteur\nde température du chauffage\ndu module\nd’approvisionnement) reçue\npour la valeur du cycle\nd’informations de température",
    "Valeur incorrecte du module\nd’approvisionnement (capteur\nde température du chauffage\ndu module\nd’approvisionnement) reçue\npour la valeur du cycle\nd’informations de température",
    "Erreur du cycle PWM des\ninformations de température\ndu module d’alimentation\n(moteur de la pompe)",
    "Erreur du signal PWM des\ninformations de température\ndu module d’alimentation\n(moteur de la pompe)",
    "Valeur erronée du module\nd’approvisionnement (capteur\nde température du module\nd’approvisionnement) reçue\npour la valeur du cycle\nd’informations de température",
    "Valeur incorrecte du module\nd’approvisionnement (capteur\nde température du module\nd’approvisionnement) reçue\npour la valeur du cycle\nd’informations de température",
    "Le module d’alimentation\n(moteur de la pompe) ne\ndémarre pas pour mesurer la\ntempérature",
    "Augmentation de la pression\ndu module\nd’approvisionnement (moteur\nde la pompe) 1",
    "Erreur de réduction de la\npression du module\nd’approvisionnement (moteur\nde la pompe)",
    "Augmentation de la pression\ncôté refoulement du flexible\nd’urée aqueuse",
    "Augmentation de la pression\ncôté pression du flexible d’urée\naqueuse",
    "Erreur de stabilité de la\npression du module\nd’approvisionnement (moteur\nde la pompe)",
    "Panne du module\nd’approvisionnement (soupape\nd’inversion)",
    "Erreur d’aspiration de l’urée\naqueuse du module\nd’approvisionnement",
    "Augmentation de la pression\ndu module\nd’approvisionnement (moteur\nde la pompe) 2",
    "Chute de pression du module\nd’approvisionnement",
    "Augmentation de la pression\nde l’urée aqueuse du module\nd’approvisionnement",
    "Augmentation de la\ntempérature du réservoir\nd’urée aqueuse",
    "Expiration de la réception CAN\n(A1DEFI)",
    "Expiration de la réception CAN\n(AT1T1I)",
    "Erreur du système SCR\n(incitation 1)",
    "Erreur du système SCR\n(incitation 2)",
    "Consigne d’action FS du\nsystème ECU 1",
    "Rupture du câblage du contact",
    "Erreur de vérification des\ndonnées entre l’ECU et le DCU\n(expiration de la vérification)"
	};
