
																
static const char *V_EngErrorMSG_ENG[308]={	
    "Accelerator sensor 2 voltage error\n(high)",
    "Accelerator sensor 2 voltage error\n(low)",
    "Foot pedal sensor open position\nerror",
    "Foot pedal sensor closed position\nerror",
    "Accelerator sensor 3 voltage error\n(high)",
    "Accelerator sensor 3 voltage error\n(low)",
    "Intake throttle position sensor\nvoltage error (high)",
    "Intake throttle position sensor\nvoltage error (low)",
    "Accelerator sensor 1 voltage error\n(high)",
    "Accelerator sensor 1 voltage error\n(low)",
    "Oil pressure sensor voltage error\n(high)",
    "Oil pressure sensor voltage error\n(low)",
    "Oil pressure drop",
    "EGR low-pressure side pressure\nsensor voltage error (high)",
    "EGR low-pressure side pressure\nsensor voltage error (low)",
    "EGR low-pressure side pressure\nsensor abnormal learning value",
    "EGR low-pressure side pressure\nsensor detected value error",
    "Intake manifold temperature sensor\nvoltage error (high)",
    "Intake manifold temperature sensor\nvoltage error (low)",
    "Intake manifold temperature sensor\ndetected value error",
    "Atmospheric pressure sensor voltage\nerror (high)",
    "Atmospheric pressure sensor voltage\nerror (low)",
    "Atmospheric pressure sensor\ncharacteristic error",
    "Engine coolant temperature sensor\nvoltage error (high)",
    "Engine coolant temperature sensor\nvoltage error (low)",
    "Engine coolant temperature rise\n(overheat)",
    "Engine coolant temperature sensor\ndetected value error",
    "Rail pressure sensor voltage error\n(high)",
    "Rail pressure sensor voltage error\n(low)",
    "Excessive rail pressure rise",
    "Rail pressure deviation error (low rail\npressure)",
    "Charge switch wiring break",
    "Charge error",
    "Ambient air temperature sensor\nvoltage error (high)",
    "Ambient air temperature sensor\nvoltage error (low)",
    "Ambient air temperature sensor\ndetected value error",
    "ECU invalid ambient air temperature\nvalue reception",
    "Exhaust manifold temperature\nsensor voltage error (high)",
    "Exhaust manifold temperature\nsensor voltage error (low)",
    "Exhaust manifold temperature\nsensor detected value error",
    "Fuel temperature sensor voltage\nerror (high)",
    "Fuel temperature sensor voltage\nerror (low)",
    "Fuel temperature rise",
    "Excessive speed",
    "CAN reception timeout (VI)",
    "CAN received data error (VI)",
    "EGR gas temperature sensor voltage\nerror (high)",
    "EGR gas temperature sensor voltage\nerror (low)",
    "EGR gas temperature sensor\ndetected value error",
    "Data verification error between ECU\nand DCU (engine model mismatch)",
    "Data verification error between ECU\nand DCU (serial No. mismatch)",
    "EEPROM error",
    "Suction control valve (magnetic\nproportional valve) H/L-side VB short\ncircuit",
    "Suction control valve (magnetic\nproportional valve) H-side GND short\ncircuit/wiring break",
    "Drive circuit error (suction control\nvalve sticking)",
    "No. 1 cylinder injector-specific wiring\nbreak",
    "No. 1 cylinder injector coil short\ncircuit between COM and TWV\nterminals",
    "No. 1 cylinder injector discharge\nMOS open circuit",
    "No. 2 cylinder injector-specific wiring\nbreak",
    "No. 2 cylinder injector coil short\ncircuit between COM and TWV\nterminals",
    "No. 2 cylinder injector discharge\nMOS open circuit",
    "No. 3 cylinder injector-specific wiring\nbreak",
    "No. 3 cylinder injector coil short\ncircuit between COM and TWV\nterminals",
    "No. 3 cylinder injector discharge\nMOS open circuit",
    "No. 4 cylinder injector-specific wiring\nbreak",
    "No. 4 cylinder injector coil short\ncircuit between COM and TWV\nterminals",
    "No. 4 cylinder injector discharge\nMOS open circuit",
    "EGR high-pressure side pressure\nsensor voltage error (high)",
    "EGR high-pressure side pressure\nsensor voltage error (low)",
    "EGR high-pressure side pressure\nsensor abnormal learning value",
    "EGR high-pressure side pressure\nsensor detected value error",
    "High-pressure pump protection error",
    "High-pressure pump replacement\nerror",
    "Power off without main relay\nself-holding",
    "Low aqueous urea tank level\n(inducement 1)",
    "Low aqueous urea tank level\n(inducement 2)",
    "Aqueous urea tank level sensor\nwiring break",
    "Aqueous urea tank level sensor\n(AT1T1I) short circuit",
    "Aqueous urea tank level sensor\n(AT1T1I) controller internal error",
    "Aqueous urea tank level sensor\ndetected value error",
    "EGR motor coil wiring break",
    "EGR feedback error",
    "EGR ECM data error",
    "EGR voltage error (overvoltage)",
    "EGR voltage error (low)",
    "Injector bank 1 +B short circuit",
    "Injector bank 1 GND short circuit ",
    "Injector bank 1 wiring break",
    "Injector driver IC-1 VDIC3 internal\nclock error",
    "Injector driver IC-1 communication\nerror between VDIC3 and\nmicrocomputer",
    "Injector bank 2 +B short circuit",
    "Injector bank 2 GND short circuit ",
    "Injector bank 2 wiring break",
    "Injector driver IC-2 VDIC3 internal\nclock error",
    "Injector driver IC-2 communication\nerror between VDIC3 and\nmicrocomputer",
    "Intake throttle drive circuit wiring\nbreak",
    "Intake throttle drive circuit VB/GND\nshort circuit ",
    "Intake throttle drive circuit deviation\nerror",
    "Intake throttle drive circuit drive duty\nerror",
    "Aqueous urea tank temperature\nsensor/Aqueous urea tank level\nsensor (AT1T1I) controller\ntemperature rise",
    "Aqueous urea tank temperature\nsensor (AT1T1I) internal circuit\nwiring break",
    "Aqueous urea tank temperature\nsensor (AT1T1I) internal circuit short\ncircuit",
    "Aqueous urea tank temperature\nsensor (AT1T1I) controller internal\nfailure",
    "Aqueous urea tank temperature rise",
    "Aqueous urea tank temperature\nsensor detected value error (upper\nlimit error)",
    "Aqueous urea tank temperature\nsensor detected value error (lower\nlimit error)",
    "SCR upstream NOx sensor detected\nvalue error (upper limit error)",
    "SCR upstream NOx sensor detected\nvalue error (lower limit error)",
    "DPF inlet temperature sensor\nvoltage error (high)",
    "DPF inlet temperature sensor\nvoltage error (low)",
    "DPF inlet temperature sensor\ndetected value error",
    "DPF inlet temperature rise",
    "DPF intermediate temperature\nsensor voltage error (high)",
    "DPF intermediate temperature\nsensor voltage error (low)",
    "DPF intermediate temperature\nsensor detected value error",
    "DPF intermediate temperature drop",
    "DPF intermediate temperature rise\n(post-injection failure)",
    "DPF differential pressure sensor\nvoltage error (high)",
    "DPF differential pressure sensor\nvoltage error (low)",
    "DPF differential pressure sensor\nabnormal learning value",
    "DPF differential pressure rise",
    "Aqueous urea quality\nsensor/Aqueous urea tank\ntemperature sensor (A1DEFI)\ncontroller temperature rise",
    "Aqueous urea tank temperature\nsensor (A1DEFI) internal circuit\nwiring break",
    "Aqueous urea tank temperature\nsensor (A1DEFI) internal circuit short\ncircuit",
    "Aqueous urea tank temperature\nsensor (A1DEFI) controller internal\nfailure",
    "Aqueous urea quality sensor internal\ncircuit wiring break",
    "Aqueous urea quality sensor internal\ncircuit short circuit",
    "Aqueous urea quality sensor\ncontroller internal failure",
    "Aqueous urea quality sensor\nconcentration error (small deviation)",
    "Aqueous urea quality sensor\nconcentration error (large deviation)",
    "Aqueous urea tank contamination",
    "DPF high-pressure side pressure\nsensor voltage error (high)",
    "DPF high-pressure side pressure\nsensor voltage error (low)",
    "DPF high-pressure side pressure\nsensor detected value error",
    "DPF stationary regeneration standby",
    "DPF regeneration failure (recovery\nregeneration failure)",
    "DPF recovery regeneration inhibited",
    "DPF backup mode",
    "DPF ash cleaning request 1",
    "DPF ash cleaning request 2",
    "Supply module pump pressure\nsensor voltage error (high)",
    "Supply module pump pressure\nsensor voltage error (low)",
    "Supply module pump pressure\nsensor detected value error (upper\nlimit error)",
    "Supply module pump pressure\nsensor detected value error (lower\nlimit error)",
    "Aqueous urea hose heater\n(pressure) L-side VB short circuit",
    "Aqueous urea hose heater\n(pressure) L-side GND short circuit",
    "Aqueous urea hose heater\n(pressure) wiring break",
    "Aqueous urea hose heater\n(backflow) L-side VB short circuit",
    "Aqueous urea hose heater\n(backflow) L-side GND short circuit",
    "Aqueous urea hose heater\n(backflow) wiring break",
    "Aqueous urea hose heater (suction)\nL-side VB short circuit",
    "Aqueous urea hose heater (suction)\nL-side GND short circuit",
    "Aqueous urea hose heater (suction)\nwiring break",
    "SCR catalyst upstream temperature\nsensor voltage error (high)",
    "SCR catalyst upstream temperature\nsensor voltage error (low)",
    "SCR catalyst upstream temperature\nrise",
    "SCR catalyst upstream temperature\nsensor detected value error (upper\nlimit error)",
    "SCR catalyst upstream temperature\nsensor detected value error (lower\nlimit error)",
    "SCR catalyst upstream temperature\nsensor detected value error at cold\nstart check",
    "Supply module (pump motor) PWM\nsignal wiring VB short circuit",
    "Supply module (pump motor) PWM\nsignal wiring GND short circuit",
    "Supply module (pump motor) PWM\nsignal wiring break",
    "Supply module (pump motor) drive\nerror 1",
    "Supply module (pump motor) drive\nerror 2",
    "DPF base material removal/DPF\ndifferential pressure sensor validity\nerror",
    "Tank heating valve L-side GND short\ncircuit",
    "Tank heating valve wiring break",
    "ECU communication error between\nmicrocomputers (MSC\ncommunication error)",
    "ECU communication error between\nmicrocomputers (SPI communication\nerror based on atmospheric pressure\nsensor error diagnosis)",
    "ECU communication error between\nmicrocomputers (SPI communication\nerror based on monitoring\nmicrocomputer error diagnosis)",
    "ECU microcomputer A/D converter\nerror",
    "Abnormal injection stop path at ECU\nmicrocomputer error",
    "Preheating lamp +B short circuit",
    "Fault lamp +B short circuit",
    "Starter relay +B short circuit",
    "Hydraulic drop lamp +B short circuit",
    "Amber warning lamp +B short circuit",
    "Speed change display lamp +B short\ncircuit",
    "Exhaust temperature alarm lamp +B\nshort circuit",
    "Engine coolant temperature alarm\nlamp +B short circuit",
    "Buzzer +B short circuit",
    "Red engine stop lamp +B short\ncircuit",
    "Isochronous lamp +B short circuit",
    "DPF regeneration approval lamp +B\nshort circuit",
    "DPF regeneration prohibition lamp\n+B short circuit",
    "DPF regeneration request lamp +B\nshort circuit",
    "EGR system error (inducement 1)",
    "EGR system error (inducement 2)",
    "ECU system FS action instruction 2",
    "SCR upstream NOx sensor detected\nvalue error (O2 concentration)",
    "Starting aid relay wiring break/VB\nshort circuit",
    "Starting aid relay GND short circuit",
    "Air cleaner clogging",
    "Oil and water separator error",
    "Crankshaft signal error",
    "No signal from crankshaft",
    "Camshaft signal error",
    "No signal from camshaft",
    "DPF excessive PM accumulation\n(method C)",
    "DPF excessive PM accumulation\n(method P)",
    "DPF regeneration error (stationary\nregeneration failure)",
    "DPF regeneration error (stationary\nregeneration not operated)",
    "EGR motor coil short circuit",
    "EGR position sensor error",
    "EGR valve sticking",
    "EGR initialization error",
    "EGR high-temperature thermistor\nerror",
    "EGR low-temperature thermistor\nerror",
    "CAN reception timeout (TSC1 (SA1))",
    "CAN reception timeout (TSC1 (SA2))",
    "CAN reception timeout (Y_ECR1)",
    "CAN reception timeout (Y_EC)",
    "CAN reception timeout (Y_RSS)",
    "CAN reception timeout from EGR\nvalve",
    "EGR target value out of range",
    "CAN reception timeout (EBC1)",
    "CAN reception timeout (Y_DRFIF)",
    "Dual accelerator sensor open\nposition error",
    "Dual accelerator sensor closed\nposition error",
    "High-pressure pump learning not\nperformed",
    "ECU CPU monitoring IC error",
    "ECU CPU error",
    "QR data correction input error",
    "Injector drive circuit charge error (low\ncharge)",
    "Injector drive circuit charge error\n(overcharge)",
    "ECU flash ROM checksum error",
    "ECU sensor 5V circuit 1 voltage error\n(low)",
    "ECU sensor 5V circuit 1 voltage error\n(high)",
    "ECU sensor 5V circuit 2 voltage error\n(low)",
    "ECU sensor 5V circuit 2 voltage error\n(high)",
    "QR data not written",
    "QR data error",
    "No crankshaft speed\nsensor/camshaft speed sensor input\n(simultaneous)",
    "CAN reception timeout from DCU",
    "Supply module (reverting valve)\nH-side VB short circuit",
    "Supply module (reverting valve)\nH-side GND short circuit",
    "Hose heater relay/Tank heating\nvalve H-side VB short circuit",
    "Hose heater relay/Tank heating\nvalve H-side GND short circuit",
    "Supply module (supply module\nheater) H-side VB short circuit ",
    "Supply module (supply module\nheater) H-side GND short circuit ",
    "Supply module (supply module\nheater) wiring break",
    "Supply module (supply module\nheater) detected value error",
    "SCR system forced termination",
    "DCU supply voltage error (high 1)",
    "DCU supply voltage error (low 2)",
    "DCU supply voltage error (high 2)",
    "DCU supply voltage error (low 1)",
    "Main relay sticking",
    "Main relay early opening",
    "CAN reception timeout from SCR\nupstream NOx sensor",
    "CAN reception timeout from SCR\ndownstream NOx sensor",
    "CAN reception timeout from ECU ",
    "DCU sensor supply voltage error",
    "DCU SPI communication error 1",
    "DCU SPI communication error 2",
    "Dosing module H/L-side short circuit",
    "Dosing module wiring break",
    "Dosing module H-side VB short\ncircuit",
    "Dosing module GND short circuit",
    "Dosing module valve sticking",
    "EEPROM memory reading error",
    "EEPROM memory writing error",
    "Hose heater relay L-side VB short\ncircuit",
    "Hose heater relay L-side GND short\ncircuit",
    "Hose heater relay wiring break",
    "Supply module (supply module\nheater) L-side VB short circuit ",
    "Tank heating valve L-side VB short\ncircuit",
    "SCR upstream NOx value rise",
    "SCR upstream NOx sensor internal\ncircuit short circuit",
    "SCR upstream NOx sensor internal\ncircuit wiring break",
    "SCR downstream NOx value rise",
    "SCR downstream NOx sensor\ninternal circuit short circuit",
    "SCR downstream NOx sensor\ninternal circuit wiring break",
    "SCR upstream NOx sensor\nincomplete heating",
    "SCR downstream NOx sensor\nincomplete heating",
    "Supply module (reverting valve)\nL-side VB short circuit",
    "Supply module (reverting valve)\nL-side GND short circuit",
    "Supply module (reverting valve)\nwiring break",
    "SCR system inefficient NOx cleaning",
    "Supply module (supply module\nheater temperature sensor) detected\nvalue error",
    "Supply module (supply module\nheater temperature sensor) detected\nvalue error at cold start check",
    "Supply module (supply module\ntemperature sensor) detected value\nerror",
    "Supply module (supply module\ntemperature sensor) detected value\nerror at cold start check",
    "Supply module (supply module\nheater temperature sensor) faulty\nvalue received for temperature\ninformation duty value",
    "Supply module (supply module\nheater temperature sensor) invalid\nvalue received for temperature\ninformation duty value",
    "Supply module (pump motor)\ntemperature information PWM cycle\nerror",
    "Supply module (pump motor)\ntemperature information PWM signal\nerror",
    "Supply module (supply module\ntemperature sensor) faulty value\nreceived for temperature information\nduty value",
    "Supply module (supply module\ntemperature sensor) invalid value\nreceived for temperature information\nduty value",
    "Supply module (pump motor) not\nstarting to measure temperature",
    "Supply module (pump motor)\npressure rise 1",
    "Supply module (pump motor)\npressure reduction error",
    "Aqueous urea hose backflow-side\npressure rise",
    "Aqueous urea hose pressure-side\npressure rise",
    "Supply module (pump motor)\npressure stability error",
    "Supply module (reverting valve)\nfailure",
    "Supply module aqueous urea\nsuckback error",
    "Supply module (pump motor)\npressure rise 2",
    "Supply module pressure drop",
    "Supply module aqueous urea\npressure rise",
    "Aqueous urea tank temperature rise",
    "CAN reception timeout (A1DEFI)",
    "CAN reception timeout (AT1T1I)",
    "SCR system error (inducement 1)",
    "SCR system error (inducement 2)",
    "ECU system FS action instruction 1",
    "Key switch wiring break",
    "Data verification error between ECU\nand DCU (verification timeout)"
	};