
static const char *H_EngErrorMSG_DEU[308]={	
    "Spannungsfehler\nGaspedalsensor 2 (hoch)",
    "Spannungsfehler\nGaspedalsensor 2 (niedrig)",
    "Fehler offene Stellung\nFahrpedalsensor",
    "Fehler geschlossene Stellung\nFahrpedalsensor",
    "Spannungsfehler\nGaspedalsensor 3 (hoch)",
    "Spannungsfehler\nGaspedalsensor 3 (niedrig)",
    "Spannungsfehler\nAnsaugdrosselklappen-\nPositionssensor (hoch)",
    "Spannungsfehler\nAnsaugdrosselklappen-\nPositionssensor (niedrig)",
    "Spannungsfehler\nGaspedalsensor 1 (hoch)",
    "Spannungsfehler\nGaspedalsensor 1 (niedrig)",
    "Spannungsfehler Öldrucksensor\n(hoch)",
    "Spannungsfehler Öldrucksensor\n(niedrig)",
    "Öldruckabfall",
    "Spannungsfehler des\nDrucksensors auf\nEGR-Niederdruckseite (hoch)",
    "Spannungsfehler des\nDrucksensors auf\nEGR-Niederdruckseite (niedrig)",
    "Anormaler Lernwert am\nDrucksensor auf\nEGR-Niederdruckseite",
    "Fehler erkannter Wert am\nDrucksensor auf\nEGR-Niederdruckseite",
    "Spannungsfehler\nEinlasskrümmer-\nTemperatursensor (hoch)",
    "Spannungsfehler\nEinlasskrümmer-\nTemperatursensor (niedrig)",
    "Fehler erkannter Wert am\nEinlasskrümmer-\nTemperatursensor",
    "Spannungsfehler\nAtmosphärendrucksensor\n(hoch)",
    "Spannungsfehler\nAtmosphärendrucksensor\n(niedrig)",
    "Kennlinienfehler\nAtmosphärendrucksensor",
    "Spannungsfehler\nMotorkühlmittel-\nTemperatursensor (hoch)",
    "Spannungsfehler\nMotorkühlmittel-\nTemperatursensor (niedrig)",
    "Temperaturanstieg des\nMotorkühlmittels (Überhitzung)",
    "Fehler erkannter Wert am\nMotorkühlmittel-\nTemperatursensor",
    "Spannungsfehler\nKraftstoffleitungsdrucksensor\n(hoch)",
    "Spannungsfehler\nKraftstoffleitungsdrucksensor\n(niedrig)",
    "Übermäßiger Druckanstieg in\nder Kraftstoffleitung",
    "Abweichungsfehler\nKraftstoffleitungsdruck\n(niedriger Leitungsdruck)",
    "Ladeschalter-Kabelbruch",
    "Ladefehler",
    "Spannungsfehler\nUmgebungsluft-\nTemperatursensor (hoch)",
    "Spannungsfehler\nUmgebungsluft-\nTemperatursensor (niedrig)",
    "Fehler erkannter Wert am\nUmgebungsluft-\nTemperatursensor",
    "ECU empfängt ungültigen Wert\nder Umgebungslufttemperatur",
    "Spannungsfehler\nAuspuffkrümmer-\nTemperatursensor (hoch)",
    "Spannungsfehler\nAuspuffkrümmer-\nTemperatursensor (niedrig)",
    "Fehler erkannter Wert am\nAuspuffkrümmer-\nTemperatursensor",
    "Spannungsfehler\nKraftstofftemperatursensor\n(hoch)",
    "Spannungsfehler\nKraftstofftemperatursensor\n(niedrig)",
    "Temperaturanstieg des\nKraftstoffs",
    "Übermäßige Geschwindigkeit",
    "Zeitüberschreitung beim\nCAN-Empfang (VI)",
    "Fehler der CAN-Empfangsdaten\n(VI)",
    "Spannungsfehler\nEGR-Gastemperatursensor\n(hoch)",
    "Spannungsfehler\nEGR-Gastemperatursensor\n(niedrig)",
    "Fehler erkannter Wert am\nEGR-Gastemperatursensor",
    "Datenüberprüfungsfehler\nzwischen ECU und DCU\n(Abweichung Motortyp)",
    "Datenüberprüfungsfehler\nzwischen ECU und DCU\n(Abweichung Seriennummer)",
    "EEPROM-Fehler",
    "Ansaugregelventil\n(magnetisches\nProportionalventil) Kurzschluss\nam VB auf H/L-Seite",
    "Ansaugregelventil\n(magnetisches\nProportionalventil)\nKurzschluss/Kabelbruch an\nGND auf H-Seite",
    "Fehler im Steuerkreis\n(Ansaugsteuerventil klemmt)",
    "Kabelbruch an Injektorkabeln\nZylinder 1",
    "Kurzschluss zwischen den\nKlemmen COM und TWV in\nSpule von Injektor Zylinder 1",
    "Offener Stromkreis\nMOS-Auslauf des Injektors\nZylinder 1",
    "Kabelbruch an Injektorkabeln\nZylinder 2",
    "Kurzschluss zwischen den\nKlemmen COM und TWV in\nSpule von Injektor Zylinder 2",
    "Offener Stromkreis\nMOS-Auslauf des Injektors\nZylinder 2",
    "Kabelbruch an Injektorkabeln\nZylinder 3",
    "Kurzschluss zwischen den\nKlemmen COM und TWV in\nSpule von Injektor Zylinder 3",
    "Offener Stromkreis\nMOS-Auslauf des Injektors\nZylinder 3",
    "Kabelbruch an Injektorkabeln\nZylinder 4",
    "Kurzschluss zwischen den\nKlemmen COM und TWV in\nSpule von Injektor Zylinder 4",
    "Offener Stromkreis\nMOS-Auslauf des Injektors\nZylinder 4",
    "Spannungsfehler des\nDrucksensors auf\nEGR-Hochdruckseite (hoch)",
    "Spannungsfehler des\nDrucksensors auf\nEGR-Hochdruckseite (niedrig)",
    "Anormaler Lernwert am\nDrucksensor auf\nEGR-Hochdruckseite",
    "Fehler erkannter Wert am\nDrucksensor auf\nEGR-Hochdruckseite",
    "Fehler Schutz der\nHochdruckpumpe",
    "Fehler Austausch der\nHochdruckpumpe",
    "Stromabschaltung ohne\nSelbsthaltung des Hauptrelais",
    "Niedriger Füllstand des\nHarnstoff-Wasser-Tanks\n(Auslöser 1)",
    "Niedriger Füllstand des\nHarnstoff-Wasser-Tanks\n(Auslöser 2)",
    "Kabelbruch am Füllstandsensor\ndes Harnstoff-Wasser-Tanks",
    "Kurzschluss am Füllstandsensor\ndes Harnstoff-Wasser-Tanks\n(AT1T1I)",
    "Interner Steuerungsfehler\nFüllstandsensor des\nHarnstoff-Wasser-Tanks\n(AT1T1I)",
    "Fehler erkannter Wert am\nFüllstandsensor des\nHarnstoff-Wasser-Tanks",
    "Kabelbruch an EGR-Motorspule",
    "EGR-Feedbackfehler",
    "EGR ECM-Datenfehler",
    "EGR-Spannungsfehler\n(Überspannung)",
    "EGR-Spannungsfehler (niedrig)",
    "Kurzschluss Einspritzung Bank\n1 +B",
    "Kurzschluss Einspritzung Bank\n1 GND ",
    "Kabelbruch Einspritzung Bank 1",
    "Injektor-Antrieb IC-1 VDIC3\ninterner Taktfehler",
    "Injektor-Antrieb IC-1\nKommunikationsfehler\nzwischen VDIC3 und\nMikrocomputer",
    "Kurzschluss Einspritzung Bank\n2 +B",
    "Kurzschluss Einspritzung Bank\n2 GND ",
    "Kabelbruch Einspritzung Bank 2",
    "Injektor-Antrieb IC-2 VDIC3\ninterner Taktfehler",
    "Injektor-Antrieb IC-2\nKommunikationsfehler\nzwischen VDIC3 und\nMikrocomputer",
    "Kabelbruch\nAnsaugdrosselklappen-\nSteuerkreis",
    "VB/GND-Kurzschluss\nAnsaugdrosselklappen-\nSteuerkreis\n",
    "Abweichungsfehler\nAnsaugdrosselklappen-\nSteuerkreis",
    "Funktionsfehler des Antriebs\nAnsaugdrosselklappen-\nSteuerkreis",
    "Temperatursensor/\nFüllstandsensor des\nHarnstoff-Wasser-Tanks\n(AT1T1I), Temperaturanstieg in\nSteuerung",
    "Interner Kabelbruch\nTemperatursensor des\nHarnstoff-Wasser-Tanks\n(AT1T1I)",
    "Interner Kurzschluss am\nTemperatursensor des\nHarnstoff-Wasser-Tanks\n(AT1T1I)",
    "Interner Steuerungsfehler\nTemperatursensor des\nHarnstoff-Wasser-Tanks\n(AT1T1I)",
    "Temperaturanstieg\nHarnstoff-Wasser-Tank",
    "Fehler erkannter Wert am\nTemperatursensor des\nHarnstoff-Wasser-Tanks (oberer\nGrenzwertfehler)",
    "Fehler erkannter Wert am\nTemperatursensor des\nHarnstoff-Wasser-Tanks\n(unterer Grenzwertfehler)",
    "Fehler erkannter Wert\nNOx-Sensor vor SCR (oberer\nGrenzwertfehler)",
    "Fehler erkannter Wert\nNOx-Sensor vor SCR (unterer\nGrenzwertfehler)",
    "Spannungsfehler am\nTemperatursensor DPF-Einlass\n(hoch)",
    "Spannungsfehler am\nTemperatursensor DPF-Einlass\n(niedrig)",
    "Fehler erkannter Wert\nTemperatursensor DPF-Einlass",
    "Temperaturanstieg DPF-Einlass",
    "Spannungsfehler am\nDPF-Zwischentemperatursensor\n(hoch)",
    "Spannungsfehler am\nDPF-Zwischentemperatursensor\n(niedrig)",
    "Fehler erkannter Wert\nDPF-Zwischentemperatursensor",
    "Abfall der\nDPF-Zwischentemperatur",
    "Anstieg der\nDPF-Zwischentemperatur\n(Störung nach Einspritzung)",
    "Spannungsfehler am\nDPF-Differenzdrucksensor\n(hoch)",
    "Spannungsfehler am\nDPF-Differenzdrucksensor\n(niedrig)",
    "DPF-Differenzdrucksensor\nanormaler Lernwert",
    "Anstieg des\nDPF-Differenzdrucks",
    "Temperaturanstieg in\nSteuerung von Harnstoff-\nWasser-Qualitätssensor/\nTemperatursensor des\nHarnstoff-Wasser-Tanks\n(A1DEFI)",
    "Interner Kabelbruch\nTemperatursensor des\nHarnstoff-Wasser-Tanks\n(A1DEFI)",
    "Interner Kurzschluss am\nTemperatursensor des\nHarnstoff-Wasser-Tanks\n(A1DEFI)",
    "Interner Steuerungsfehler\nTemperatursensor des\nHarnstoff-Wasser-Tanks\n(A1DEFI)",
    "Interner Kabelbruch Harnstoff-\nWasser-Qualitätssensor",
    "Interner Kurzschluss am\nHarnstoff-Wasser-\nQualitätssensor",
    "Interner Steuerungsfehler\nHarnstoff-Wasser-\nQualitätssensor",
    "Konzentrationsfehler\nHarnstoff-Wasser-\nQualitätssensor (geringe\nAbweichung)",
    "Konzentrationsfehler\nHarnstoff-Wasser-\nQualitätssensor (große\nAbweichung)",
    "Verschmutzung im\nHarnstoff-Wasser-Tank",
    "Spannungsfehler des\nDrucksensors auf\nDPF-Hochdruckseite (hoch)",
    "Spannungsfehler des\nDrucksensors auf\nDPF-Hochdruckseite (niedrig)",
    "Fehler erkannter Wert am\nDrucksensor auf\nDPF-Hochdruckseite",
    "DPF stationäre\nRegenerationsbereitschaft",
    "DPF-Regenerationsfehler\n(Regenerations-\nrückgewinnungsfehler)",
    "DPF\nRegenerationsrückgewinnung\ngesperrt",
    "DPF-Sicherungsmodus",
    "DPF\nAschereinigungsanforderung 1",
    "DPF\nAschereinigungsanforderung 2",
    "Spannungsfehler am\nVersorgungsmodul-\nPumpendrucksensor (hoch)",
    "Spannungsfehler am\nVersorgungsmodul-\nPumpendrucksensor (niedrig)",
    "Fehler erkannter Wert am\nVersorgungsmodul-\nPumpensensor (oberer\nGrenzwertfehler)",
    "Fehler erkannter Wert am\nVersorgungsmodul-\nPumpensensor (unterer\nGrenzwertfehler)",
    "Harnstoff-Wasser-\nSchlauchheizung (Druck)\nVB-Kurzschluss L-Seite",
    "Harnstoff-Wasser-\nSchlauchheizung (Druck)\nGND-Kurzschluss L-Seite",
    "Kabelbruch an\nHarnstoff-Wasser-\nSchlauchheizung (Druck)",
    "Harnstoff-Wasser-\nSchlauchheizung (Rückfluss)\nVB-Kurzschluss L-Seite",
    "Harnstoff-Wasser-\nSchlauchheizung (Rückfluss)\nGND-Kurzschluss L-Seite",
    "Kabelbruch an Harnstoff-\nWasser-Schlauchheizung\n(Rückfluss)",
    "Harnstoff-Wasser-\nSchlauchheizung (Ansaugung)\nVB-Kurzschluss L-Seite",
    "Harnstoff-Wasser-\nSchlauchheizung (Ansaugung)\nGND-Kurzschluss L-Seite",
    "Kabelbruch an Harnstoff-\nWasser-Schlauchheizung\n(Ansaugung)",
    "Spannungsfehler am\nTemperatursensor vor\nSCR-Katalysator (hoch)",
    "Spannungsfehler am\nTemperatursensor vor\nSCR-Katalysator (niedrig)",
    "Temperaturanstieg vor\nSCR-Katalysator",
    "Fehler erkannter Wert\nTemperatursensor vor\nSCR-Katalysator (oberer\nGrenzwertfehler)",
    "Fehler erkannter Wert\nTemperatursensor vor\nSCR-Katalysator (unterer\nGrenzwertfehler)",
    "Fehler erkannter Wert\nTemperatursensor vor\nSCR-Katalysator bei\nKaltstartüberprüfung",
    "VB-Kurzschluss\nVersorgungsmodul\n(Pumpenmotor)\nPWM-Signalverkabelung",
    "GND-Kurzschluss\nVersorgungsmodul\n(Pumpenmotor)\nPWM-Signalverkabelung",
    "Kabelbruch Versorgungsmodul\n(Pumpenmotor)\nPWM-Signalverkabelung",
    "Antriebsfehler 1\nVersorgungsmodul\n(Pumpenmotor)",
    "Antriebsfehler 2\nVersorgungsmodul\n(Pumpenmotor)",
    "Gültigkeitsfehler\nDPF-Grundmaterialaustrag/DPF-Differenzdrucksensor",
    "Tankheizungsventil\nGND-Kurzschluss L-Seite",
    "Kabelbruch Tankheizungsventil",
    "ECU-Kommunikationsfehler\nzwischen Mikrocomputern\n(MSC-Kommunikationsfehler)",
    "ECU-Kommunikationsfehler\nzwischen Mikrocomputern\n(SPI-Kommunikationsfehler\nbasierend auf der\nFehlerdiagnose des\nAtmosphärendrucksensors)",
    "ECU-Kommunikationsfehler\nzwischen Mikrocomputern\n(SPI-Kommunikationsfehler\nbasierend auf der\nFehlerdiagnose des\nüberwachenden\nMikrocomputers)",
    "Fehler im A/D-Wandler des\nECU-Mikrocomputers",
    "Anormaler\nEinspritzungs-Stopp-Pfad am\nECU-Mikrocomputer-Fehler",
    "Kurzschluss an Vorglühlampe\n+B",
    "Kurzschluss an Störungsleuchte\n+B",
    "Kurzschluss an Anlasserrelais\n+B",
    "Kurzschluss Leuchte für\nhydraulischen Abfall +B",
    "Kurzschluss an gelber\nWarnleuchte +B",
    "Kurzschluss an Anzeigeleuchte\nder Drehzahländerung +B",
    "Kurzschluss an Warnleuchte\nder Abgastemperatur +B",
    "Kurzschluss an Warnleuchte\nder Motorkühlmitteltemperatur\n+B",
    "Kurzschluss Hupe +B",
    "Kurzschluss an roter\nMotorstoppleuchte +B",
    "Kurzschluss Isochrone Leuchte\n+B",
    "Kurzschluss an Kontrollleuchte\nder DPF-Regeneration +B",
    "Kurzschluss an DPF-\nRegenerationsverbotsleuchte\n+B",
    "Kurzschluss\nDPF-Regenerations-\nanforderungsleuchte +B",
    "EGR Systemfehler (Auslöser 1)",
    "EGR Systemfehler (Auslöser 2)",
    "ECU-System\nFS-Aktionsanweisung 2",
    "Fehler erkannter Wert\nNOx-Sensor vor SCR\n(O2-Konzentration)",
    "Kabelbruch des\nStarthilfe-Relais/VB-Kurzschluss",
    "GND-Kurzschluss\nStarthilferelais",
    "Verstopfung des Luftfilters",
    "Fehler Öl- und\nWasserabscheider",
    "Fehler Kurbelwellensignal",
    "Kein Signal von der Kurbelwelle",
    "Fehler Nockenwellensignal",
    "Kein Signal von der\nNockenwelle",
    "DPF übermäßige\nPM-Akkumulation (Methode C)",
    "DPF übermäßige\nPM-Akkumulation (Methode P)",
    "DPF-Regenerationsfehler\n(Ausfall der stationären\nRegeneration)",
    "DPF-Regenerationsfehler\n(Stationären Regeneration nicht\nin Betrieb)",
    "Kurzschluss an EGR-Motorspule",
    "Fehler EGR-Positionssensors",
    "EGR-Ventil klemmt",
    "EGR-Initialisierungsfehler",
    "Fehler EGR-\nHochtemperatur-Thermistor",
    "Fehler EGR-\nNiedrigtemperatur-Thermistor",
    "Zeitüberschreitung\nCAN-Empfang (TSC1 (SA1))",
    "Zeitüberschreitung\nCAN-Empfang (TSC1 (SA2))",
    "Zeitüberschreitung beim\nCAN-Empfang (Y_ECR1)",
    "Zeitüberschreitung beim\nCAN-Empfang (Y_EC)",
    "Zeitüberschreitung beim\nCAN-Empfang (Y_RSS)",
    "Zeitüberschreitung\nCAN-Empfang von EGR-Ventil",
    "EGR-Zielwert außerhalb des\nBereichs",
    "Zeitüberschreitung beim\nCAN-Empfang (EBC1)",
    "Zeitüberschreitung beim\nCAN-Empfang (Y_DRFIF)",
    "Fehler offene Stellung des\ndoppelten\nBeschleunigungssensors",
    "Fehler geschlossene Stellung\ndes doppelten\nBeschleunigungssensors",
    "Lernen der Hochdruckpumpe\nnicht durchgeführt",
    "ECU CPU Überwachungs-IC\nFehler",
    "ECU CPU-Fehler",
    "Eingabefehler\nQR-Datenkorrektur",
    "Ladungsfehler im\nInjektor-Steuerkreis (niedrige\nLadung)",
    "Ladungsfehler im\nInjektor-Steuerkreis\n(Überladung)",
    "Prüfsummenfehler\nECU-Flash-ROM",
    "Spannungsfehler ECU-Sensor 5\nV Schaltkreis 1 (niedrig)",
    "Spannungsfehler ECU-Sensor 5\nV Schaltkreis 1 (hoch)",
    "Spannungsfehler ECU-Sensor 5\nV Schaltkreis 2 (niedrig)",
    "Spannungsfehler ECU-Sensor 5\nV Schaltkreis 2 (hoch)",
    "QR-Daten nicht geschrieben",
    "QR-Datenfehler",
    "Keine Eingabe Kurbelwellen-\n/Nockenwellendrehzahlsensor\n(gleichzeitig)",
    "Zeitüberschreitung\nCAN-Empfang von DCU",
    "VB-Kurzschluss\nVersorgungsmodul\n(Rücklaufventil) H-Seite",
    "GND-Kurzschluss\nVersorgungsmodul\n(Rücklaufventil) H-Seite",
    "VB-Kurzschluss\nSchlauchheizungsrelais/Tank-\nheizungsventil H-Seite",
    "GND-Kurzschluss\nSchlauchheizungsrelais/Tank-\nheizungsventil H-Seite",
    "VB-Kurzschluss\nVersorgungsmodul\n(Versorgungsmodulheizung)\nH-Seite ",
    "GND-Kurzschluss\nVersorgungsmodul\n(Versorgungsmodulheizung)\nH-Seite ",
    "Kabelbruch Versorgungsmodul\n(Versorgungsmodulheizung)",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Versorgungsmodulheizung)",
    "Zwangsabschaltung des\nSCR-Systems",
    "Spannungsfehler\nDCU-Versorgung (hoch 1)",
    "Spannungsfehler\nDCU-Versorgung (niedrig 2)",
    "Spannungsfehler\nDCU-Versorgung (hoch 2)",
    "Spannungsfehler\nDCU-Versorgung (niedrig 1)",
    "Hauptrelais klemmt",
    "Vorzeitiges Öffnen des\nHauptrelais",
    "Zeitüberschreitung\nCAN-Empfang von NOx-Sensor\nvor SCR",
    "Zeitüberschreitung\nCAN-Empfang von NOx-Sensor\nhinter SCR",
    "Zeitüberschreitung\nCAN-Empfang von ECU ",
    "Spannungsfehler\nDCU-Sensorversorgung",
    "DCU SPI-Kommunikationsfehler\n1",
    "DCU SPI-Kommunikationsfehler\n2",
    "Kurzschluss im Dosiermodul\nauf H/L-Seite",
    "Kabelbruch Dosiermodul",
    "VB-Kurzschluss Dosiermodul\nauf der H-Seite",
    "GND-Kurzschluss Dosiermodul",
    "Dosiermodulventil klemmt",
    "EEPROM-Speicher-Lesefehler",
    "EEPROM-Speicher-Schreibfehler",
    "VB-Kurzschluss\nSchlauchheizungsrelais L-Seite",
    "GND-Kurzschluss\nSchlauchheizungsrelais L-Seite",
    "Kabelbruch\nSchlauchheizungsrelais",
    "VB-Kurzschluss\nVersorgungsmodul\n(Versorgungsmodulheizung)\nL-Seite ",
    "VB-Kurzschluss\nTankheizungsventil L-Seite",
    "NOx-Wert-Anstieg vor SCR",
    "Interner Kurzschluss\nNOx-Sensor vor SCR",
    "Interner Kabelbruch\nNOx-Sensor vor SCR",
    "NOx-Wert-Anstieg hinter SCR",
    "Interner Kurzschluss\nNOx-Sensor hinter SCR",
    "Interner Kabelbruch\nNOx-Sensor hinter SCR",
    "Nicht abgeschlossene\nAufheizung NOx-Sensor vor\nSCR",
    "Nicht abgeschlossene\nAufheizung NOx-Sensor hinter\nSCR",
    "VB-Kurzschluss\nVersorgungsmodul\n(Rücklaufventil) L-Seite",
    "GND-Kurzschluss\nVersorgungsmodul\n(Rücklaufventil) L-Seite",
    "Kabelbruch Versorgungsmodul\n(Rücklaufventil)",
    "SCR-System ineffiziente\nNOx-Reinigung",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Temperatursensor\nVersorgungsmodulheizung)",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Temperatursensor\nVersorgungsmodulheizung) bei\nKaltstartüberprüfung",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Temperatursensor\nVersorgungsmodulheizung)",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Temperatursensor\nVersorgungsmodulheizung) bei\nKaltstartüberprüfung",
    "Falscher Wert empfangen für\nTemperaturangabe während\ndes Betriebs des\nVersorgungsmoduls\n(Temperatursensor\nVersorgungsmodulheizung)",
    "Ungültiger Wert empfangen für\nTemperaturangabe während\ndes Betriebs des\nVersorgungsmoduls\n(Temperatursensor\nVersorgungsmodulheizung)",
    "PWM-Zyklusfehler\nVersorgungsmodul\n(Pumpenmotor)\nTemperaturangabe",
    "PWM-Signalfehler\nVersorgungsmodul\n(Pumpenmotor)\nTemperaturangabe",
    "Falscher Wert empfangen für\nTemperaturangabe während\ndes Betriebs des\nVersorgungsmoduls\n(Temperatursensor\nVersorgungsmodul)",
    "Ungültiger Wert empfangen für\nTemperaturangabe während\ndes Betriebs des\nVersorgungsmoduls\n(Temperatursensor\nVersorgungsmodul)",
    "Versorgungsmodul\n(Pumpenmotor) startet nicht\nzur Temperaturmessung",
    "Druckanstieg 1\nVersorgungsmodul\n(Pumpenmotor)",
    "Druckminderungsfehler\nVersorgungsmodul\n(Pumpenmotor)",
    "Druckanstieg auf der\nRücklaufseite des\nHarnstoff-Wasser-Schlauchs",
    "Druckanstieg auf der\nDruckseite des\nHarnstoff-Wasser-Schlauchs",
    "Druckstabilitätsfehler\nVersorgungsmodul\n(Pumpenmotor)",
    "Ausfall Versorgungsmodul\n(Rücklaufventil)",
    "Harnstoff-Wasser-\nRücksaugfehler am\nVersorgungsmodul",
    "Druckanstieg 2\nVersorgungsmodul\n(Pumpenmotor)",
    "Druckabfall am\nVersorgungsmodul",
    "Harnstoff-Wasser-Druckanstieg\nam Versorgungsmodul",
    "Temperaturanstieg\nHarnstoff-Wasser-Tank",
    "Zeitüberschreitung beim\nCAN-Empfang (A1DEFI)",
    "Zeitüberschreitung beim\nCAN-Empfang (AT1T1I)",
    "SCR Systemfehler (Auslöser 1)",
    "SCR Systemfehler (Auslöser 2)",
    "ECU-System\nFS-Aktionsanweisung 1",
    "Schlüsselschalter-Kabelbruch",
    "Datenüberprüfungsfehler\nzwischen ECU und DCU\n(Zeitüberschreitung der\nVerifizierung)"
	};
