
static const char *H_EngErrorMSG_ESP[308]={	
    "Error de tensión del sensor 2\ndel acelerador (alta)",
    "Error de tensión del sensor 2\ndel acelerador (baja)",
    "Error de posición abierta del\nsensor del pedal",
    "Error de posición cerrada del\nsensor del pedal",
    "Error de tensión del sensor 3\ndel acelerador (alta)",
    "Error de tensión del sensor 3\ndel acelerador (baja)",
    "Error de tensión del sensor de\nposición del regulador de\nadmisión (alta)",
    "Error de tensión del sensor de\nposición del regulador de\nadmisión (baja)",
    "Error de tensión del sensor 1\ndel acelerador (alta)",
    "Error de tensión del sensor 1\ndel acelerador (baja)",
    "Error de tensión del sensor de\npresión de aceite (alta)",
    "Error de tensión del sensor de\npresión de aceite (baja)",
    "Caída de la presión del aceite",
    "Error de tensión del sensor de\npresión del lado de baja\npresión de la EGR (alta)",
    "Error de tensión del sensor de\npresión del lado de baja\npresión de la EGR (baja)",
    "Valor de aprendizaje anómalo\ndel sensor de presión del lado\nde baja presión de la EGR",
    "Error de valor detectado del\nsensor de presión del lado de\nbaja presión de la EGR",
    "Error de tensión del sensor de\ntemperatura del colector de\nadmisión (alta)",
    "Error de tensión del sensor de\ntemperatura del colector de\nadmisión (baja)",
    "Error de valor detectado del\nsensor de temperatura del\ncolector de admisión",
    "Error de tensión del sensor de\npresión atmosférica (alta)",
    "Error de tensión del sensor de\npresión atmosférica (baja)",
    "Error característico del sensor\nde presión atmosférica",
    "Error de tensión del sensor de\ntemperatura del refrigerante\ndel motor (alta)",
    "Error de tensión del sensor de\ntemperatura del refrigerante\ndel motor (baja)",
    "Aumento de la temperatura del\nrefrigerante del motor\n(sobrecalentamiento)",
    "Error de valor detectado del\nsensor de temperatura del\nrefrigerante del motor",
    "Error de tensión del sensor de\npresión del raíl (alta)",
    "Error de tensión del sensor de\npresión del raíl (baja)",
    "Aumento excesivo de la\npresión del raíl",
    "Error de desviación de la\npresión del raíl (baja presión\ndel raíl)",
    "Rotura del cableado del\ninterruptor de carga",
    "Error de carga",
    "Error de tensión del sensor de\ntemperatura del aire ambiente\n(alta)",
    "Error de tensión del sensor de\ntemperatura del aire ambiente\n(baja)",
    "Error de valor detectado del\nsensor de temperatura del aire\nambiente",
    "Recepción no válida del valor\nde la temperatura ambiente en\nla ECU",
    "Error de tensión del sensor de\ntemperatura del colector de\nescape (alta)",
    "Error de tensión del sensor de\ntemperatura del colector de\nescape (baja)",
    "Error de valor detectado del\nsensor de temperatura del\ncolector de escape",
    "Error de tensión del sensor de\ntemperatura de combustible\n(alta)",
    "Error de tensión del sensor de\ntemperatura de combustible\n(baja)",
    "Aumento de la temperatura del\ncombustible",
    "Velocidad excesiva",
    "Se excedió el tiempo de espera\nde recepción de CAN (VI)",
    "Error de datos recibidos de\nCAN (VI)",
    "Error de tensión del sensor de\ntemperatura del gas de la EGR\n(alta)",
    "Error de tensión del sensor de\ntemperatura del gas de la EGR\n(baja)",
    "Error de valor detectado del\nsensor de temperatura del gas\nde la EGR",
    "Error de verificación de datos\nentre la ECU y la DCU\n(discrepancia del modelo del\nmotor)",
    "Error de verificación de datos\nentre la ECU y la DCU\n(discrepancia del n.º de serie)",
    "Error de EEPROM",
    "Cortocircuito VB del lado H/L\nde la válvula de control de\naspiración (válvula proporcional\nmagnética)",
    "Cortocircuito/rotura del\ncableado de GND del lado H\nde la válvula de control de\naspiración (válvula proporcional\nmagnética)",
    "Error del circuito de\naccionamiento (la válvula de\ncontrol de aspiración se atasca)",
    "Rotura de cableado específica\ndel inyector del cilindro n.º 1",
    "Cortocircuito en la bobina del\ninyector del cilindro n.º 1 entre\nlos terminales COM y TWV",
    "Circuito abierto de MOS de\ndescarga del inyector del\ncilindro n.º 1",
    "Rotura de cableado específica\ndel inyector del cilindro n.º 2",
    "Cortocircuito en la bobina del\ninyector del cilindro n.º 2 entre\nlos terminales COM y TWV",
    "Circuito abierto de MOS de\ndescarga del inyector del\ncilindro n.º 2",
    "Rotura de cableado específica\ndel inyector del cilindro n.º 3",
    "Cortocircuito en la bobina del\ninyector del cilindro n.º 3 entre\nlos terminales COM y TWV",
    "Circuito abierto de MOS de\ndescarga del inyector del\ncilindro n.º 3",
    "Rotura de cableado específica\ndel inyector del cilindro n.º 4",
    "Cortocircuito en la bobina del\ninyector del cilindro n.º 4 entre\nlos terminales COM y TWV",
    "Circuito abierto de MOS de\ndescarga del inyector del\ncilindro n.º 4",
    "Error de tensión del sensor de\npresión del lado de alta\npresión de la EGR (alta)",
    "Error de tensión del sensor de\npresión del lado de alta\npresión de la EGR (baja)",
    "Valor de aprendizaje anómalo\ndel sensor de presión del lado\nde alta presión de la EGR",
    "Error de valor detectado del\nsensor de presión del lado de\nalta presión de la EGR",
    "Error de protección de la\nbomba de alta presión",
    "Error de sustitución de la\nbomba de alta presión",
    "Apagado sin autorretención del\nrelé principal",
    "Bajo nivel del depósito de urea\nacuosa (inducción 1)",
    "Bajo nivel del depósito de urea\nacuosa (inducción 2)",
    "Rotura del cableado del sensor\nde nivel del depósito de urea\nacuosa",
    "Cortocircuito del sensor de\nnivel del depósito de urea\nacuosa (AT1T1I)",
    "Error interno del controlador\ndel sensor de nivel del\ndepósito de urea acuosa\n(AT1T1I)",
    "Error de valor detectado del\nsensor de nivel del depósito de\nurea acuosa",
    "Rotura del cableado de la\nbobina del motor de la EGR",
    "Error de retroalimentación de\nla EGR",
    "Error de datos del ECM de la\nEGR",
    "Error de tensión de la EGR\n(sobretensión)",
    "Error de tensión de la EGR\n(baja)",
    "Cortocircuito del banco de\ninyectores 1 +B",
    "Cortocircuito de GND del\nbanco de inyectores 1 ",
    "Rotura del cableado del banco\nde inyectores 1",
    "Error de reloj interno del\ncontrolador del inyector IC-1\nVDIC3",
    "Error de comunicación del\ncontrolador del inyector IC-1\nentre el VDIC3 y el\nmicroordenador",
    "Cortocircuito del banco de\ninyectores 2 +B",
    "Cortocircuito de GND del\nbanco de inyectores 2 ",
    "Rotura del cableado del banco\nde inyectores 2",
    "Error de reloj interno del\ncontrolador del inyector IC-2\nVDIC3",
    "Error de comunicación del\ncontrolador del inyector IC-2\nentre el VDIC3 y el\nmicroordenador",
    "Rotura del cableado del\ncircuito de accionamiento del\nregulador de admisión",
    "Cortocircuito de VB/GND del\ncircuito de accionamiento del\nregulador de admisión ",
    "Error de desviación del circuito\nde accionamiento del\nregulador de admisión",
    "Error de funcionamiento del\ncircuito de accionamiento del\nregulador de admisión",
    "Aumento de temperatura del\ncontrolador del sensor de\ntemperatura del depósito de\nurea acuosa/Sensor de nivel\ndel depósito de urea acuosa\n(AT1T1I)",
    "Rotura del cableado del\ncircuito interno del sensor de\ntemperatura del depósito de\nurea acuosa (AT1T1I)",
    "Cortocircuito del circuito\ninterno del sensor de\ntemperatura del depósito de\nurea acuosa (AT1T1I)",
    "Fallo interno del controlador\ndel sensor de temperatura del\ndepósito de urea acuosa\n(AT1T1I)",
    "Aumento de la temperatura del\ndepósito de urea acuosa",
    "Error de valor detectado del\nsensor de temperatura del\ndepósito de urea acuosa (error\nde límite superior)",
    "Error de valor detectado del\nsensor de temperatura del\ndepósito de urea acuosa (error\nde límite inferior)",
    "Error de valor detectado del\nsensor de NOx aguas arriba del\nSCR (error de límite superior)",
    "Error de valor detectado del\nsensor de NOx aguas arriba del\nSCR (error de límite inferior)",
    "Error de tensión del sensor de\ntemperatura de entrada del\nDPF (alta)",
    "Error de tensión del sensor de\ntemperatura de entrada del\nDPF (baja)",
    "Error de valor detectado del\nsensor de temperatura de\nentrada del DPF",
    "Aumento de la temperatura de\nentrada del DPF",
    "Error de tensión del sensor de\ntemperatura intermedia del\nDPF (alta)",
    "Error de tensión del sensor de\ntemperatura intermedia del\nDPF (baja)",
    "Error de valor detectado del\nsensor de temperatura\nintermedia del DPF",
    "Caída de la temperatura\nintermedia del DPF",
    "Aumento de la temperatura\nintermedia del DPF (fallo\nposterior a la inyección)",
    "Error de tensión del sensor de\npresión diferencial del DPF\n(alta)",
    "Error de tensión del sensor de\npresión diferencial del DPF\n(baja)",
    "Valor de aprendizaje anómalo\ndel sensor de presión\ndiferencial del DPF",
    "Aumento de la presión\ndiferencial del DPF",
    "Aumento de la temperatura del\ncontrolador del sensor de\ncalidad de la urea\nacuosa/sensor de temperatura\ndel depósito de urea acuosa\n(A1DEFI)",
    "Rotura del cableado del\ncircuito interno del sensor de\ntemperatura del depósito de\nurea acuosa (A1DEFI)",
    "Cortocircuito del circuito\ninterno del sensor de\ntemperatura del depósito de\nurea acuosa (A1DEFI)",
    "Fallo interno del controlador\ndel sensor de temperatura del\ndepósito de urea acuosa\n(A1DEFI)",
    "Rotura del cableado del\ncircuito interno del sensor de\ncalidad de urea acuosa",
    "Cortocircuito en el circuito\ninterno del sensor de calidad\nde urea acuosa",
    "Fallo interno del controlador\ndel sensor de calidad de urea\nacuosa",
    "Error de concentración del\nsensor de calidad de urea\nacuosa (desviación pequeña)",
    "Error de concentración del\nsensor de calidad de urea\nacuosa (desviación grande)",
    "Contaminación del depósito de\nurea acuosa",
    "Error de tensión del sensor de\npresión del lado de alta\npresión de la DPF (alta)",
    "Error de tensión del sensor de\npresión del lado de alta\npresión de la DPF (baja)",
    "Error de valor detectado del\nsensor de presión del lado de\nalta presión de la DPF",
    "Regeneración estacionaria del\nDPF en espera",
    "Fallo de regeneración del DPF\n(fallo de regeneración de\nrecuperación)",
    "Regeneración de recuperación\ndel DPF inhibida",
    "Modo de copia de seguridad\ndel DPF",
    "Solicitud de limpieza de\ncenizas del DPF 1",
    "Solicitud de limpieza de\ncenizas del DPF 2",
    "Error de tensión del sensor de\npresión de la bomba del\nmódulo de alimentación (alta)",
    "Error de tensión del sensor de\npresión de la bomba del\nmódulo de alimentación (baja)",
    "Error de valor detectado del\nsensor de presión de la bomba\ndel módulo de alimentación\n(error de límite superior)",
    "Error de valor detectado del\nsensor de presión de la bomba\ndel módulo de alimentación\n(error de límite inferior)",
    "Cortocircuito de VB del lado\nIzq. del calentador de\nmanguera de urea acuosa\n(presión)",
    "Cortocircuito de GND del lado\nIzq. del calentador de\nmanguera de urea acuosa\n(presión)",
    "Rotura de cableado del\ncalentador de manguera de\nurea acuosa (presión)",
    "Cortocircuito de VB del lado\nIzq. del calentador de\nmanguera de urea acuosa\n(reflujo)",
    "Cortocircuito de GND del lado\nIzq. del calentador de\nmanguera de urea acuosa\n(reflujo)",
    "Rotura de cableado del\ncalentador de manguera de\nurea acuosa (reflujo)",
    "Cortocircuito de VB del lado\nIzq. del calentador de\nmanguera de urea acuosa\n(aspiración)",
    "Cortocircuito de GND del lado\nIzq. del calentador de\nmanguera de urea acuosa\n(aspiración)",
    "Rotura de cableado del\ncalentador de manguera de\nurea acuosa (aspiración)",
    "Error de tensión del sensor de\ntemperatura aguas arriba del\ncatalizador SCR (alta)",
    "Error de tensión del sensor de\ntemperatura aguas arriba del\ncatalizador SCR (baja)",
    "Aumento de la temperatura\naguas arriba del catalizador\nSCR",
    "Error de valor detectado del\nsensor de temperatura aguas\narriba del catalizador SCR\n(error de límite superior)",
    "Error de valor detectado del\nsensor de temperatura aguas\narriba del catalizador SCR\n(error de límite inferior)",
    "El sensor de temperatura\nascendente del catalizador SCR\ndetectó un error de valor en la\ncomprobación de arranque en\nfrío",
    "Cortocircuito de VB del\ncableado de señal de PWM del\nmódulo de alimentación\n(motor de la bomba)",
    "Cortocircuito de GND del\ncableado de señal de PWM del\nmódulo de alimentación\n(motor de la bomba)",
    "Rotura del cableado de señal\nde PWM del módulo de\nalimentación (motor de la\nbomba)",
    "Error de accionamiento del\nmódulo de alimentación\n(motor de la bomba) 1",
    "Error de accionamiento del\nmódulo de alimentación\n(motor de la bomba) 2",
    "Eliminación del material base\ndel DPF/Error de validez del\nsensor de presión diferencial\ndel DPF",
    "Cortocircuito de GND del lado\nIzq. de la válvula de calefacción\ndel depósito",
    "Rotura del cableado de la\nválvula de calefacción del\ndepósito",
    "Error de comunicación de la\nECU entre microordenadores\n(error de comunicación de\nMSC)",
    "Error de comunicación de la\nECU entre microordenadores\n(error de comunicación de SPI\nbasado en el diagnóstico de\nerror del sensor de presión\natmosférica)",
    "Error de comunicación de la\nECU entre microordenadores\n(error de comunicación de SPI\nbasado en el diagnóstico de\nerrores del microordenador de\nvigilancia)",
    "Error del convertidor A/D del\nmicroordenador de la ECU",
    "Error de ruta de parada de\ninyección anómala en el\nmicroordenador de la ECU",
    "Cortocircuito de lámpara de\nprecalentamiento +B",
    "Cortocircuito de lámpara de\navería +B",
    "Cortocircuito del relé de\narranque +B",
    "Cortocircuito de lámpara de\ncaída hidráulica +B",
    "Cortocircuito de luz de\nadvertencia ámbar +B",
    "Cortocircuito de indicador\nluminoso de cambio de\nvelocidad +B",
    "Cortocircuito de lámpara de\nalarma de temperatura de\nescape +B",
    "Cortocircuito de lámpara de\nalarma de temperatura del\nrefrigerante del motor +B",
    "Cortocircuito del zumbador +B",
    "Cortocircuito de luz roja de\nparada del motor +B",
    "Cortocircuito de la lámpara\nisócrona +B",
    "Cortocircuito de la lámpara de\naprobación de regeneración\ndel DPF +B",
    "Cortocircuito de la lámpara de\nprohibición de regeneración\ndel DPF +B",
    "Cortocircuito de la lámpara de\nsolicitud de regeneración del\nDPF +B",
    "Error en el sistema de EGR\n(inducción 1)",
    "Error en el sistema de EGR\n(inducción 2)",
    "Instrucción de acción FS 2 del\nsistema de la ECU",
    "Error de valor detectado del\nsensor de NOx aguas arriba del\nSCR (concentración de O2)",
    "Rotura del cableado del relé de\nayuda al arranque/Cortocircuito\nde VB",
    "Cortocircuito de GND del relé\nde ayuda al arranque",
    "Obstrucción del filtro de aire",
    "Error en el separador de aceite\ny agua",
    "Error de señal del cigüeñal",
    "Sin señal del cigüeñal",
    "Error de señal del árbol de\nlevas",
    "Sin señal del árbol de levas",
    "Acumulación excesiva de PM\nen el DPF (método C)",
    "Acumulación excesiva de PM\nen el DPF (método P)",
    "Error de regeneración del DPF\n(fallo de regeneración\nestacionaria)",
    "Error de regeneración del DPF\n(regeneración estacionaria no\noperada)",
    "Cortocircuito en la bobina del\nmotor de la EGR",
    "Error del sensor de posición de\nla EGR",
    "La válvula de la EGR se atasca",
    "Error de inicialización de la\nEGR",
    "Error del termistor de alta\ntemperatura de la EGR",
    "Error del termistor de baja\ntemperatura de la EGR",
    "Se excedió el tiempo de espera\nde recepción de CAN (TSC1\n(SA1))",
    "Se excedió el tiempo de espera\nde recepción de CAN (TSC1\n(SA2))",
    "Se excedió el tiempo de espera\nde recepción de CAN (Y_ECR1)",
    "Se excedió el tiempo de espera\nde recepción de CAN (Y_EC)",
    "Se excedió el tiempo de espera\nde recepción de CAN (Y_RSS)",
    "Se excedió el tiempo de espera\nde recepción CAN de la válvula\nEGR",
    "Valor objetivo de la EGR fuera\nde rango",
    "Se excedió el tiempo de espera\nde recepción de CAN (EBC1)",
    "Se excedió el tiempo de espera\nde recepción de CAN (Y_DRFIF)",
    "Error de posición abierta del\nsensor del acelerador dual",
    "Error de posición cerrada del\nsensor del acelerador dual",
    "No se ha realizado el\naprendizaje de la bomba de\nalta presión",
    "Error del CI de monitorización\nde la CPU de la ECU",
    "Error de la CPU de la ECU",
    "Error de entrada de corrección\nde datos QR",
    "Error de carga del circuito de\naccionamiento del inyector\n(carga baja)",
    "Error de carga del circuito de\naccionamiento del inyector\n(sobrecarga)",
    "Error de suma de\ncomprobación de la ROM flash\nde la ECU",
    "Error de tensión del circuito 1\nde 5 V del sensor de la ECU\n(baja)",
    "Error de tensión del circuito 1\nde 5 V del sensor de la ECU\n(alta)",
    "Error de tensión del circuito 2\nde 5 V del sensor de la ECU\n(baja)",
    "Error de tensión del circuito 2\nde 5 V del sensor de la ECU\n(alta)",
    "Datos de QR no escritos",
    "Error de datos de QR",
    "Sin entrada de sensor de\nvelocidad del cigüeñal/sensor\nde velocidad del árbol de levas\n(simultánea)",
    "Se excedió el tiempo de espera\nde recepción CAN de la DCU",
    "Cortocircuito de VB del lado H\ndel módulo de alimentación\n(válvula de inversión)",
    "Cortocircuito de GND del lado\nH del módulo de alimentación\n(válvula de inversión)",
    "Cortocircuito de VB del lado H\nde relé del calentador de la\nmanguera/Válvula de\ncalefacción del depósito",
    "Cortocircuito de GND del lado\nH de relé del calentador de la\nmanguera/Válvula de\ncalefacción del depósito",
    "Cortocircuito de VB del lado H\ndel módulo de alimentación\n(calentador del módulo de\nalimentación) ",
    "Cortocircuito de GND del lado\nH del módulo de alimentación\n(calentador del módulo de\nalimentación) ",
    "Rotura del cableado del\nmódulo de alimentación\n(calentador del módulo de\nalimentación)",
    "Error de valor detectado del\nmódulo de alimentación\n(calentador del módulo de\nalimentación)",
    "Finalización forzada del sistema\nSCR",
    "Error de tensión de\nalimentación de la DCU (alta 1)",
    "Error de tensión de\nalimentación de la DCU\n(baja 2)",
    "Error de tensión de\nalimentación de la DCU (alta 2)",
    "Error de tensión de\nalimentación de la DCU\n(baja 1)",
    "El relé principal se atasca",
    "Apertura anticipada del relé\nprincipal",
    "Tiempo de espera de recepción\nCAN del sensor de NOx aguas\narriba de SCR",
    "Tiempo de espera de recepción\nCAN del sensor de NOx aguas\nabajo de SCR",
    "Se excedió el tiempo de espera\nde recepción CAN de la ECU ",
    "Error de tensión de\nalimentación del sensor de la\nDCU",
    "Error de comunicación de SPI\nde la DCU 1",
    "Error de comunicación de SPI\nde la DCU 2",
    "Cortocircuito del lado H/L del\nmódulo de dosificación",
    "Rotura del cableado del\nmódulo de dosificación",
    "Cortocircuito de VB del lado H\ndel módulo de dosificación",
    "Cortocircuito de GND del\nmódulo de dosificación",
    "Válvula del módulo de\ndosificación atascada",
    "Error de lectura de la memoria\nEEPROM",
    "Error de escritura de la\nmemoria EEPROM",
    "Cortocircuito de VB del lado\nIzq. del relé del calentador de\nmanguera",
    "Cortocircuito de GND del lado\nIzq. del relé del calentador de\nmanguera",
    "Rotura del cableado del relé\ndel calentador de la manguera",
    "Cortocircuito de VB del lado\nIzq. del módulo de\nalimentación (calentador del\nmódulo de alimentación) ",
    "Cortocircuito de VB del lado\nIzq. de la válvula de calefacción\ndel depósito",
    "Aumento del valor de NOx\naguas arriba del SCR",
    "Cortocircuito del circuito\ninterno del sensor de NOx\naguas arriba del SCR",
    "Rotura del cableado del\ncircuito interno del sensor de\nNOx aguas arriba del SCR",
    "Aumento del valor de NOx\naguas abajo del SCR",
    "Cortocircuito del circuito\ninterno del sensor de NOx\naguas abajo del SCR",
    "Rotura del cableado del\ncircuito interno del sensor de\nNOx aguas abajo del SCR",
    "Calentamiento incompleto del\nsensor de NOx aguas arriba del\nSCR",
    "Calentamiento incompleto del\nsensor de NOx aguas abajo del\nSCR",
    "Cortocircuito de VB del lado\nIzq. del módulo de\nalimentación (válvula de\ninversión)",
    "Cortocircuito de GND del lado\nIzq. del módulo de\nalimentación (válvula de\ninversión)",
    "Rotura de cableado del\nmódulo de alimentación\n(válvula de inversión)",
    "Sistema SCR de limpieza de\nNOx ineficiente",
    "Error de valor detectado del\nmódulo de alimentación\n(sensor de temperatura del\ncalentador del módulo de\nalimentación)",
    "Error de valor detectado del\nmódulo de alimentación\n(sensor de temperatura del\ncalentador del módulo de\nalimentación) en la\ncomprobación de arranque en\nfrío",
    "Error de valor detectado del\nmódulo de alimentación\n(sensor de temperatura del\nmódulo de alimentación)",
    "Error de valor detectado del\nmódulo de alimentación\n(sensor de temperatura del\nmódulo de alimentación) en la\ncomprobación de arranque en\nfrío",
    "Valor defectuoso recibido del\nmódulo de alimentación\n(sensor de temperatura del\ncalentador del módulo de\nalimentación) para la\ninformación de temperatura\nvalor de servicio",
    "Valor no válido recibido del\nmódulo de alimentación\n(sensor de temperatura del\ncalentador del módulo de\nalimentación) para la\ninformación de temperatura\nvalor de servicio",
    "Error de ciclo PWM de\ninformación sobre la\ntemperatura del módulo de\nalimentación (motor de la\nbomba)",
    "Error de señal PWM de\ninformación sobre la\ntemperatura del módulo de\nalimentación (motor de la\nbomba)",
    "Valor defectuoso recibido del\nmódulo de alimentación\n(sensor de temperatura del\nmódulo de alimentación) para\nla información de temperatura\nvalor de servicio",
    "Valor no válido recibido del\nmódulo de alimentación\n(sensor de temperatura del\nmódulo de alimentación) para\nla información de temperatura\nvalor de servicio",
    "El módulo de alimentación\n(motor de la bomba) no\narranca para medir la\ntemperatura",
    "Aumento de presión del\nmódulo de alimentación\n(motor de la bomba) 1",
    "Error de reducción de presión\ndel módulo de alimentación\n(motor de la bomba)",
    "Aumento de la presión del\nlado de reflujo de la manguera\nde urea acuosa",
    "Aumento de la presión del\nlado de presión de la\nmanguera de urea acuosa",
    "Error de estabilidad de presión\ndel módulo de alimentación\n(motor de la bomba)",
    "Fallo del módulo de\nalimentación (válvula de\ninversión)",
    "Error de aspiración de urea\nacuosa del módulo de\nalimentación",
    "Aumento de presión del\nmódulo de alimentación\n(motor de la bomba) 2",
    "Caída de presión del módulo\nde alimentación",
    "Aumento de la presión de la\nurea acuosa del módulo de\nalimentación",
    "Aumento de la temperatura del\ndepósito de urea acuosa",
    "Se excedió el tiempo de espera\nde recepción de CAN (A1DEFI)",
    "Se excedió el tiempo de espera\nde recepción de CAN (AT1T1I)",
    "Error en el sistema de SCR\n(inducción 1)",
    "Error en el sistema de SCR\n(inducción 2)",
    "Instrucción de acción FS 1 del\nsistema de la ECU",
    "Rotura del cableado del\ninterruptor de llave",
    "Error de verificación de datos\nentre la ECU y la DCU (tiempo\nde espera de verificación\nexcedido)"
	};
