
static const char *V_EngErrorMSG_FRA[308]={	
    "Erreur de tension du capteur de\nl’accélérateur 2 (élevée)",
    "Erreur de tension du capteur de\nl’accélérateur 2 (faible)",
    "Erreur de position ouverte du capteur\nde pédale",
    "Erreur de position fermée du capteur\nde pédale",
    "Erreur de tension du capteur de\nl’accélérateur 3 (élevée)",
    "Erreur de tension du capteur de\nl’accélérateur 3 (faible)",
    "Erreur de tension du capteur de\nposition du papillon des gaz\nd’admission (élevée)",
    "Erreur de tension du capteur de\nposition du papillon des gaz\nd’admission (faible)",
    "Erreur de tension du capteur de\nl’accélérateur 1 (élevée)",
    "Erreur de tension du capteur de\nl’accélérateur 1 (faible)",
    "Erreur de tension du capteur de\npression d’huile (élevée)",
    "Erreur de tension du capteur de\npression d’huile (faible)",
    "Chute de pression d’huile",
    "Erreur de tension du capteur de\npression côté EGR basse pression\n(élevée)",
    "Erreur de tension du capteur de\npression côté EGR basse pression\n(faible)",
    "Valeur d’apprentissage anormale du\ncapteur de pression côté EGR basse\npression",
    "Erreur de valeur détectée au niveau\ndu capteur de pression côté EGR\nbasse pression",
    "Erreur de tension du capteur de\ntempérature du collecteur\nd’admission (élevée)",
    "Erreur de tension du capteur de\ntempérature du collecteur\nd’admission (faible)",
    "Erreur de valeur détectée au niveau\ndu capteur de température du\ncollecteur d’admission",
    "Erreur de tension du capteur de\npression atmosphérique (élevée)",
    "Erreur de tension du capteur de\npression atmosphérique (faible)",
    "Erreur caractéristique du capteur de\npression atmosphérique",
    "Erreur de tension du capteur de\ntempérature du liquide de\nrefroidissement du moteur (élevée)",
    "Erreur de tension du capteur de\ntempérature du liquide de\nrefroidissement du moteur (faible)",
    "Augmentation de la température du\nliquide de refroidissement du moteur\n(surchauffe)",
    "Erreur de valeur détectée au niveau\ndu capteur de température du liquide\nde refroidissement du moteur",
    "Erreur de tension du capteur de\npression de la rampe (élevée)",
    "Erreur de tension du capteur de\npression de la rampe (faible)",
    "Augmentation excessive de la\npression de la rampe",
    "Erreur d’écart de la pression de la\nrampe (faible pression de la rampe)",
    "Rupture du câblage du commutateur\nde charge",
    "Erreur de charge",
    "Erreur de tension du capteur de\ntempérature de l’air ambiant (élevée)",
    "Erreur de tension du capteur de\ntempérature de l’air ambiant (faible)",
    "Erreur de valeur détectée au niveau\ndu capteur de température de l’air\nambiant",
    "Réception d’une valeur de\ntempérature de l’air ambiant\nincorrecte de l’ECU",
    "Erreur de tension du capteur de\ntempérature du collecteur\nd’échappement (élevée)",
    "Erreur de tension du capteur de\ntempérature du collecteur\nd’échappement (faible)",
    "Erreur de valeur détectée au niveau\ndu capteur de température du\ncollecteur d’échappement",
    "Erreur de tension du capteur de\ntempérature du carburant (élevée)",
    "Erreur de tension du capteur de\ntempérature du carburant (faible)",
    "Augmentation de la température du\ncarburant",
    "Vitesse excessive",
    "Expiration de la réception CAN (VI)",
    "Erreur des données reçues du CAN\n(VI)",
    "Erreur de tension du capteur de\ntempérature des gaz EGR (élevée)",
    "Erreur de tension du capteur de\ntempérature des gaz EGR (faible)",
    "Erreur de valeur détectée au niveau\ndu capteur de température des gaz\nEGR",
    "Erreur de vérification des données\nentre l’ECU et le DCU\n(non-correspondance du modèle de\nmoteur)",
    "Erreur de vérification des données\nentre l’ECU et le DCU\n(non-correspondance du numéro de\nsérie)",
    "Erreur EEPROM",
    "Court-circuit VB côté H/L de la\nsoupape de commande d’aspiration\n(soupape proportionnelle\nmagnétique)",
    "Rupture du câblage/court-circuit à la\nmasse côté H de la soupape de\ncommande d’aspiration (soupape\nproportionnelle magnétique)",
    "Erreur du circuit d’entraînement\n(blocage de la soupape de\ncommande d’aspiration)",
    "Rupture du câblage spécifique à\nl’injecteur du vérin numéro 1",
    "Court-circuit de la bobine de\nl’injecteur du vérin numéro 1 entre\nles bornes COM et TWV",
    "Circuit ouvert MOS de décharge de\nl’injecteur du vérin numéro 1",
    "Rupture du câblage spécifique à\nl’injecteur du vérin numéro 2",
    "Court-circuit de la bobine de\nl’injecteur du vérin numéro 2 entre\nles bornes COM et TWV",
    "Circuit ouvert MOS de décharge de\nl’injecteur du vérin numéro 2",
    "Rupture du câblage spécifique à\nl’injecteur du vérin numéro 3",
    "Court-circuit de la bobine de\nl’injecteur du vérin numéro 3 entre\nles bornes COM et TWV",
    "Circuit ouvert MOS de décharge de\nl’injecteur du vérin numéro 3",
    "Rupture du câblage spécifique à\nl’injecteur du vérin numéro 4",
    "Court-circuit de la bobine de\nl’injecteur du vérin numéro 4 entre\nles bornes COM et TWV",
    "Circuit ouvert MOS de décharge de\nl’injecteur du vérin numéro 4",
    "Erreur de tension du capteur de\npression côté EGR haute pression\n(élevée)",
    "Erreur de tension du capteur de\npression côté EGR haute pression\n(faible)",
    "Valeur d’apprentissage anormale du\ncapteur de pression côté EGR haute\npression",
    "Erreur de valeur détectée au niveau\ndu capteur de pression côté EGR\nhaute pression",
    "Erreur de protection de la pompe\nhaute pression",
    "Erreur de remplacement de la pompe\nhaute pression",
    "Mise hors tension sans maintien du\nrelais principal",
    "Faible niveau du réservoir d’urée\naqueuse (incitation 1)",
    "Faible niveau du réservoir d’urée\naqueuse (incitation 2)",
    "Rupture du câblage du capteur de\nniveau du réservoir d’urée aqueuse",
    "Court-circuit du capteur de niveau du\nréservoir d’urée aqueuse (AT1T1I)",
    "Erreur interne du contrôleur du\ncapteur de niveau du réservoir d’urée\naqueuse (AT1T1I)",
    "Erreur de valeur détectée au niveau\ndu capteur de niveau du réservoir\nd’urée aqueuse",
    "Rupture du câblage de la bobine du\nmoteur EGR",
    "Erreur de retour EGR",
    "Erreur de données EGR de l’ECM",
    "Erreur de tension EGR (tension\nexcessive)",
    "Erreur de tension EGR (faible)",
    "Court-circuit +B de la rangée\nd’injecteurs 1",
    "Court-circuit à la masse de la rangée\nd’injecteurs 1 ",
    "Rupture du câblage de la rangée\nd’injecteurs 1",
    "Erreur de l’horloge interne VDIC3 du\npilote d’injecteur IC-1",
    "Erreur de communication du pilote\nd’injecteur IC-1 entre VDIC3 et le\nmicro-ordinateur",
    "Court-circuit +B de la rangée\nd’injecteurs 2",
    "Court-circuit à la masse de la rangée\nd’injecteurs 2 ",
    "Rupture du câblage de la rangée\nd’injecteurs 2",
    "Erreur de l’horloge interne VDIC3 du\npilote d’injecteur IC-2",
    "Erreur de communication du pilote\nd’injecteur IC-2 entre VDIC3 et le\nmicro-ordinateur",
    "Rupture du câblage du circuit\nd’entraînement du papillon des gaz\nd’admission",
    "Court-circuit VB/à la masse du circuit\nd’entraînement du papillon des gaz\nd’admission ",
    "Erreur d’écart du circuit\nd’entraînement du papillon des gaz\nd’admission",
    "Erreur du cycle d’entraînement du\ncircuit d’entraînement du papillon des\ngaz d’admission",
    "Augmentation de la température du\ncontrôleur du capteur de température\ndu réservoir d’urée aqueuse/du\ncapteur de niveau du réservoir d’urée\naqueuse (AT1T1I)",
    "Rupture du câblage du circuit interne\ndu capteur de température du\nréservoir d’urée aqueuse (AT1T1I)",
    "Court-circuit du circuit interne du\ncapteur de température du réservoir\nd’urée aqueuse (AT1T1I)",
    "Panne interne du contrôleur du\ncapteur de température du réservoir\nd’urée aqueuse (AT1T1I)",
    "Augmentation de la température du\nréservoir d’urée aqueuse",
    "Erreur de valeur détectée au niveau\ndu capteur de température du\nréservoir d’urée aqueuse (erreur de\nlimite supérieure)",
    "Erreur de valeur détectée au niveau\ndu capteur de température du\nréservoir d’urée aqueuse (erreur de\nlimite inférieure)",
    "Erreur de valeur détectée au niveau\ndu capteur NOx en amont SCR\n(erreur de limite supérieure)",
    "Erreur de valeur détectée au niveau\ndu capteur NOx en amont SCR\n(erreur de limite inférieure)",
    "Erreur de tension du capteur de\ntempérature d’admission du DPF\n(élevée)",
    "Erreur de tension du capteur de\ntempérature d’admission du DPF\n(faible)",
    "Erreur de valeur détectée au niveau\ndu capteur de température\nd’admission du DPF",
    "Augmentation de la température\nd’admission du DPF",
    "Erreur de tension du capteur de\ntempérature intermédiaire du DPF\n(élevée)",
    "Erreur de tension du capteur de\ntempérature intermédiaire du DPF\n(faible)",
    "Erreur de valeur détectée au niveau\ndu capteur de température\nintermédiaire du DPF",
    "Chute de la température\nintermédiaire du DPF",
    "Augmentation de la température\nintermédiaire du DPF (panne après\ninjection)",
    "Erreur de tension du capteur de\npression différentielle du DPF\n(élevée)",
    "Erreur de tension du capteur de\npression différentielle du DPF (faible)",
    "Valeur d’apprentissage anormale du\ncapteur de pression différentielle du\nDPF",
    "Augmentation de la pression\ndifférentielle du DPF",
    "Augmentation de la température du\ncontrôleur du capteur de qualité de\nl’urée aqueuse/du capteur de\ntempérature du réservoir d’urée\naqueuse (A1DEFI)",
    "Rupture du câblage du circuit interne\ndu capteur de température du\nréservoir d’urée aqueuse (A1DEFI)",
    "Court-circuit du circuit interne du\ncapteur de température du réservoir\nd’urée aqueuse (A1DEFI)",
    "Panne interne du contrôleur du\ncapteur de température du réservoir\nd’urée aqueuse (A1DEFI)",
    "Rupture du câblage du circuit interne\ndu capteur de qualité de l’urée\naqueuse",
    "Court-circuit du circuit interne du\ncapteur de qualité de l’urée aqueuse",
    "Panne interne du contrôleur du\ncapteur de qualité de l’urée aqueuse",
    "Erreur de concentration du capteur\nde qualité de l’urée aqueuse (petit\nécart)",
    "Erreur de concentration du capteur\nde qualité de l’urée aqueuse (grand\nécart)",
    "Contamination du réservoir d’urée\naqueuse",
    "Erreur de tension du capteur de\npression côté DPF haute pression\n(élevée)",
    "Erreur de tension du capteur de\npression côté DPF haute pression\n(faible)",
    "Erreur de valeur détectée au niveau\ndu capteur de pression côté DPF\nhaute pression",
    "Régénération fixe en mode veille du\nDPF",
    "Échec de la régénération du DPF\n(échec de la régénération de\nrécupération)",
    "Régénération de récupération du\nDPF inhibée",
    "Mode de secours du DPF",
    "Demande de nettoyage des cendres\ndu DPF 1",
    "Demande de nettoyage des cendres\ndu DPF 2",
    "Erreur de tension du capteur de\npression de la pompe du module\nd’alimentation (élevée)",
    "Erreur de tension du capteur de\npression de la pompe du module\nd’alimentation (faible)",
    "Erreur de valeur détectée au niveau\ndu capteur de pression de la pompe\ndu module d’alimentation (erreur de\nlimite supérieure)",
    "Erreur de valeur détectée au niveau\ndu capteur de pression de la pompe\ndu module d’alimentation (erreur de\nlimite inférieure)",
    "Court-circuit VB côté L du chauffage\ndu flexible d’urée aqueuse (pression)",
    "Court-circuit à la masse côté L du\nchauffage du flexible d’urée aqueuse\n(pression)",
    "Rupture du câblage du chauffage du\nflexible d’urée aqueuse (pression)",
    "Court-circuit VB côté L du chauffage\ndu flexible d’urée aqueuse\n(refoulement)",
    "Court-circuit à la masse côté L du\nchauffage du flexible d’urée aqueuse\n(refoulement)",
    "Rupture du câblage du chauffage du\nflexible d’urée aqueuse (refoulement)",
    "Court-circuit VB côté L du chauffage\ndu flexible d’urée aqueuse\n(aspiration)",
    "Court-circuit à la masse côté L du\nchauffage du flexible d’urée aqueuse\n(aspiration)",
    "Rupture du câblage du chauffage du\nflexible d’urée aqueuse (aspiration)",
    "Erreur de tension du capteur de\ntempérature en amont du catalyseur\nSCR (élevée)",
    "Erreur de tension du capteur de\ntempérature en amont du catalyseur\nSCR (faible)",
    "Augmentation de la température en\namont du catalyseur SCR",
    "Erreur de valeur détectée au niveau\ndu capteur de température en amont\ndu catalyseur SCR (erreur de limite\nsupérieure)",
    "Erreur de valeur détectée au niveau\ndu capteur température en amont du\ncatalyseur SCR (erreur de limite\ninférieure)",
    "Erreur de valeur détectée au niveau\ndu capteur de température en amont\ndu catalyseur SCR lors de la\nvérification du démarrage à froid",
    "Court-circuit VB du câblage du signal\nPWM du module\nd’approvisionnement (moteur de la\npompe)",
    "Court-circuit à la masse du câblage\ndu signal PWM du module\nd’approvisionnement (moteur de la\npompe)",
    "Rupture du câblage du signal PWM\ndu module d’approvisionnement\n(moteur de la pompe)",
    "Erreur d’entraînement du module\nd’approvisionnement (moteur de la\npompe) 1",
    "Erreur d’entraînement du module\nd’approvisionnement (moteur de la\npompe) 2",
    "Erreur de validité du capteur de\npression différentielle du DPF/retrait\ndu matériel de la base du DPF",
    "Court-circuit à la masse côté L de la\nsoupape de chauffage du réservoir",
    "Rupture du câblage de la soupape\nde chauffage du réservoir",
    "Erreur de communication de l’ECU\nentre les micro-ordinateurs (erreur\nde communication MSC)",
    "Erreur de communication de l’ECU\nentre les micro-ordinateurs (erreur\nde communication SPI basée sur le\ndiagnostic d’erreur du capteur de\npression atmosphérique)",
    "Erreur de communication de l’ECU\nentre les micro-ordinateurs (erreur\nde communication SPI basée sur le\ndiagnostic d’erreur du\nmicro-ordinateur de surveillance)",
    "Erreur du convertisseur A/D du\nmicro-ordinateur de l’ECU",
    "Trajectoire d’arrêt d’injection\nanormale au niveau du\nmicro-ordinateur de l’ECU",
    "Court-circuit +B du témoin de\npréchauffage",
    "Court-circuit +B du témoin\nd’anomalie",
    "Court-circuit +B du relais du\ndémarreur",
    "Court-circuit +B du témoin de chute\nhydraulique",
    "Court-circuit +B du témoin\nd’avertissement orange",
    "Court-circuit +B du témoin\nd’affichage du changement de\nvitesse",
    "Court-circuit +B du témoin d’alarme\nde la température d’échappement",
    "Court-circuit +B du témoin d’alarme\nde la température du liquide de\nrefroidissement du moteur",
    "Court-circuit +B de l’avertisseur",
    "Court-circuit +B du témoin d’arrêt du\nmoteur rouge",
    "Court-circuit +B du témoin isochrone",
    "Court-circuit +B du témoin\nd’approbation de la régénération du\nDPF",
    "Court-circuit +B du témoin\nd’interdiction de la régénération du\nDPF",
    "Court-circuit +B du témoin de\ndemande de régénération du DPF",
    "Erreur du système EGR (incitation 1)",
    "Erreur du système EGR (incitation 2)",
    "Consigne d’action FS du système\nECU 2",
    "Erreur de valeur détectée au niveau\ndu capteur NOx en amont SCR\n(concentration O2)",
    "Court-circuit VB/rupture du câblage\ndu relais d’aide au démarrage",
    "Court-circuit à la masse du relais\nd’aide au démarrage",
    "Obstruction du filtre à air",
    "Erreur du séparateur d’eau et d’huile",
    "Erreur du signal du vilebrequin",
    "Aucun signal du vilebrequin",
    "Erreur du signal de l’arbre à came",
    "Aucun signal de l’arbre à came",
    "Accumulation excessive de PM du\nDPF (méthode C)",
    "Accumulation excessive de PM du\nDPF (méthode P)",
    "Erreur de régénération du DPF\n(échec de la régénération fixe)",
    "Erreur de régénération du DPF\n(régénération fixe non effectuée)",
    "Court-circuit de la bobine du moteur\nEGR",
    "Erreur du capteur de position EGR",
    "Blocage de la soupape EGR",
    "Erreur d’initialisation EGR",
    "Erreur de la thermistance haute\ntempérature EGR",
    "Erreur de la thermistance basse\ntempérature EGR",
    "Expiration de la réception CAN\n(TSC1 (SA1))",
    "Expiration de la réception CAN\n(TSC1 (SA2))",
    "Expiration de la réception CAN\n(Y_ECR1)",
    "Expiration de la réception CAN\n(Y_EC)",
    "Expiration de la réception CAN\n(Y_RSS)",
    "Expiration de la réception CAN de la\nsoupape EGR",
    "Valeur cible EGR hors de portée",
    "Expiration de la réception CAN\n(EBC1)",
    "Expiration de la réception CAN\n(Y_DRFIF)",
    "Erreur de position ouverte du double\ncapteur d’accélération",
    "Erreur de position fermée du double\ncapteur d’accélération",
    "Apprentissage de la pompe haute\npression non effectué",
    "Erreur IC de surveillance du\nprocesseur de l’ECU",
    "Erreur du processeur de l’ECU",
    "Erreur de saisie de correction des\ndonnées QR",
    "Erreur de charge du circuit\nd’entraînement de l’injecteur (faible\ncharge)",
    "Erreur de charge du circuit\nd’entraînement de l’injecteur\n(surcharge)",
    "Erreur de la somme de contrôle de la\nmémoire Flash ROM de l’ECU",
    "Erreur de tension du circuit 5 V du\ncapteur de l’ECU 1 (faible)",
    "Erreur de tension du circuit 5 V du\ncapteur de l’ECU 1 (élevée)",
    "Erreur de tension du circuit 5 V du\ncapteur de l’ECU 2 (faible)",
    "Erreur de tension du circuit 5 V du\ncapteur de l’ECU 2 (élevée)",
    "Données QR non écrites",
    "Erreur des données QR",
    "Pas de saisie du capteur de vitesse\ndu vilebrequin/du capteur de vitesse\nde l’arbre à cale (simultanée)",
    "Expiration de la réception CAN du\nDCU",
    "Court-circuit VB côté H du module\nd’approvisionnement (soupape\nd’inversion)",
    "Court-circuit GND côté H du module\nd’approvisionnement (soupape\nd’inversion)",
    "Court-circuit VB côté H du relais du\nchauffage du flexible/de la soupape\nde chauffage du réservoir",
    "Court-circuit à la masse côté H du\nrelais du chauffage du flexible/de la\nsoupape de chauffage du réservoir",
    "Court-circuit VB côté H du module\nd’approvisionnement (chauffage du\nmodule d’approvisionnement) ",
    "Court-circuit à la masse côté H du\nmodule d’approvisionnement\n(chauffage du module\nd’approvisionnement) ",
    "Rupture du câblage du module\nd’approvisionnement (chauffage du\nmodule d’approvisionnement)",
    "Erreur de valeur détectée au niveau\ndu module d’approvisionnement\n(chauffage du module\nd’approvisionnement)",
    "Fin forcée du système SCR",
    "Erreur de la tension d’alimentation\nDCU (élevée 1)",
    "Erreur de la tension d’alimentation\nDCU (faible 2)",
    "Erreur de la tension d’alimentation\nDCU (élevée 2)",
    "Erreur de la tension d’alimentation\nDCU (faible 1)",
    "Blocage du relais principal",
    "Ouverture anticipée du relais\nprincipal",
    "Expiration de la réception CAN du\ncapteur NOx en amont SCR",
    "Expiration de la réception CAN du\ncapteur NOx en aval SCR",
    "Expiration de la réception CAN du\nECU ",
    "Erreur de tension de l’alimentation\ndu capteur DCU",
    "Erreur de communication SPI DCU 1",
    "Erreur de communication SPI DCU 2",
    "Court-circuit côté H/L du module de\ndosage",
    "Rupture du câblage du module de\ndosage",
    "Court-circuit VB côté H du module de\ndosage",
    "Court-circuit à la masse du module\nde dosage",
    "Blocage de la soupape du module de\ndosage",
    "Erreur de lecture de la mémoire\nEEPROM",
    "Erreur d’écriture dans la mémoire\nEEPROM",
    "Court-circuit VB côté L du relais du\nchauffage du flexible",
    "Court-circuit à la masse côté L du\nrelais du chauffage du flexible",
    "Rupture du câblage du relais du\nchauffage du flexible",
    "Court-circuit VB côté L du module\nd’approvisionnement (chauffage du\nmodule d’approvisionnement) ",
    "Court-circuit VB côté L de la soupape\nde chauffage du réservoir",
    "Augmentation de la valeur NOx en\namont SCR",
    "Court-circuit du circuit interne du\ncapteur NOx en amont SCR",
    "Rupture du câblage du circuit interne\ndu capteur NOx en amont SCR",
    "Augmentation de la valeur NOx en\naval SCR",
    "Court-circuit du circuit interne du\ncapteur NOx en aval SCR",
    "Rupture du câblage du circuit interne\ndu capteur NOx en aval SCR",
    "Chauffage incomplet du capteur NOx\nen amont SCR",
    "Chauffage incomplet du capteur NOx\nen aval SCR",
    "Court-circuit VB côté L du module\nd’approvisionnement (soupape\nd’inversion)",
    "Court-circuit à la masse côté L du\nmodule d’approvisionnement\n(soupape d’inversion)",
    "Rupture du câblage du module\nd’approvisionnement (soupape\nd’inversion)",
    "Nettoyage NOx inefficace du\nsystème SCR",
    "Erreur de valeur détectée au niveau\ndu module d’approvisionnement\n(capteur de température du\nchauffage du module\nd’approvisionnement)",
    "Erreur de valeur détectée au niveau\ndu module d’approvisionnement\n(capteur de température du\nchauffage du module\nd’approvisionnement) lors de la\nvérification du démarrage à froid",
    "Erreur de valeur détectée au niveau\ndu module d’approvisionnement\n(capteur de température du module\nd’approvisionnement)",
    "Erreur de valeur détectée au niveau\ndu module d’approvisionnement\n(capteur de température du module\nd’approvisionnement) lors de la\nvérification du démarrage à froid",
    "Valeur erronée du module\nd’approvisionnement (capteur de\ntempérature du chauffage du module\nd’approvisionnement) reçue pour la\nvaleur du cycle d’informations de\ntempérature",
    "Valeur incorrecte du module\nd’approvisionnement (capteur de\ntempérature du chauffage du module\nd’approvisionnement) reçue pour la\nvaleur du cycle d’informations de\ntempérature",
    "Erreur du cycle PWM des\ninformations de température du\nmodule d’alimentation (moteur de la\npompe)",
    "Erreur du signal PWM des\ninformations de température du\nmodule d’alimentation (moteur de la\npompe)",
    "Valeur erronée du module\nd’approvisionnement (capteur de\ntempérature du module\nd’approvisionnement) reçue pour la\nvaleur du cycle d’informations de\ntempérature",
    "Valeur incorrecte du module\nd’approvisionnement (capteur de\ntempérature du module\nd’approvisionnement) reçue pour la\nvaleur du cycle d’informations de\ntempérature",
    "Le module d’alimentation (moteur de\nla pompe) ne démarre pas pour\nmesurer la température",
    "Augmentation de la pression du\nmodule d’approvisionnement (moteur\nde la pompe) 1",
    "Erreur de réduction de la pression du\nmodule d’approvisionnement (moteur\nde la pompe)",
    "Augmentation de la pression côté\nrefoulement du flexible d’urée\naqueuse",
    "Augmentation de la pression côté\npression du flexible d’urée aqueuse",
    "Erreur de stabilité de la pression du\nmodule d’approvisionnement (moteur\nde la pompe)",
    "Panne du module\nd’approvisionnement (soupape\nd’inversion)",
    "Erreur d’aspiration de l’urée aqueuse\ndu module d’approvisionnement",
    "Augmentation de la pression du\nmodule d’approvisionnement (moteur\nde la pompe) 2",
    "Chute de pression du module\nd’approvisionnement",
    "Augmentation de la pression de\nl’urée aqueuse du module\nd’approvisionnement",
    "Augmentation de la température du\nréservoir d’urée aqueuse",
    "Expiration de la réception CAN\n(A1DEFI)",
    "Expiration de la réception CAN\n(AT1T1I)",
    "Erreur du système SCR (incitation 1)",
    "Erreur du système SCR (incitation 2)",
    "Consigne d’action FS du système\nECU 1",
    "Rupture du câblage du contact",
    "Erreur de vérification des données\nentre l’ECU et le DCU (expiration de\nla vérification)"
	};
