
static const char *V_EngErrorMSG_ESP[308]={	
    "Error de tensión del sensor 2 del\nacelerador (alta)",
    "Error de tensión del sensor 2 del\nacelerador (baja)",
    "Error de posición abierta del sensor\ndel pedal",
    "Error de posición cerrada del sensor\ndel pedal",
    "Error de tensión del sensor 3 del\nacelerador (alta)",
    "Error de tensión del sensor 3 del\nacelerador (baja)",
    "Error de tensión del sensor de\nposición del regulador de admisión\n(alta)",
    "Error de tensión del sensor de\nposición del regulador de admisión\n(baja)",
    "Error de tensión del sensor 1 del\nacelerador (alta)",
    "Error de tensión del sensor 1 del\nacelerador (baja)",
    "Error de tensión del sensor de\npresión de aceite (alta)",
    "Error de tensión del sensor de\npresión de aceite (baja)",
    "Caída de la presión del aceite",
    "Error de tensión del sensor de\npresión del lado de baja presión de\nla EGR (alta)",
    "Error de tensión del sensor de\npresión del lado de baja presión de\nla EGR (baja)",
    "Valor de aprendizaje anómalo del\nsensor de presión del lado de baja\npresión de la EGR",
    "Error de valor detectado del sensor\nde presión del lado de baja presión\nde la EGR",
    "Error de tensión del sensor de\ntemperatura del colector de admisión\n(alta)",
    "Error de tensión del sensor de\ntemperatura del colector de admisión\n(baja)",
    "Error de valor detectado del sensor\nde temperatura del colector de\nadmisión",
    "Error de tensión del sensor de\npresión atmosférica (alta)",
    "Error de tensión del sensor de\npresión atmosférica (baja)",
    "Error característico del sensor de\npresión atmosférica",
    "Error de tensión del sensor de\ntemperatura del refrigerante del\nmotor (alta)",
    "Error de tensión del sensor de\ntemperatura del refrigerante del\nmotor (baja)",
    "Aumento de la temperatura del\nrefrigerante del motor\n(sobrecalentamiento)",
    "Error de valor detectado del sensor\nde temperatura del refrigerante del\nmotor",
    "Error de tensión del sensor de\npresión del raíl (alta)",
    "Error de tensión del sensor de\npresión del raíl (baja)",
    "Aumento excesivo de la presión del\nraíl",
    "Error de desviación de la presión del\nraíl (baja presión del raíl)",
    "Rotura del cableado del interruptor\nde carga",
    "Error de carga",
    "Error de tensión del sensor de\ntemperatura del aire ambiente (alta)",
    "Error de tensión del sensor de\ntemperatura del aire ambiente (baja)",
    "Error de valor detectado del sensor\nde temperatura del aire ambiente",
    "Recepción no válida del valor de la\ntemperatura ambiente en la ECU",
    "Error de tensión del sensor de\ntemperatura del colector de escape\n(alta)",
    "Error de tensión del sensor de\ntemperatura del colector de escape\n(baja)",
    "Error de valor detectado del sensor\nde temperatura del colector de\nescape",
    "Error de tensión del sensor de\ntemperatura de combustible (alta)",
    "Error de tensión del sensor de\ntemperatura de combustible (baja)",
    "Aumento de la temperatura del\ncombustible",
    "Velocidad excesiva",
    "Se excedió el tiempo de espera de\nrecepción de CAN (VI)",
    "Error de datos recibidos de CAN (VI)",
    "Error de tensión del sensor de\ntemperatura del gas de la EGR (alta)",
    "Error de tensión del sensor de\ntemperatura del gas de la EGR\n(baja)",
    "Error de valor detectado del sensor\nde temperatura del gas de la EGR",
    "Error de verificación de datos entre\nla ECU y la DCU (discrepancia del\nmodelo del motor)",
    "Error de verificación de datos entre\nla ECU y la DCU (discrepancia del\nn.º de serie)",
    "Error de EEPROM",
    "Cortocircuito VB del lado H/L de la\nválvula de control de aspiración\n(válvula proporcional magnética)",
    "Cortocircuito/rotura del cableado de\nGND del lado H de la válvula de\ncontrol de aspiración (válvula\nproporcional magnética)",
    "Error del circuito de accionamiento\n(la válvula de control de aspiración\nse atasca)",
    "Rotura de cableado específica del\ninyector del cilindro n.º 1",
    "Cortocircuito en la bobina del\ninyector del cilindro n.º 1 entre los\nterminales COM y TWV",
    "Circuito abierto de MOS de descarga\ndel inyector del cilindro n.º 1",
    "Rotura de cableado específica del\ninyector del cilindro n.º 2",
    "Cortocircuito en la bobina del\ninyector del cilindro n.º 2 entre los\nterminales COM y TWV",
    "Circuito abierto de MOS de descarga\ndel inyector del cilindro n.º 2",
    "Rotura de cableado específica del\ninyector del cilindro n.º 3",
    "Cortocircuito en la bobina del\ninyector del cilindro n.º 3 entre los\nterminales COM y TWV",
    "Circuito abierto de MOS de descarga\ndel inyector del cilindro n.º 3",
    "Rotura de cableado específica del\ninyector del cilindro n.º 4",
    "Cortocircuito en la bobina del\ninyector del cilindro n.º 4 entre los\nterminales COM y TWV",
    "Circuito abierto de MOS de descarga\ndel inyector del cilindro n.º 4",
    "Error de tensión del sensor de\npresión del lado de alta presión de la\nEGR (alta)",
    "Error de tensión del sensor de\npresión del lado de alta presión de la\nEGR (baja)",
    "Valor de aprendizaje anómalo del\nsensor de presión del lado de alta\npresión de la EGR",
    "Error de valor detectado del sensor\nde presión del lado de alta presión\nde la EGR",
    "Error de protección de la bomba de\nalta presión",
    "Error de sustitución de la bomba de\nalta presión",
    "Apagado sin autorretención del relé\nprincipal",
    "Bajo nivel del depósito de urea\nacuosa (inducción 1)",
    "Bajo nivel del depósito de urea\nacuosa (inducción 2)",
    "Rotura del cableado del sensor de\nnivel del depósito de urea acuosa",
    "Cortocircuito del sensor de nivel del\ndepósito de urea acuosa (AT1T1I)",
    "Error interno del controlador del\nsensor de nivel del depósito de urea\nacuosa (AT1T1I)",
    "Error de valor detectado del sensor\nde nivel del depósito de urea acuosa",
    "Rotura del cableado de la bobina del\nmotor de la EGR",
    "Error de retroalimentación de la EGR",
    "Error de datos del ECM de la EGR",
    "Error de tensión de la EGR\n(sobretensión)",
    "Error de tensión de la EGR (baja)",
    "Cortocircuito del banco de inyectores\n1 +B",
    "Cortocircuito de GND del banco de\ninyectores 1 ",
    "Rotura del cableado del banco de\ninyectores 1",
    "Error de reloj interno del controlador\ndel inyector IC-1 VDIC3",
    "Error de comunicación del\ncontrolador del inyector IC-1 entre el\nVDIC3 y el microordenador",
    "Cortocircuito del banco de inyectores\n2 +B",
    "Cortocircuito de GND del banco de\ninyectores 2 ",
    "Rotura del cableado del banco de\ninyectores 2",
    "Error de reloj interno del controlador\ndel inyector IC-2 VDIC3",
    "Error de comunicación del\ncontrolador del inyector IC-2 entre el\nVDIC3 y el microordenador",
    "Rotura del cableado del circuito de\naccionamiento del regulador de\nadmisión",
    "Cortocircuito de VB/GND del circuito\nde accionamiento del regulador de\nadmisión ",
    "Error de desviación del circuito de\naccionamiento del regulador de\nadmisión",
    "Error de funcionamiento del circuito\nde accionamiento del regulador de\nadmisión",
    "Aumento de temperatura del\ncontrolador del sensor de\ntemperatura del depósito de urea\nacuosa/Sensor de nivel del depósito\nde urea acuosa (AT1T1I)",
    "Rotura del cableado del circuito\ninterno del sensor de temperatura\ndel depósito de urea acuosa\n(AT1T1I)",
    "Cortocircuito del circuito interno del\nsensor de temperatura del depósito\nde urea acuosa (AT1T1I)",
    "Fallo interno del controlador del\nsensor de temperatura del depósito\nde urea acuosa (AT1T1I)",
    "Aumento de la temperatura del\ndepósito de urea acuosa",
    "Error de valor detectado del sensor\nde temperatura del depósito de urea\nacuosa (error de límite superior)",
    "Error de valor detectado del sensor\nde temperatura del depósito de urea\nacuosa (error de límite inferior)",
    "Error de valor detectado del sensor\nde NOx aguas arriba del SCR (error\nde límite superior)",
    "Error de valor detectado del sensor\nde NOx aguas arriba del SCR (error\nde límite inferior)",
    "Error de tensión del sensor de\ntemperatura de entrada del DPF\n(alta)",
    "Error de tensión del sensor de\ntemperatura de entrada del DPF\n(baja)",
    "Error de valor detectado del sensor\nde temperatura de entrada del DPF",
    "Aumento de la temperatura de\nentrada del DPF",
    "Error de tensión del sensor de\ntemperatura intermedia del DPF\n(alta)",
    "Error de tensión del sensor de\ntemperatura intermedia del DPF\n(baja)",
    "Error de valor detectado del sensor\nde temperatura intermedia del DPF",
    "Caída de la temperatura intermedia\ndel DPF",
    "Aumento de la temperatura\nintermedia del DPF (fallo posterior a\nla inyección)",
    "Error de tensión del sensor de\npresión diferencial del DPF (alta)",
    "Error de tensión del sensor de\npresión diferencial del DPF (baja)",
    "Valor de aprendizaje anómalo del\nsensor de presión diferencial del\nDPF",
    "Aumento de la presión diferencial del\nDPF",
    "Aumento de la temperatura del\ncontrolador del sensor de calidad de\nla urea acuosa/sensor de\ntemperatura del depósito de urea\nacuosa (A1DEFI)",
    "Rotura del cableado del circuito\ninterno del sensor de temperatura\ndel depósito de urea acuosa\n(A1DEFI)",
    "Cortocircuito del circuito interno del\nsensor de temperatura del depósito\nde urea acuosa (A1DEFI)",
    "Fallo interno del controlador del\nsensor de temperatura del depósito\nde urea acuosa (A1DEFI)",
    "Rotura del cableado del circuito\ninterno del sensor de calidad de urea\nacuosa",
    "Cortocircuito en el circuito interno del\nsensor de calidad de urea acuosa",
    "Fallo interno del controlador del\nsensor de calidad de urea acuosa",
    "Error de concentración del sensor de\ncalidad de urea acuosa (desviación\npequeña)",
    "Error de concentración del sensor de\ncalidad de urea acuosa (desviación\ngrande)",
    "Contaminación del depósito de urea\nacuosa",
    "Error de tensión del sensor de\npresión del lado de alta presión de la\nDPF (alta)",
    "Error de tensión del sensor de\npresión del lado de alta presión de la\nDPF (baja)",
    "Error de valor detectado del sensor\nde presión del lado de alta presión\nde la DPF",
    "Regeneración estacionaria del DPF\nen espera",
    "Fallo de regeneración del DPF (fallo\nde regeneración de recuperación)",
    "Regeneración de recuperación del\nDPF inhibida",
    "Modo de copia de seguridad del DPF",
    "Solicitud de limpieza de cenizas del\nDPF 1",
    "Solicitud de limpieza de cenizas del\nDPF 2",
    "Error de tensión del sensor de\npresión de la bomba del módulo de\nalimentación (alta)",
    "Error de tensión del sensor de\npresión de la bomba del módulo de\nalimentación (baja)",
    "Error de valor detectado del sensor\nde presión de la bomba del módulo\nde alimentación (error de límite\nsuperior)",
    "Error de valor detectado del sensor\nde presión de la bomba del módulo\nde alimentación (error de límite\ninferior)",
    "Cortocircuito de VB del lado Izq. del\ncalentador de manguera de urea\nacuosa (presión)",
    "Cortocircuito de GND del lado Izq.\ndel calentador de manguera de urea\nacuosa (presión)",
    "Rotura de cableado del calentador\nde manguera de urea acuosa\n(presión)",
    "Cortocircuito de VB del lado Izq. del\ncalentador de manguera de urea\nacuosa (reflujo)",
    "Cortocircuito de GND del lado Izq.\ndel calentador de manguera de urea\nacuosa (reflujo)",
    "Rotura de cableado del calentador\nde manguera de urea acuosa\n(reflujo)",
    "Cortocircuito de VB del lado Izq. del\ncalentador de manguera de urea\nacuosa (aspiración)",
    "Cortocircuito de GND del lado Izq.\ndel calentador de manguera de urea\nacuosa (aspiración)",
    "Rotura de cableado del calentador\nde manguera de urea acuosa\n(aspiración)",
    "Error de tensión del sensor de\ntemperatura aguas arriba del\ncatalizador SCR (alta)",
    "Error de tensión del sensor de\ntemperatura aguas arriba del\ncatalizador SCR (baja)",
    "Aumento de la temperatura aguas\narriba del catalizador SCR",
    "Error de valor detectado del sensor\nde temperatura aguas arriba del\ncatalizador SCR (error de límite\nsuperior)",
    "Error de valor detectado del sensor\nde temperatura aguas arriba del\ncatalizador SCR (error de límite\ninferior)",
    "El sensor de temperatura\nascendente del catalizador SCR\ndetectó un error de valor en la\ncomprobación de arranque en frío",
    "Cortocircuito de VB del cableado de\nseñal de PWM del módulo de\nalimentación (motor de la bomba)",
    "Cortocircuito de GND del cableado\nde señal de PWM del módulo de\nalimentación (motor de la bomba)",
    "Rotura del cableado de señal de\nPWM del módulo de alimentación\n(motor de la bomba)",
    "Error de accionamiento del módulo\nde alimentación (motor de la bomba)\n1",
    "Error de accionamiento del módulo\nde alimentación (motor de la bomba)\n2",
    "Eliminación del material base del\nDPF/Error de validez del sensor de\npresión diferencial del DPF",
    "Cortocircuito de GND del lado Izq. de\nla válvula de calefacción del depósito",
    "Rotura del cableado de la válvula de\ncalefacción del depósito",
    "Error de comunicación de la ECU\nentre microordenadores (error de\ncomunicación de MSC)",
    "Error de comunicación de la ECU\nentre microordenadores (error de\ncomunicación de SPI basado en el\ndiagnóstico de error del sensor de\npresión atmosférica)",
    "Error de comunicación de la ECU\nentre microordenadores (error de\ncomunicación de SPI basado en el\ndiagnóstico de errores del\nmicroordenador de vigilancia)",
    "Error del convertidor A/D del\nmicroordenador de la ECU",
    "Error de ruta de parada de inyección\nanómala en el microordenador de la\nECU",
    "Cortocircuito de lámpara de\nprecalentamiento +B",
    "Cortocircuito de lámpara de avería\n+B",
    "Cortocircuito del relé de arranque +B",
    "Cortocircuito de lámpara de caída\nhidráulica +B",
    "Cortocircuito de luz de advertencia\námbar +B",
    "Cortocircuito de indicador luminoso\nde cambio de velocidad +B",
    "Cortocircuito de lámpara de alarma\nde temperatura de escape +B",
    "Cortocircuito de lámpara de alarma\nde temperatura del refrigerante del\nmotor +B",
    "Cortocircuito del zumbador +B",
    "Cortocircuito de luz roja de parada\ndel motor +B",
    "Cortocircuito de la lámpara isócrona\n+B",
    "Cortocircuito de la lámpara de\naprobación de regeneración del DPF\n+B",
    "Cortocircuito de la lámpara de\nprohibición de regeneración del DPF\n+B",
    "Cortocircuito de la lámpara de\nsolicitud de regeneración del DPF +B",
    "Error en el sistema de EGR\n(inducción 1)",
    "Error en el sistema de EGR\n(inducción 2)",
    "Instrucción de acción FS 2 del\nsistema de la ECU",
    "Error de valor detectado del sensor\nde NOx aguas arriba del SCR\n(concentración de O2)",
    "Rotura del cableado del relé de\nayuda al arranque/Cortocircuito de\nVB",
    "Cortocircuito de GND del relé de\nayuda al arranque",
    "Obstrucción del filtro de aire",
    "Error en el separador de aceite y\nagua",
    "Error de señal del cigüeñal",
    "Sin señal del cigüeñal",
    "Error de señal del árbol de levas",
    "Sin señal del árbol de levas",
    "Acumulación excesiva de PM en el\nDPF (método C)",
    "Acumulación excesiva de PM en el\nDPF (método P)",
    "Error de regeneración del DPF (fallo\nde regeneración estacionaria)",
    "Error de regeneración del DPF\n(regeneración estacionaria no\noperada)",
    "Cortocircuito en la bobina del motor\nde la EGR",
    "Error del sensor de posición de la\nEGR",
    "La válvula de la EGR se atasca",
    "Error de inicialización de la EGR",
    "Error del termistor de alta\ntemperatura de la EGR",
    "Error del termistor de baja\ntemperatura de la EGR",
    "Se excedió el tiempo de espera de\nrecepción de CAN (TSC1 (SA1))",
    "Se excedió el tiempo de espera de\nrecepción de CAN (TSC1 (SA2))",
    "Se excedió el tiempo de espera de\nrecepción de CAN (Y_ECR1)",
    "Se excedió el tiempo de espera de\nrecepción de CAN (Y_EC)",
    "Se excedió el tiempo de espera de\nrecepción de CAN (Y_RSS)",
    "Se excedió el tiempo de espera de\nrecepción CAN de la válvula EGR",
    "Valor objetivo de la EGR fuera de\nrango",
    "Se excedió el tiempo de espera de\nrecepción de CAN (EBC1)",
    "Se excedió el tiempo de espera de\nrecepción de CAN (Y_DRFIF)",
    "Error de posición abierta del sensor\ndel acelerador dual",
    "Error de posición cerrada del sensor\ndel acelerador dual",
    "No se ha realizado el aprendizaje de\nla bomba de alta presión",
    "Error del CI de monitorización de la\nCPU de la ECU",
    "Error de la CPU de la ECU",
    "Error de entrada de corrección de\ndatos QR",
    "Error de carga del circuito de\naccionamiento del inyector (carga\nbaja)",
    "Error de carga del circuito de\naccionamiento del inyector\n(sobrecarga)",
    "Error de suma de comprobación de\nla ROM flash de la ECU",
    "Error de tensión del circuito 1 de 5 V\ndel sensor de la ECU (baja)",
    "Error de tensión del circuito 1 de 5 V\ndel sensor de la ECU (alta)",
    "Error de tensión del circuito 2 de 5 V\ndel sensor de la ECU (baja)",
    "Error de tensión del circuito 2 de 5 V\ndel sensor de la ECU (alta)",
    "Datos de QR no escritos",
    "Error de datos de QR",
    "Sin entrada de sensor de velocidad\ndel cigüeñal/sensor de velocidad del\nárbol de levas (simultánea)",
    "Se excedió el tiempo de espera de\nrecepción CAN de la DCU",
    "Cortocircuito de VB del lado H del\nmódulo de alimentación (válvula de\ninversión)",
    "Cortocircuito de GND del lado H del\nmódulo de alimentación (válvula de\ninversión)",
    "Cortocircuito de VB del lado H de\nrelé del calentador de la\nmanguera/Válvula de calefacción del\ndepósito",
    "Cortocircuito de GND del lado H de\nrelé del calentador de la\nmanguera/Válvula de calefacción del\ndepósito",
    "Cortocircuito de VB del lado H del\nmódulo de alimentación (calentador\ndel módulo de alimentación) ",
    "Cortocircuito de GND del lado H del\nmódulo de alimentación (calentador\ndel módulo de alimentación) ",
    "Rotura del cableado del módulo de\nalimentación (calentador del módulo\nde alimentación)",
    "Error de valor detectado del módulo\nde alimentación (calentador del\nmódulo de alimentación)",
    "Finalización forzada del sistema\nSCR",
    "Error de tensión de alimentación de\nla DCU (alta 1)",
    "Error de tensión de alimentación de\nla DCU (baja 2)",
    "Error de tensión de alimentación de\nla DCU (alta 2)",
    "Error de tensión de alimentación de\nla DCU (baja 1)",
    "El relé principal se atasca",
    "Apertura anticipada del relé principal",
    "Tiempo de espera de recepción CAN\ndel sensor de NOx aguas arriba de\nSCR",
    "Tiempo de espera de recepción CAN\ndel sensor de NOx aguas abajo de\nSCR",
    "Se excedió el tiempo de espera de\nrecepción CAN de la ECU ",
    "Error de tensión de alimentación del\nsensor de la DCU",
    "Error de comunicación de SPI de la\nDCU 1",
    "Error de comunicación de SPI de la\nDCU 2",
    "Cortocircuito del lado H/L del módulo\nde dosificación",
    "Rotura del cableado del módulo de\ndosificación",
    "Cortocircuito de VB del lado H del\nmódulo de dosificación",
    "Cortocircuito de GND del módulo de\ndosificación",
    "Válvula del módulo de dosificación\natascada",
    "Error de lectura de la memoria\nEEPROM",
    "Error de escritura de la memoria\nEEPROM",
    "Cortocircuito de VB del lado Izq. del\nrelé del calentador de manguera",
    "Cortocircuito de GND del lado Izq.\ndel relé del calentador de manguera",
    "Rotura del cableado del relé del\ncalentador de la manguera",
    "Cortocircuito de VB del lado Izq. del\nmódulo de alimentación (calentador\ndel módulo de alimentación) ",
    "Cortocircuito de VB del lado Izq. de\nla válvula de calefacción del depósito",
    "Aumento del valor de NOx aguas\narriba del SCR",
    "Cortocircuito del circuito interno del\nsensor de NOx aguas arriba del SCR",
    "Rotura del cableado del circuito\ninterno del sensor de NOx aguas\narriba del SCR",
    "Aumento del valor de NOx aguas\nabajo del SCR",
    "Cortocircuito del circuito interno del\nsensor de NOx aguas abajo del SCR",
    "Rotura del cableado del circuito\ninterno del sensor de NOx aguas\nabajo del SCR",
    "Calentamiento incompleto del sensor\nde NOx aguas arriba del SCR",
    "Calentamiento incompleto del sensor\nde NOx aguas abajo del SCR",
    "Cortocircuito de VB del lado Izq. del\nmódulo de alimentación (válvula de\ninversión)",
    "Cortocircuito de GND del lado Izq.\ndel módulo de alimentación (válvula\nde inversión)",
    "Rotura de cableado del módulo de\nalimentación (válvula de inversión)",
    "Sistema SCR de limpieza de NOx\nineficiente",
    "Error de valor detectado del módulo\nde alimentación (sensor de\ntemperatura del calentador del\nmódulo de alimentación)",
    "Error de valor detectado del módulo\nde alimentación (sensor de\ntemperatura del calentador del\nmódulo de alimentación) en la\ncomprobación de arranque en frío",
    "Error de valor detectado del módulo\nde alimentación (sensor de\ntemperatura del módulo de\nalimentación)",
    "Error de valor detectado del módulo\nde alimentación (sensor de\ntemperatura del módulo de\nalimentación) en la comprobación de\narranque en frío",
    "Valor defectuoso recibido del módulo\nde alimentación (sensor de\ntemperatura del calentador del\nmódulo de alimentación) para la\ninformación de temperatura valor de\nservicio",
    "Valor no válido recibido del módulo\nde alimentación (sensor de\ntemperatura del calentador del\nmódulo de alimentación) para la\ninformación de temperatura valor de\nservicio",
    "Error de ciclo PWM de información\nsobre la temperatura del módulo de\nalimentación (motor de la bomba)",
    "Error de señal PWM de información\nsobre la temperatura del módulo de\nalimentación (motor de la bomba)",
    "Valor defectuoso recibido del módulo\nde alimentación (sensor de\ntemperatura del módulo de\nalimentación) para la información de\ntemperatura valor de servicio",
    "Valor no válido recibido del módulo\nde alimentación (sensor de\ntemperatura del módulo de\nalimentación) para la información de\ntemperatura valor de servicio",
    "El módulo de alimentación (motor de\nla bomba) no arranca para medir la\ntemperatura",
    "Aumento de presión del módulo de\nalimentación (motor de la bomba) 1",
    "Error de reducción de presión del\nmódulo de alimentación (motor de la\nbomba)",
    "Aumento de la presión del lado de\nreflujo de la manguera de urea\nacuosa",
    "Aumento de la presión del lado de\npresión de la manguera de urea\nacuosa",
    "Error de estabilidad de presión del\nmódulo de alimentación (motor de la\nbomba)",
    "Fallo del módulo de alimentación\n(válvula de inversión)",
    "Error de aspiración de urea acuosa\ndel módulo de alimentación",
    "Aumento de presión del módulo de\nalimentación (motor de la bomba) 2",
    "Caída de presión del módulo de\nalimentación",
    "Aumento de la presión de la urea\nacuosa del módulo de alimentación",
    "Aumento de la temperatura del\ndepósito de urea acuosa",
    "Se excedió el tiempo de espera de\nrecepción de CAN (A1DEFI)",
    "Se excedió el tiempo de espera de\nrecepción de CAN (AT1T1I)",
    "Error en el sistema de SCR\n(inducción 1)",
    "Error en el sistema de SCR\n(inducción 2)",
    "Instrucción de acción FS 1 del\nsistema de la ECU",
    "Rotura del cableado del interruptor\nde llave",
    "Error de verificación de datos entre\nla ECU y la DCU (tiempo de espera\nde verificación excedido)"
	};
