
static const char *V_EngErrorMSG_DEU[308]={	
    "Spannungsfehler Gaspedalsensor 2\n(hoch)",
    "Spannungsfehler Gaspedalsensor 2\n(niedrig)",
    "Fehler offene Stellung\nFahrpedalsensor",
    "Fehler geschlossene Stellung\nFahrpedalsensor",
    "Spannungsfehler Gaspedalsensor 3\n(hoch)",
    "Spannungsfehler Gaspedalsensor 3\n(niedrig)",
    "Spannungsfehler\nAnsaugdrosselklappen-\nPositionssensor (hoch)",
    "Spannungsfehler\nAnsaugdrosselklappen-\nPositionssensor (niedrig)",
    "Spannungsfehler Gaspedalsensor 1\n(hoch)",
    "Spannungsfehler Gaspedalsensor 1\n(niedrig)",
    "Spannungsfehler Öldrucksensor\n(hoch)",
    "Spannungsfehler Öldrucksensor\n(niedrig)",
    "Öldruckabfall",
    "Spannungsfehler des Drucksensors\nauf EGR-Niederdruckseite (hoch)",
    "Spannungsfehler des Drucksensors\nauf EGR-Niederdruckseite (niedrig)",
    "Anormaler Lernwert am Drucksensor\nauf EGR-Niederdruckseite",
    "Fehler erkannter Wert am\nDrucksensor auf\nEGR-Niederdruckseite",
    "Spannungsfehler\nEinlasskrümmer-Temperatursensor\n(hoch)",
    "Spannungsfehler\nEinlasskrümmer-Temperatursensor\n(niedrig)",
    "Fehler erkannter Wert am\nEinlasskrümmer-Temperatursensor",
    "Spannungsfehler\nAtmosphärendrucksensor (hoch)",
    "Spannungsfehler\nAtmosphärendrucksensor (niedrig)",
    "Kennlinienfehler\nAtmosphärendrucksensor",
    "Spannungsfehler\nMotorkühlmittel-Temperatursensor\n(hoch)",
    "Spannungsfehler\nMotorkühlmittel-Temperatursensor\n(niedrig)",
    "Temperaturanstieg des\nMotorkühlmittels (Überhitzung)",
    "Fehler erkannter Wert am\nMotorkühlmittel-Temperatursensor",
    "Spannungsfehler\nKraftstoffleitungsdrucksensor (hoch)",
    "Spannungsfehler\nKraftstoffleitungsdrucksensor\n(niedrig)",
    "Übermäßiger Druckanstieg in der\nKraftstoffleitung",
    "Abweichungsfehler\nKraftstoffleitungsdruck (niedriger\nLeitungsdruck)",
    "Ladeschalter-Kabelbruch",
    "Ladefehler",
    "Spannungsfehler\nUmgebungsluft-Temperatursensor\n(hoch)",
    "Spannungsfehler\nUmgebungsluft-Temperatursensor\n(niedrig)",
    "Fehler erkannter Wert am\nUmgebungsluft-Temperatursensor",
    "ECU empfängt ungültigen Wert der\nUmgebungslufttemperatur",
    "Spannungsfehler\nAuspuffkrümmer-Temperatursensor\n(hoch)",
    "Spannungsfehler\nAuspuffkrümmer-Temperatursensor\n(niedrig)",
    "Fehler erkannter Wert am\nAuspuffkrümmer-Temperatursensor",
    "Spannungsfehler\nKraftstofftemperatursensor (hoch)",
    "Spannungsfehler\nKraftstofftemperatursensor (niedrig)",
    "Temperaturanstieg des Kraftstoffs",
    "Übermäßige Geschwindigkeit",
    "Zeitüberschreitung beim\nCAN-Empfang (VI)",
    "Fehler der CAN-Empfangsdaten (VI)",
    "Spannungsfehler\nEGR-Gastemperatursensor (hoch)",
    "Spannungsfehler\nEGR-Gastemperatursensor (niedrig)",
    "Fehler erkannter Wert am\nEGR-Gastemperatursensor",
    "Datenüberprüfungsfehler zwischen\nECU und DCU (Abweichung\nMotortyp)",
    "Datenüberprüfungsfehler zwischen\nECU und DCU (Abweichung\nSeriennummer)",
    "EEPROM-Fehler",
    "Ansaugregelventil (magnetisches\nProportionalventil) Kurzschluss am\nVB auf H/L-Seite",
    "Ansaugregelventil (magnetisches\nProportionalventil)\nKurzschluss/Kabelbruch an GND auf\nH-Seite",
    "Fehler im Steuerkreis\n(Ansaugsteuerventil klemmt)",
    "Kabelbruch an Injektorkabeln\nZylinder 1",
    "Kurzschluss zwischen den Klemmen\nCOM und TWV in Spule von Injektor\nZylinder 1",
    "Offener Stromkreis MOS-Auslauf des\nInjektors Zylinder 1",
    "Kabelbruch an Injektorkabeln\nZylinder 2",
    "Kurzschluss zwischen den Klemmen\nCOM und TWV in Spule von Injektor\nZylinder 2",
    "Offener Stromkreis MOS-Auslauf des\nInjektors Zylinder 2",
    "Kabelbruch an Injektorkabeln\nZylinder 3",
    "Kurzschluss zwischen den Klemmen\nCOM und TWV in Spule von Injektor\nZylinder 3",
    "Offener Stromkreis MOS-Auslauf des\nInjektors Zylinder 3",
    "Kabelbruch an Injektorkabeln\nZylinder 4",
    "Kurzschluss zwischen den Klemmen\nCOM und TWV in Spule von Injektor\nZylinder 4",
    "Offener Stromkreis MOS-Auslauf des\nInjektors Zylinder 4",
    "Spannungsfehler des Drucksensors\nauf EGR-Hochdruckseite (hoch)",
    "Spannungsfehler des Drucksensors\nauf EGR-Hochdruckseite (niedrig)",
    "Anormaler Lernwert am Drucksensor\nauf EGR-Hochdruckseite",
    "Fehler erkannter Wert am\nDrucksensor auf\nEGR-Hochdruckseite",
    "Fehler Schutz der Hochdruckpumpe",
    "Fehler Austausch der\nHochdruckpumpe",
    "Stromabschaltung ohne\nSelbsthaltung des Hauptrelais",
    "Niedriger Füllstand des\nHarnstoff-Wasser-Tanks (Auslöser 1)",
    "Niedriger Füllstand des\nHarnstoff-Wasser-Tanks (Auslöser 2)",
    "Kabelbruch am Füllstandsensor des\nHarnstoff-Wasser-Tanks",
    "Kurzschluss am Füllstandsensor des\nHarnstoff-Wasser-Tanks (AT1T1I)",
    "Interner Steuerungsfehler\nFüllstandsensor des\nHarnstoff-Wasser-Tanks (AT1T1I)",
    "Fehler erkannter Wert am\nFüllstandsensor des\nHarnstoff-Wasser-Tanks",
    "Kabelbruch an EGR-Motorspule",
    "EGR-Feedbackfehler",
    "EGR ECM-Datenfehler",
    "EGR-Spannungsfehler\n(Überspannung)",
    "EGR-Spannungsfehler (niedrig)",
    "Kurzschluss Einspritzung Bank 1 +B",
    "Kurzschluss Einspritzung Bank 1\nGND ",
    "Kabelbruch Einspritzung Bank 1",
    "Injektor-Antrieb IC-1 VDIC3 interner\nTaktfehler",
    "Injektor-Antrieb IC-1\nKommunikationsfehler zwischen\nVDIC3 und Mikrocomputer",
    "Kurzschluss Einspritzung Bank 2 +B",
    "Kurzschluss Einspritzung Bank 2\nGND ",
    "Kabelbruch Einspritzung Bank 2",
    "Injektor-Antrieb IC-2 VDIC3 interner\nTaktfehler",
    "Injektor-Antrieb IC-2\nKommunikationsfehler zwischen\nVDIC3 und Mikrocomputer",
    "Kabelbruch\nAnsaugdrosselklappen-Steuerkreis",
    "VB/GND-Kurzschluss\nAnsaugdrosselklappen-Steuerkreis ",
    "Abweichungsfehler\nAnsaugdrosselklappen-Steuerkreis",
    "Funktionsfehler des Antriebs\nAnsaugdrosselklappen-Steuerkreis",
    "Temperatursensor/Füllstandsensor\ndes Harnstoff-Wasser-Tanks\n(AT1T1I), Temperaturanstieg in\nSteuerung",
    "Interner Kabelbruch\nTemperatursensor des\nHarnstoff-Wasser-Tanks (AT1T1I)",
    "Interner Kurzschluss am\nTemperatursensor des\nHarnstoff-Wasser-Tanks (AT1T1I)",
    "Interner Steuerungsfehler\nTemperatursensor des\nHarnstoff-Wasser-Tanks (AT1T1I)",
    "Temperaturanstieg\nHarnstoff-Wasser-Tank",
    "Fehler erkannter Wert am\nTemperatursensor des\nHarnstoff-Wasser-Tanks (oberer\nGrenzwertfehler)",
    "Fehler erkannter Wert am\nTemperatursensor des\nHarnstoff-Wasser-Tanks (unterer\nGrenzwertfehler)",
    "Fehler erkannter Wert NOx-Sensor\nvor SCR (oberer Grenzwertfehler)",
    "Fehler erkannter Wert NOx-Sensor\nvor SCR (unterer Grenzwertfehler)",
    "Spannungsfehler am\nTemperatursensor DPF-Einlass\n(hoch)",
    "Spannungsfehler am\nTemperatursensor DPF-Einlass\n(niedrig)",
    "Fehler erkannter Wert\nTemperatursensor DPF-Einlass",
    "Temperaturanstieg DPF-Einlass",
    "Spannungsfehler am\nDPF-Zwischentemperatursensor\n(hoch)",
    "Spannungsfehler am\nDPF-Zwischentemperatursensor\n(niedrig)",
    "Fehler erkannter Wert\nDPF-Zwischentemperatursensor",
    "Abfall der DPF-Zwischentemperatur",
    "Anstieg der\nDPF-Zwischentemperatur (Störung\nnach Einspritzung)",
    "Spannungsfehler am\nDPF-Differenzdrucksensor (hoch)",
    "Spannungsfehler am\nDPF-Differenzdrucksensor (niedrig)",
    "DPF-Differenzdrucksensor\nanormaler Lernwert",
    "Anstieg des DPF-Differenzdrucks",
    "Temperaturanstieg in Steuerung von\nHarnstoff-Wasser-\nQualitätssensor/Temperatursensor\ndes Harnstoff-Wasser-Tanks\n(A1DEFI)",
    "Interner Kabelbruch\nTemperatursensor des\nHarnstoff-Wasser-Tanks (A1DEFI)",
    "Interner Kurzschluss am\nTemperatursensor des\nHarnstoff-Wasser-Tanks (A1DEFI)",
    "Interner Steuerungsfehler\nTemperatursensor des\nHarnstoff-Wasser-Tanks (A1DEFI)",
    "Interner Kabelbruch\nHarnstoff-Wasser-Qualitätssensor",
    "Interner Kurzschluss am\nHarnstoff-Wasser-Qualitätssensor",
    "Interner Steuerungsfehler\nHarnstoff-Wasser-Qualitätssensor",
    "Konzentrationsfehler\nHarnstoff-Wasser-Qualitätssensor\n(geringe Abweichung)",
    "Konzentrationsfehler\nHarnstoff-Wasser-Qualitätssensor\n(große Abweichung)",
    "Verschmutzung im\nHarnstoff-Wasser-Tank",
    "Spannungsfehler des Drucksensors\nauf DPF-Hochdruckseite (hoch)",
    "Spannungsfehler des Drucksensors\nauf DPF-Hochdruckseite (niedrig)",
    "Fehler erkannter Wert am\nDrucksensor auf\nDPF-Hochdruckseite",
    "DPF stationäre\nRegenerationsbereitschaft",
    "DPF-Regenerationsfehler\n(Regenerationsrückgewinnungsfehler)",
    "DPF Regenerationsrückgewinnung\ngesperrt",
    "DPF-Sicherungsmodus",
    "DPF Aschereinigungsanforderung 1",
    "DPF Aschereinigungsanforderung 2",
    "Spannungsfehler am\nVersorgungsmodul-\nPumpendrucksensor (hoch)",
    "Spannungsfehler am\nVersorgungsmodul-\nPumpendrucksensor (niedrig)",
    "Fehler erkannter Wert am\nVersorgungsmodul-Pumpensensor\n(oberer Grenzwertfehler)",
    "Fehler erkannter Wert am\nVersorgungsmodul-Pumpensensor\n(unterer Grenzwertfehler)",
    "Harnstoff-Wasser-Schlauchheizung\n(Druck) VB-Kurzschluss L-Seite",
    "Harnstoff-Wasser-Schlauchheizung\n(Druck) GND-Kurzschluss L-Seite",
    "Kabelbruch an\nHarnstoff-Wasser-Schlauchheizung\n(Druck)",
    "Harnstoff-Wasser-Schlauchheizung\n(Rückfluss) VB-Kurzschluss L-Seite",
    "Harnstoff-Wasser-Schlauchheizung\n(Rückfluss) GND-Kurzschluss\nL-Seite",
    "Kabelbruch an\nHarnstoff-Wasser-Schlauchheizung\n(Rückfluss)",
    "Harnstoff-Wasser-Schlauchheizung\n(Ansaugung) VB-Kurzschluss L-Seite",
    "Harnstoff-Wasser-Schlauchheizung\n(Ansaugung) GND-Kurzschluss\nL-Seite",
    "Kabelbruch an\nHarnstoff-Wasser-Schlauchheizung\n(Ansaugung)",
    "Spannungsfehler am\nTemperatursensor vor\nSCR-Katalysator (hoch)",
    "Spannungsfehler am\nTemperatursensor vor\nSCR-Katalysator (niedrig)",
    "Temperaturanstieg vor\nSCR-Katalysator",
    "Fehler erkannter Wert\nTemperatursensor vor\nSCR-Katalysator (oberer\nGrenzwertfehler)",
    "Fehler erkannter Wert\nTemperatursensor vor\nSCR-Katalysator (unterer\nGrenzwertfehler)",
    "Fehler erkannter Wert\nTemperatursensor vor\nSCR-Katalysator bei\nKaltstartüberprüfung",
    "VB-Kurzschluss Versorgungsmodul\n(Pumpenmotor)\nPWM-Signalverkabelung",
    "GND-Kurzschluss\nVersorgungsmodul (Pumpenmotor)\nPWM-Signalverkabelung",
    "Kabelbruch Versorgungsmodul\n(Pumpenmotor)\nPWM-Signalverkabelung",
    "Antriebsfehler 1 Versorgungsmodul\n(Pumpenmotor)",
    "Antriebsfehler 2 Versorgungsmodul\n(Pumpenmotor)",
    "Gültigkeitsfehler\nDPF-Grundmaterialaustrag/DPF-\nDifferenzdrucksensor",
    "Tankheizungsventil\nGND-Kurzschluss L-Seite",
    "Kabelbruch Tankheizungsventil",
    "ECU-Kommunikationsfehler\nzwischen Mikrocomputern\n(MSC-Kommunikationsfehler)",
    "ECU-Kommunikationsfehler\nzwischen Mikrocomputern\n(SPI-Kommunikationsfehler\nbasierend auf der Fehlerdiagnose\ndes Atmosphärendrucksensors)",
    "ECU-Kommunikationsfehler\nzwischen Mikrocomputern\n(SPI-Kommunikationsfehler\nbasierend auf der Fehlerdiagnose\ndes überwachenden\nMikrocomputers)",
    "Fehler im A/D-Wandler des\nECU-Mikrocomputers",
    "Anormaler Einspritzungs-Stopp-Pfad\nam ECU-Mikrocomputer-Fehler",
    "Kurzschluss an Vorglühlampe +B",
    "Kurzschluss an Störungsleuchte +B",
    "Kurzschluss an Anlasserrelais +B",
    "Kurzschluss Leuchte für\nhydraulischen Abfall +B",
    "Kurzschluss an gelber Warnleuchte\n+B",
    "Kurzschluss an Anzeigeleuchte der\nDrehzahländerung +B",
    "Kurzschluss an Warnleuchte der\nAbgastemperatur +B",
    "Kurzschluss an Warnleuchte der\nMotorkühlmitteltemperatur +B",
    "Kurzschluss Hupe +B",
    "Kurzschluss an roter\nMotorstoppleuchte +B",
    "Kurzschluss Isochrone Leuchte +B",
    "Kurzschluss an Kontrollleuchte der\nDPF-Regeneration +B",
    "Kurzschluss an\nDPF-Regenerationsverbotsleuchte\n+B",
    "Kurzschluss DPF-\nRegenerationsanforderungsleuchte\n+B",
    "EGR Systemfehler (Auslöser 1)",
    "EGR Systemfehler (Auslöser 2)",
    "ECU-System FS-Aktionsanweisung 2",
    "Fehler erkannter Wert NOx-Sensor\nvor SCR (O2-Konzentration)",
    "Kabelbruch des\nStarthilfe-Relais/VB-Kurzschluss",
    "GND-Kurzschluss Starthilferelais",
    "Verstopfung des Luftfilters",
    "Fehler Öl- und Wasserabscheider",
    "Fehler Kurbelwellensignal",
    "Kein Signal von der Kurbelwelle",
    "Fehler Nockenwellensignal",
    "Kein Signal von der Nockenwelle",
    "DPF übermäßige PM-Akkumulation\n(Methode C)",
    "DPF übermäßige PM-Akkumulation\n(Methode P)",
    "DPF-Regenerationsfehler (Ausfall\nder stationären Regeneration)",
    "DPF-Regenerationsfehler\n(Stationären Regeneration nicht in\nBetrieb)",
    "Kurzschluss an EGR-Motorspule",
    "Fehler EGR-Positionssensors",
    "EGR-Ventil klemmt",
    "EGR-Initialisierungsfehler",
    "Fehler\nEGR-Hochtemperatur-Thermistor",
    "Fehler\nEGR-Niedrigtemperatur-Thermistor",
    "Zeitüberschreitung CAN-Empfang\n(TSC1 (SA1))",
    "Zeitüberschreitung CAN-Empfang\n(TSC1 (SA2))",
    "Zeitüberschreitung beim\nCAN-Empfang (Y_ECR1)",
    "Zeitüberschreitung beim\nCAN-Empfang (Y_EC)",
    "Zeitüberschreitung beim\nCAN-Empfang (Y_RSS)",
    "Zeitüberschreitung CAN-Empfang\nvon EGR-Ventil",
    "EGR-Zielwert außerhalb des\nBereichs",
    "Zeitüberschreitung beim\nCAN-Empfang (EBC1)",
    "Zeitüberschreitung beim\nCAN-Empfang (Y_DRFIF)",
    "Fehler offene Stellung des doppelten\nBeschleunigungssensors",
    "Fehler geschlossene Stellung des\ndoppelten Beschleunigungssensors",
    "Lernen der Hochdruckpumpe nicht\ndurchgeführt",
    "ECU CPU Überwachungs-IC Fehler",
    "ECU CPU-Fehler",
    "Eingabefehler QR-Datenkorrektur",
    "Ladungsfehler im\nInjektor-Steuerkreis (niedrige\nLadung)",
    "Ladungsfehler im\nInjektor-Steuerkreis (Überladung)",
    "Prüfsummenfehler ECU-Flash-ROM",
    "Spannungsfehler ECU-Sensor 5 V\nSchaltkreis 1 (niedrig)",
    "Spannungsfehler ECU-Sensor 5 V\nSchaltkreis 1 (hoch)",
    "Spannungsfehler ECU-Sensor 5 V\nSchaltkreis 2 (niedrig)",
    "Spannungsfehler ECU-Sensor 5 V\nSchaltkreis 2 (hoch)",
    "QR-Daten nicht geschrieben",
    "QR-Datenfehler",
    "Keine Eingabe Kurbelwellen-\n/Nockenwellendrehzahlsensor\n(gleichzeitig)",
    "Zeitüberschreitung CAN-Empfang\nvon DCU",
    "VB-Kurzschluss Versorgungsmodul\n(Rücklaufventil) H-Seite",
    "GND-Kurzschluss\nVersorgungsmodul (Rücklaufventil)\nH-Seite",
    "VB-Kurzschluss\nSchlauchheizungsrelais/Tankheizung-\nsventil H-Seite",
    "GND-Kurzschluss\nSchlauchheizungsrelais/Tankheizung-\nsventil H-Seite",
    "VB-Kurzschluss Versorgungsmodul\n(Versorgungsmodulheizung) H-Seite ",
    "GND-Kurzschluss\nVersorgungsmodul\n(Versorgungsmodulheizung) H-Seite ",
    "Kabelbruch Versorgungsmodul\n(Versorgungsmodulheizung)",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Versorgungsmodulheizung)",
    "Zwangsabschaltung des\nSCR-Systems",
    "Spannungsfehler DCU-Versorgung\n(hoch 1)",
    "Spannungsfehler DCU-Versorgung\n(niedrig 2)",
    "Spannungsfehler DCU-Versorgung\n(hoch 2)",
    "Spannungsfehler DCU-Versorgung\n(niedrig 1)",
    "Hauptrelais klemmt",
    "Vorzeitiges Öffnen des Hauptrelais",
    "Zeitüberschreitung CAN-Empfang\nvon NOx-Sensor vor SCR",
    "Zeitüberschreitung CAN-Empfang\nvon NOx-Sensor hinter SCR",
    "Zeitüberschreitung CAN-Empfang\nvon ECU ",
    "Spannungsfehler\nDCU-Sensorversorgung",
    "DCU SPI-Kommunikationsfehler 1",
    "DCU SPI-Kommunikationsfehler 2",
    "Kurzschluss im Dosiermodul auf\nH/L-Seite",
    "Kabelbruch Dosiermodul",
    "VB-Kurzschluss Dosiermodul auf der\nH-Seite",
    "GND-Kurzschluss Dosiermodul",
    "Dosiermodulventil klemmt",
    "EEPROM-Speicher-Lesefehler",
    "EEPROM-Speicher-Schreibfehler",
    "VB-Kurzschluss\nSchlauchheizungsrelais L-Seite",
    "GND-Kurzschluss\nSchlauchheizungsrelais L-Seite",
    "Kabelbruch Schlauchheizungsrelais",
    "VB-Kurzschluss Versorgungsmodul\n(Versorgungsmodulheizung) L-Seite ",
    "VB-Kurzschluss Tankheizungsventil\nL-Seite",
    "NOx-Wert-Anstieg vor SCR",
    "Interner Kurzschluss NOx-Sensor\nvor SCR",
    "Interner Kabelbruch NOx-Sensor vor\nSCR",
    "NOx-Wert-Anstieg hinter SCR",
    "Interner Kurzschluss NOx-Sensor\nhinter SCR",
    "Interner Kabelbruch NOx-Sensor\nhinter SCR",
    "Nicht abgeschlossene Aufheizung\nNOx-Sensor vor SCR",
    "Nicht abgeschlossene Aufheizung\nNOx-Sensor hinter SCR",
    "VB-Kurzschluss Versorgungsmodul\n(Rücklaufventil) L-Seite",
    "GND-Kurzschluss\nVersorgungsmodul (Rücklaufventil)\nL-Seite",
    "Kabelbruch Versorgungsmodul\n(Rücklaufventil)",
    "SCR-System ineffiziente\nNOx-Reinigung",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Temperatursensor\nVersorgungsmodulheizung)",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Temperatursensor\nVersorgungsmodulheizung) bei\nKaltstartüberprüfung",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Temperatursensor\nVersorgungsmodulheizung)",
    "Fehler erkannter Wert\nVersorgungsmodul\n(Temperatursensor\nVersorgungsmodulheizung) bei\nKaltstartüberprüfung",
    "Falscher Wert empfangen für\nTemperaturangabe während des\nBetriebs des Versorgungsmoduls\n(Temperatursensor\nVersorgungsmodulheizung)",
    "Ungültiger Wert empfangen für\nTemperaturangabe während des\nBetriebs des Versorgungsmoduls\n(Temperatursensor\nVersorgungsmodulheizung)",
    "PWM-Zyklusfehler\nVersorgungsmodul (Pumpenmotor)\nTemperaturangabe",
    "PWM-Signalfehler\nVersorgungsmodul (Pumpenmotor)\nTemperaturangabe",
    "Falscher Wert empfangen für\nTemperaturangabe während des\nBetriebs des Versorgungsmoduls\n(Temperatursensor\nVersorgungsmodul)",
    "Ungültiger Wert empfangen für\nTemperaturangabe während des\nBetriebs des Versorgungsmoduls\n(Temperatursensor\nVersorgungsmodul)",
    "Versorgungsmodul (Pumpenmotor)\nstartet nicht zur Temperaturmessung",
    "Druckanstieg 1 Versorgungsmodul\n(Pumpenmotor)",
    "Druckminderungsfehler\nVersorgungsmodul (Pumpenmotor)",
    "Druckanstieg auf der Rücklaufseite\ndes Harnstoff-Wasser-Schlauchs",
    "Druckanstieg auf der Druckseite des\nHarnstoff-Wasser-Schlauchs",
    "Druckstabilitätsfehler\nVersorgungsmodul (Pumpenmotor)",
    "Ausfall Versorgungsmodul\n(Rücklaufventil)",
    "Harnstoff-Wasser-Rücksaugfehler\nam Versorgungsmodul",
    "Druckanstieg 2 Versorgungsmodul\n(Pumpenmotor)",
    "Druckabfall am Versorgungsmodul",
    "Harnstoff-Wasser-Druckanstieg am\nVersorgungsmodul",
    "Temperaturanstieg\nHarnstoff-Wasser-Tank",
    "Zeitüberschreitung beim\nCAN-Empfang (A1DEFI)",
    "Zeitüberschreitung beim\nCAN-Empfang (AT1T1I)",
    "SCR Systemfehler (Auslöser 1)",
    "SCR Systemfehler (Auslöser 2)",
    "ECU-System FS-Aktionsanweisung 1",
    "Schlüsselschalter-Kabelbruch",
    "Datenüberprüfungsfehler zwischen\nECU und DCU (Zeitüberschreitung\nder Verifizierung)"
	};
