
static const char *V_EngErrorMSG_ITA[308]={	
    "Errore di tensione sensore 2\nacceleratore (alta)",
    "Errore di tensione sensore 2\nacceleratore (bassa)",
    "Errore posizione aperta sensore\npedale",
    "Errore posizione chiusa sensore\npedale",
    "Errore di tensione sensore 3\nacceleratore (alta)",
    "Errore di tensione sensore 3\nacceleratore (bassa)",
    "Errore di tensione sensore posizione\nvalvola a farfalla di aspirazione (alta)",
    "Errore di tensione sensore posizione\nvalvola a farfalla di aspirazione\n(bassa)",
    "Errore di tensione sensore 1\nacceleratore (alta)",
    "Errore di tensione sensore 1\nacceleratore (bassa)",
    "Errore di tensione sensore pressione\nolio (alta)",
    "Errore di tensione sensore pressione\nolio (bassa)",
    "Calo di pressione olio",
    "Errore di tensione sensore pressione\nlato bassa pressione EGR (alta)",
    "Errore di tensione sensore pressione\nlato bassa pressione EGR (bassa)",
    "Anomalia valore di apprendimento\nsensore pressione lato bassa\npressione EGR",
    "Errore valore rilevato sensore\npressione lato bassa pressione EGR",
    "Errore di tensione sensore\ntemperatura collettore di aspirazione\n(alta)",
    "Errore di tensione sensore\ntemperatura collettore di aspirazione\n(bassa)",
    "Errore valore rilevato sensore\ntemperatura collettore di aspirazione",
    "Errore di tensione sensore pressione\natmosferica (alta)",
    "Errore di tensione sensore pressione\natmosferica (bassa)",
    "Errore caratteristiche sensore\npressione atmosferica",
    "Errore di tensione sensore\ntemperatura refrigerante motore\n(alta)",
    "Errore di tensione sensore\ntemperatura refrigerante motore\n(bassa)",
    "Aumento temperatura refrigerante\nmotore (surriscaldamento)",
    "Errore valore rilevato sensore\ntemperatura refrigerante motore",
    "Errore di tensione sensore pressione\ncondotto (alta)",
    "Errore di tensione sensore pressione\ncondotto (bassa)",
    "Aumento eccessivo pressione\ncondotto",
    "Errore scostamento pressione\ncondotto (bassa pressione condotto)",
    "Interruzione cablaggio interruttore di\ncarica",
    "Errore di carica",
    "Errore di tensione sensore\ntemperatura aria ambiente (alta)",
    "Errore di tensione sensore\ntemperatura aria ambiente (bassa)",
    "Errore valore rilevato sensore\ntemperatura aria ambiente",
    "Ricezione non valida valore\ntemperatura aria ambiente ECU",
    "Errore di tensione sensore\ntemperatura collettore di scarico\n(alta)",
    "Errore di tensione sensore\ntemperatura collettore di scarico\n(bassa)",
    "Errore valore rilevato sensore\ntemperatura collettore di scarico",
    "Errore di tensione sensore\ntemperatura carburante (alta)",
    "Errore di tensione sensore\ntemperatura carburante (bassa)",
    "Aumento temperatura carburante",
    "Velocità eccessiva",
    "Timeout ricezione CAN (VI)",
    "Errore dati ricevuti CAN (VI)",
    "Errore di tensione sensore\ntemperatura gas EGR (alta)",
    "Errore di tensione sensore\ntemperatura gas EGR (bassa)",
    "Errore valore rilevato sensore\ntemperatura gas EGR",
    "Errore di verifica dati tra ECU e DCU\n(mancata corrispondenza modello\nmotore)",
    "Errore di verifica dati tra ECU e DCU\n(mancata corrispondenza N. di\nmatricola)",
    "Errore EEPROM",
    "Cortocircuito VB lato H/L valvola di\ncomando aspirazione (valvola\nproporzionale magnetica)",
    "Cortocircuito/interruzione cablaggio\nGND lato H valvola di comando\naspirazione (valvola proporzionale\nmagnetica)",
    "Errore circuito di comando\n(inceppamento valvola di comando\naspirazione)",
    "Interruzione cablaggio specifico\niniettore cilindro N. 1",
    "Cortocircuito tra terminali COM e\nTWV bobina iniettore cilindro N. 1",
    "Circuito aperto MOS scarica iniettore\ncilindro N. 1",
    "Interruzione cablaggio specifico\niniettore cilindro N. 2",
    "Cortocircuito tra terminali COM e\nTWV bobina iniettore cilindro N. 2",
    "Circuito aperto MOS scarica iniettore\ncilindro N. 2",
    "Interruzione cablaggio specifico\niniettore cilindro N. 3",
    "Cortocircuito tra terminali COM e\nTWV bobina iniettore cilindro N. 3",
    "Circuito aperto MOS scarica iniettore\ncilindro N. 3",
    "Interruzione cablaggio specifico\niniettore cilindro N. 4",
    "Cortocircuito tra terminali COM e\nTWV bobina iniettore cilindro N. 4",
    "Circuito aperto MOS scarica iniettore\ncilindro N. 4",
    "Errore di tensione sensore pressione\nlato alta pressione EGR (alta)",
    "Errore di tensione sensore pressione\nlato alta pressione EGR (bassa)",
    "Anomalia valore di apprendimento\nsensore pressione lato alta\npressione EGR",
    "Errore valore rilevato sensore\npressione lato alta pressione EGR",
    "Errore di protezione pompa ad alta\npressione",
    "Errore di sostituzione pompa ad alta\npressione",
    "Spegnimento senza autoritenuta relè\nprincipale",
    "Basso livello serbatoio urea acquosa\n(invito 1)",
    "Basso livello serbatoio urea acquosa\n(invito 2)",
    "Interruzione cablaggio sensore livello\nserbatoio urea acquosa",
    "Cortocircuito sensore livello\nserbatoio urea acquosa (AT1T1I)",
    "Errore controller interno sensore\nlivello serbatoio urea acquosa\n(AT1T1I)",
    "Errore valore rilevato sensore livello\nserbatoio urea acquosa",
    "Interruzione cablaggio bobina motore\nEGR",
    "Errore feedback EGR",
    "Errore dati ECM EGR",
    "Errore di tensione EGR\n(sovratensione)",
    "Errore di tensione EGR (bassa)",
    "Cortocircuito +B banco iniettori 1",
    "Cortocircuito GND banco iniettori 1 ",
    "Interruzione cablaggio banco iniettori\n1",
    "Errore clock interno VDIC3 IC-1\ndriver iniettori",
    "Errore di comunicazione tra VDIC3 e\nmicrocomputer IC-1 driver iniettori",
    "Cortocircuito +B banco iniettori 2",
    "Cortocircuito GND banco iniettori 2 ",
    "Interruzione cablaggio banco iniettori\n2",
    "Errore clock interno VDIC3 IC-2\ndriver iniettori",
    "Errore di comunicazione tra VDIC3 e\nmicrocomputer IC-2 driver iniettori",
    "Interruzione cablaggio circuito di\ncomando valvola a farfalla di\naspirazione",
    "Cortocircuito VB/GND circuito di\ncomando valvola a farfalla di\naspirazione ",
    "Errore scostamento circuito di\ncomando valvola a farfalla di\naspirazione",
    "Errore servizio di comando circuito di\ncomando valvola a farfalla di\naspirazione",
    "Aumento temperatura sensore\ntemperatura serbatoio urea\nacquosa/controller sensore livello\nserbatoio urea acquosa (AT1T1I)",
    "Interruzione cablaggio circuito\ninterno sensore temperatura\nserbatoio urea acquosa (AT1T1I)",
    "Cortocircuito circuito interno sensore\ntemperatura serbatoio urea acquosa\n(AT1T1I)",
    "Guasto interno controller sensore\ntemperatura serbatoio urea acquosa\n(AT1T1I)",
    "Aumento temperatura serbatoio urea\nacquosa",
    "Errore valore rilevato sensore\ntemperatura serbatoio urea acquosa\n(errore limite superiore)",
    "Errore valore rilevato sensore\ntemperatura serbatoio urea acquosa\n(errore limite inferiore)",
    "Errore valore rilevato sensore NOx a\nmonte SCR (errore limite superiore)",
    "Errore valore rilevato sensore NOx a\nmonte SCR (errore limite inferiore)",
    "Errore di tensione sensore\ntemperatura ingresso DPF (alta)",
    "Errore di tensione sensore\ntemperatura ingresso DPF (bassa)",
    "Errore valore rilevato sensore\ntemperatura ingresso DPF",
    "Aumento temperatura ingresso DPF",
    "Errore di tensione sensore\ntemperatura intermedia DPF (alta)",
    "Errore di tensione sensore\ntemperatura intermedia DPF (bassa)",
    "Errore valore rilevato sensore\ntemperatura intermedia DPF",
    "Calo temperatura intermedia DPF",
    "Aumento temperatura intermedia\nDPF (guasto post iniezione)",
    "Errore di tensione sensore pressione\ndifferenziale DPF (alta)",
    "Errore di tensione sensore pressione\ndifferenziale DPF (bassa)",
    "Anomalia valore di apprendimento\nsensore pressione differenziale DPF",
    "Aumento pressione differenziale\nDPF",
    "Aumento temperatura controller\nsensore qualità urea\nacquosa/sensore temperatura\nserbatoio urea acquosa (A1DEFI)",
    "Interruzione cablaggio circuito\ninterno sensore temperatura\nserbatoio urea acquosa (A1DEFI)",
    "Cortocircuito circuito interno sensore\ntemperatura serbatoio urea acquosa\n(A1DEFI)",
    "Guasto interno controller sensore\ntemperatura serbatoio urea acquosa\n(A1DEFI)",
    "Interruzione cablaggio circuito\ninterno sensore qualità urea acquosa",
    "Cortocircuito circuito interno sensore\nqualità urea acquosa",
    "Guasto interno controller sensore\nqualità urea acquosa",
    "Errore concentrazione sensore\nqualità urea acquosa (piccolo\nscostamento)",
    "Errore concentrazione sensore\nqualità urea acquosa (grande\nscostamento)",
    "Contaminazione serbatoio urea\nacquosa",
    "Errore di tensione sensore pressione\nlato alta pressione DPF (alta)",
    "Errore di tensione sensore pressione\nlato alta pressione DPF (bassa)",
    "Errore valore rilevato sensore\npressione lato alta pressione DPF",
    "Standby rigenerazione parcheggiata\nDPF",
    "Guasto rigenerazione DPF (guasto\nrigenerazione recovery)",
    "Inibizione rigenerazione recovery\nDPF",
    "Modalità backup DPF",
    "Richiesta pulizia cenere DPF 1",
    "Richiesta pulizia cenere DPF 2",
    "Errore di tensione sensore pressione\npompa modulo alimentazione (alta)",
    "Errore di tensione sensore pressione\npompa modulo alimentazione\n(bassa)",
    "Errore valore rilevato sensore\npressione pompa modulo\nalimentazione (errore limite\nsuperiore)",
    "Errore valore rilevato sensore\npressione pompa modulo\nalimentazione (errore limite inferiore)",
    "Cortocircuito VB lato L riscaldatore\ntubo urea acquosa (pressione)",
    "Cortocircuito GND lato L riscaldatore\ntubo urea acquosa (pressione)",
    "Interruzione cablaggio riscaldatore\ntubo urea acquosa (pressione)",
    "Cortocircuito VB lato L riscaldatore\ntubo urea acquosa (riflusso)",
    "Cortocircuito GND lato L riscaldatore\ntubo urea acquosa (riflusso)",
    "Interruzione cablaggio riscaldatore\ntubo urea acquosa (riflusso)",
    "Cortocircuito VB lato L riscaldatore\ntubo urea acquosa (aspirazione)",
    "Cortocircuito GND lato L riscaldatore\ntubo urea acquosa (aspirazione)",
    "Interruzione cablaggio riscaldatore\ntubo urea acquosa (aspirazione)",
    "Errore di tensione sensore\ntemperatura a monte catalizzatore\nSCR (alta)",
    "Errore di tensione sensore\ntemperatura a monte catalizzatore\nSCR (bassa)",
    "Aumento temperatura a monte\ncatalizzatore SCR",
    "Errore valore rilevato sensore\ntemperatura a monte catalizzatore\nSCR (errore limite superiore)",
    "Errore valore rilevato sensore\ntemperatura a monte catalizzatore\nSCR (errore limite inferiore)",
    "Errore valore rilevato al controllo\navviamento a freddo sensore\ntemperatura a monte catalizzatore\nSCR",
    "Cortocircuito VB cablaggio segnale\nPWM modulo alimentazione (motore\npompa)",
    "Cortocircuito GND cablaggio segnale\nPWM modulo alimentazione (motore\npompa)",
    "Interruzione cablaggio segnale PWM\nmodulo alimentazione (motore\npompa)",
    "Errore comando modulo\nalimentazione (motore pompa) 1",
    "Errore comando modulo\nalimentazione (motore pompa) 2",
    "Errore validità rimozione materiale\nbase DPF/sensore pressione\ndifferenziale DPF",
    "Cortocircuito GND lato L valvola\nriscaldamento serbatoio",
    "Interruzione cablaggio valvola\nriscaldamento serbatoio",
    "Errore di comunicazione ECU tra\nmicrocomputer (errore di\ncomunicazione MSC)",
    "Errore di comunicazione ECU tra\nmicrocomputer (errore di\ncomunicazione SPI basato su\ndiagnosi di errore sensore pressione\natmosferica SPI)",
    "Errore di comunicazione ECU tra\nmicrocomputer (errore di\ncomunicazione SPI basato su\ndiagnosi di errore microcomputer di\nmonitoraggio)",
    "Errore convertitore A/D\nmicrocomputer ECU",
    "Anomalia percorso arresto iniezione\nsu errore microcomputer ECU",
    "Cortocircuito +B spia\npreriscaldamento",
    "Cortocircuito +B spia guasto",
    "Cortocircuito +B relè avviamento",
    "Cortocircuito +B calo idraulico",
    "Cortocircuito +B spia avvertenza\nambra",
    "Cortocircuito +B spia display cambio\nvelocità",
    "Cortocircuito +B spia allarme\ntemperatura scarico",
    "Cortocircuito +B spia allarme\ntemperatura refrigerante motore",
    "Cortocircuito +B cicalino",
    "Cortocircuito +B spia arresto motore\nrossa",
    "Cortocircuito +B spia isocrona",
    "Cortocircuito +B spia approvazione\nrigenerazione DPF",
    "Cortocircuito +B spia divieto\nrigenerazione DPF",
    "Cortocircuito +B spia richiesta\nrigenerazione DPF",
    "Errore sistema EGR (invito 1)",
    "Errore sistema EGR (invito 2)",
    "Istruzione azione FS sistema ECU 2",
    "Errore valore rilevato sensore NOx a\nmonte SCR (concentrazione O2)",
    "Interruzione cablaggio/cortocircuito\nVB relè partenza assistita",
    "Cortocircuito GND relè partenza\nassistita",
    "Intasamento del filtro dell’aria",
    "Errore separatore acqua e olio",
    "Errore segnale albero motore",
    "Nessun segnale da albero motore",
    "Errore segnale albero a camme",
    "Nessun segnale da albero a camme",
    "Accumulo PM eccessivo DPF\n(metodo C)",
    "Accumulo PM eccessivo DPF\n(metodo P)",
    "Errore rigenerazione DPF (guasto\nrigenerazione parcheggiata)",
    "Errore rigenerazione DPF\n(rigenerazione parcheggiata non\nazionata)",
    "Cortocircuito bobina motore EGR",
    "Errore sensore posizione EGR",
    "Inceppamento valvola EGR",
    "Errore inizializzazione EGR",
    "Errore termistore alta temperatura\nEGR",
    "Errore termistore bassa temperatura\nEGR",
    "Timeout ricezione CAN (TSC1 (SA1))",
    "Timeout ricezione CAN (TSC1 (SA2))",
    "Timeout ricezione CAN (Y_ECR1)",
    "Timeout ricezione CAN (Y_EC)",
    "Timeout ricezione CAN (Y_RSS)",
    "Timeout ricezione CAN da valvola\nEGR",
    "Valore target EGR fuori intervallo",
    "Timeout ricezione CAN (EBC1)",
    "Timeout ricezione CAN (Y_DRFIF)",
    "Errore posizione aperta sensore\nacceleratore doppio",
    "Errore posizione chiusa sensore\nacceleratore doppio",
    "Apprendimento pompa ad alta\npressione non eseguito",
    "Errore IC monitoraggio CPU ECU",
    "Errore CPU ECU",
    "Errore di immissione correzione dati\nQR",
    "Errore di carica circuito comando\niniettori (carica bassa)",
    "Errore di carica circuito comando\niniettori (sovraccarico)",
    "Errore checksum ROM flash ECU",
    "Errore di tensione sensore circuito 1\n5V sensore ECU (bassa)",
    "Errore di tensione sensore circuito 1\n5V sensore ECU (alta)",
    "Errore di tensione sensore circuito 2\n5V sensore ECU (bassa)",
    "Errore di tensione sensore circuito 2\n5V sensore ECU (alta)",
    "Dati QR non scritti",
    "Errore dati QR",
    "Nessun ingresso sensore velocità\nalbero motore/sensore velocità\nalbero a camme (simultaneo)",
    "Timeout ricezione CAN da DCU",
    "Cortocircuito VB lato H modulo\nalimentazione (valvola inversione)",
    "Cortocircuito GND lato H modulo\nalimentazione (valvola inversione)",
    "Cortocircuito VB lato H relè\nriscaldatore tubo/valvola\nriscaldamento serbatoio",
    "Cortocircuito GND lato H relè\nriscaldatore tubo/valvola\nriscaldamento serbatoio",
    "Cortocircuito VB lato H modulo\nalimentazione (riscaldatore modulo\nalimentazione) ",
    "Cortocircuito GND lato H modulo\nalimentazione (riscaldatore modulo\nalimentazione) ",
    "Interruzione cablaggio modulo\nalimentazione (riscaldatore modulo\nalimentazione)",
    "Errore valore rilevato modulo\nalimentazione (riscaldatore modulo\nalimentazione)",
    "Interruzione forzata sistema SCR",
    "Errore di tensione alimentazione\nDCU (alta 1)",
    "Errore di tensione alimentazione\nDCU (bassa 2)",
    "Errore di tensione alimentazione\nDCU (alta 2)",
    "Errore di tensione alimentazione\nDCU (bassa 1)",
    "Inceppamento relè principale",
    "Apertura anticipata relè principale",
    "Errore ricezione CAN da sensore\nNOx a monte SCR",
    "Errore ricezione CAN da sensore\nNOx a valle SCR",
    "Timeout ricezione CAN da ECU ",
    "Errore di tensione alimentazione\nsensore DCU",
    "Errore di comunicazione SPI DCU 1",
    "Errore di comunicazione SPI DCU 2",
    "Cortocircuito lato H/L modulo\ndosaggio",
    "Interruzione cablaggio modulo\ndosaggio",
    "Cortocircuito VB lato H modulo\ndosaggio",
    "Cortocircuito GND modulo dosaggio",
    "Inceppamento valvola modulo\ndosaggio",
    "Errore di lettura memoria EEPROM",
    "Errore di scrittura memoria EEPROM",
    "Cortocircuito VB lato L relè\nriscaldatore tubo",
    "Cortocircuito GND lato L relè\nriscaldatore tubo",
    "Interruzione cablaggio relè\nriscaldatore tubo",
    "Cortocircuito VB lato L modulo\nalimentazione (riscaldatore modulo\nalimentazione) ",
    "Cortocircuito VB lato L valvola\nriscaldamento serbatoio",
    "Aumento valore NOx a monte SCR",
    "Cortocircuito circuito interno sensore\nNOx a monte SCR",
    "Interruzione cablaggio circuito\ninterno sensore NOx a monte SCR",
    "Aumento valore NOx a valle SCR",
    "Cortocircuito circuito interno sensore\nNOx a valle SCR",
    "Interruzione cablaggio circuito\ninterno sensore NOx a valle SCR",
    "Riscaldamento incompleto sensore\nNOx a monte SCR",
    "Riscaldamento incompleto sensore\nNOx a valle SCR",
    "Cortocircuito VB lato L modulo\nalimentazione (valvola inversione)",
    "Cortocircuito GND lato L modulo\nalimentazione (valvola inversione)",
    "Interruzione cablaggio modulo\nalimentazione (valvola inversione)",
    "Pulizia NOx inefficiente sistema SCR",
    "Errore valore rilevato modulo\nalimentazione (sensore temperatura\nriscaldatore modulo alimentazione)",
    "Errore valore rilevato al controllo\navviamento a freddo modulo\nalimentazione (sensore temperatura\nriscaldatore modulo alimentazione)",
    "Errore valore rilevato modulo\nalimentazione (sensore temperatura\nmodulo alimentazione)",
    "Errore valore rilevato al controllo\navviamento a freddo modulo\nalimentazione (sensore temperatura\nmodulo alimentazione)",
    "Ricevuto valore errato modulo\nalimentazione (sensore temperatura\nriscaldatore modulo alimentazione)\nper valore servizio informazioni\ntemperatura",
    "Ricevuto valore non valido modulo\nalimentazione (sensore temperatura\nriscaldatore modulo alimentazione)\nper valore servizio informazioni\ntemperatura",
    "Errore ciclo PWM informazioni\ntemperatura modulo alimentazione\n(motore pompa)",
    "Errore segnale PWM informazioni\ntemperatura modulo alimentazione\n(motore pompa)",
    "Ricevuto valore errato modulo\nalimentazione (sensore temperatura\nmodulo alimentazione) per valore\nservizio informazioni temperatura",
    "Ricevuto valore non valido modulo\nalimentazione (sensore temperatura\nmodulo alimentazione) per valore\nservizio informazioni temperatura",
    "Mancato avvio modulo alimentazione\n(motore pompa) per misurare\ntemperatura",
    "Aumento pressione modulo\nalimentazione (motore pompa) 1",
    "Errore riduzione pressione modulo\nalimentazione (motore pompa)",
    "Aumento pressione lato riflusso tubo\nurea acquosa",
    "Aumento pressione lato pressione\ntubo urea acquosa",
    "Errore di stabilità pressione modulo\nalimentazione (motore pompa)",
    "Guasto modulo alimentazione\n(valvola inversione)",
    "Errore risucchio urea acquosa\nmodulo alimentazione",
    "Aumento pressione modulo\nalimentazione (motore pompa) 2",
    "Calo pressione modulo\nalimentazione",
    "Aumento pressione urea acquosa\nmodulo alimentazione",
    "Aumento temperatura serbatoio urea\nacquosa",
    "Timeout ricezione CAN (A1DEFI)",
    "Timeout ricezione CAN (AT1T1I)",
    "Errore sistema SCR (invito 1)",
    "Errore sistema SCR (invito 2)",
    "Istruzione azione FS sistema ECU 1",
    "Interruzione cablaggio interruttore di\navviamento a chiave",
    "Errore di verifica dati tra ECU e DCU\n(timeout verifica)"
	};
