
																
static const char *H_EngErrorMSG_ENG[308]={	
    "Accelerator sensor 2 voltage\nerror (high)",
    "Accelerator sensor 2 voltage\nerror (low)",
    "Foot pedal sensor open\nposition error",
    "Foot pedal sensor closed\nposition error",
    "Accelerator sensor 3 voltage\nerror (high)",
    "Accelerator sensor 3 voltage\nerror (low)",
    "Intake throttle position sensor\nvoltage error (high)",
    "Intake throttle position sensor\nvoltage error (low)",
    "Accelerator sensor 1 voltage\nerror (high)",
    "Accelerator sensor 1 voltage\nerror (low)",
    "Oil pressure sensor voltage\nerror (high)",
    "Oil pressure sensor voltage\nerror (low)",
    "Oil pressure drop",
    "EGR low-pressure side pressure\nsensor voltage error (high)",
    "EGR low-pressure side pressure\nsensor voltage error (low)",
    "EGR low-pressure side pressure\nsensor abnormal learning value",
    "EGR low-pressure side pressure\nsensor detected value error",
    "Intake manifold temperature\nsensor voltage error (high)",
    "Intake manifold temperature\nsensor voltage error (low)",
    "Intake manifold temperature\nsensor detected value error",
    "Atmospheric pressure sensor\nvoltage error (high)",
    "Atmospheric pressure sensor\nvoltage error (low)",
    "Atmospheric pressure sensor\ncharacteristic error",
    "Engine coolant temperature\nsensor voltage error (high)",
    "Engine coolant temperature\nsensor voltage error (low)",
    "Engine coolant temperature rise\n(overheat)",
    "Engine coolant temperature\nsensor detected value error",
    "Rail pressure sensor voltage\nerror (high)",
    "Rail pressure sensor voltage\nerror (low)",
    "Excessive rail pressure rise",
    "Rail pressure deviation error\n(low rail pressure)",
    "Charge switch wiring break",
    "Charge error",
    "Ambient air temperature sensor\nvoltage error (high)",
    "Ambient air temperature sensor\nvoltage error (low)",
    "Ambient air temperature sensor\ndetected value error",
    "ECU invalid ambient air\ntemperature value reception",
    "Exhaust manifold temperature\nsensor voltage error (high)",
    "Exhaust manifold temperature\nsensor voltage error (low)",
    "Exhaust manifold temperature\nsensor detected value error",
    "Fuel temperature sensor\nvoltage error (high)",
    "Fuel temperature sensor\nvoltage error (low)",
    "Fuel temperature rise",
    "Excessive speed",
    "CAN reception timeout (VI)",
    "CAN received data error (VI)",
    "EGR gas temperature sensor\nvoltage error (high)",
    "EGR gas temperature sensor\nvoltage error (low)",
    "EGR gas temperature sensor\ndetected value error",
    "Data verification error between\nECU and DCU (engine model\nmismatch)",
    "Data verification error between\nECU and DCU (serial No.\nmismatch)",
    "EEPROM error",
    "Suction control valve (magnetic\nproportional valve) H/L-side VB\nshort circuit",
    "Suction control valve (magnetic\nproportional valve) H-side GND\nshort circuit/wiring break",
    "Drive circuit error (suction\ncontrol valve sticking)",
    "No. 1 cylinder injector-specific\nwiring break",
    "No. 1 cylinder injector coil\nshort circuit between COM and\nTWV terminals",
    "No. 1 cylinder injector\ndischarge MOS open circuit",
    "No. 2 cylinder injector-specific\nwiring break",
    "No. 2 cylinder injector coil\nshort circuit between COM and\nTWV terminals",
    "No. 2 cylinder injector\ndischarge MOS open circuit",
    "No. 3 cylinder injector-specific\nwiring break",
    "No. 3 cylinder injector coil\nshort circuit between COM and\nTWV terminals",
    "No. 3 cylinder injector\ndischarge MOS open circuit",
    "No. 4 cylinder injector-specific\nwiring break",
    "No. 4 cylinder injector coil\nshort circuit between COM and\nTWV terminals",
    "No. 4 cylinder injector\ndischarge MOS open circuit",
    "EGR high-pressure side\npressure sensor voltage error\n(high)",
    "EGR high-pressure side\npressure sensor voltage error\n(low)",
    "EGR high-pressure side\npressure sensor abnormal\nlearning value",
    "EGR high-pressure side\npressure sensor detected value\nerror",
    "High-pressure pump protection\nerror",
    "High-pressure pump\nreplacement error",
    "Power off without main relay\nself-holding",
    "Low aqueous urea tank level\n(inducement 1)",
    "Low aqueous urea tank level\n(inducement 2)",
    "Aqueous urea tank level sensor\nwiring break",
    "Aqueous urea tank level sensor\n(AT1T1I) short circuit",
    "Aqueous urea tank level sensor\n(AT1T1I) controller internal error",
    "Aqueous urea tank level sensor\ndetected value error",
    "EGR motor coil wiring break",
    "EGR feedback error",
    "EGR ECM data error",
    "EGR voltage error (overvoltage)",
    "EGR voltage error (low)",
    "Injector bank 1 +B short circuit",
    "Injector bank 1 GND short\ncircuit ",
    "Injector bank 1 wiring break",
    "Injector driver IC-1 VDIC3\ninternal clock error",
    "Injector driver IC-1\ncommunication error between\nVDIC3 and microcomputer",
    "Injector bank 2 +B short circuit",
    "Injector bank 2 GND short\ncircuit ",
    "Injector bank 2 wiring break",
    "Injector driver IC-2 VDIC3\ninternal clock error",
    "Injector driver IC-2\ncommunication error between\nVDIC3 and microcomputer",
    "Intake throttle drive circuit\nwiring break",
    "Intake throttle drive circuit\nVB/GND short circuit ",
    "Intake throttle drive circuit\ndeviation error",
    "Intake throttle drive circuit drive\nduty error",
    "Aqueous urea tank temperature\nsensor/Aqueous urea tank level\nsensor (AT1T1I) controller\ntemperature rise",
    "Aqueous urea tank temperature\nsensor (AT1T1I) internal circuit\nwiring break",
    "Aqueous urea tank temperature\nsensor (AT1T1I) internal circuit\nshort circuit",
    "Aqueous urea tank temperature\nsensor (AT1T1I) controller\ninternal failure",
    "Aqueous urea tank temperature\nrise",
    "Aqueous urea tank temperature\nsensor detected value error\n(upper limit error)",
    "Aqueous urea tank temperature\nsensor detected value error\n(lower limit error)",
    "SCR upstream NOx sensor\ndetected value error (upper\nlimit error)",
    "SCR upstream NOx sensor\ndetected value error (lower limit\nerror)",
    "DPF inlet temperature sensor\nvoltage error (high)",
    "DPF inlet temperature sensor\nvoltage error (low)",
    "DPF inlet temperature sensor\ndetected value error",
    "DPF inlet temperature rise",
    "DPF intermediate temperature\nsensor voltage error (high)",
    "DPF intermediate temperature\nsensor voltage error (low)",
    "DPF intermediate temperature\nsensor detected value error",
    "DPF intermediate temperature\ndrop",
    "DPF intermediate temperature\nrise (post-injection failure)",
    "DPF differential pressure sensor\nvoltage error (high)",
    "DPF differential pressure sensor\nvoltage error (low)",
    "DPF differential pressure sensor\nabnormal learning value",
    "DPF differential pressure rise",
    "Aqueous urea quality\nsensor/Aqueous urea tank\ntemperature sensor (A1DEFI)\ncontroller temperature rise",
    "Aqueous urea tank temperature\nsensor (A1DEFI) internal circuit\nwiring break",
    "Aqueous urea tank temperature\nsensor (A1DEFI) internal circuit\nshort circuit",
    "Aqueous urea tank temperature\nsensor (A1DEFI) controller\ninternal failure",
    "Aqueous urea quality sensor\ninternal circuit wiring break",
    "Aqueous urea quality sensor\ninternal circuit short circuit",
    "Aqueous urea quality sensor\ncontroller internal failure",
    "Aqueous urea quality sensor\nconcentration error (small\ndeviation)",
    "Aqueous urea quality sensor\nconcentration error (large\ndeviation)",
    "Aqueous urea tank\ncontamination",
    "DPF high-pressure side pressure\nsensor voltage error (high)",
    "DPF high-pressure side pressure\nsensor voltage error (low)",
    "DPF high-pressure side pressure\nsensor detected value error",
    "DPF stationary regeneration\nstandby",
    "DPF regeneration failure\n(recovery regeneration failure)",
    "DPF recovery regeneration\ninhibited",
    "DPF backup mode",
    "DPF ash cleaning request 1",
    "DPF ash cleaning request 2",
    "Supply module pump pressure\nsensor voltage error (high)",
    "Supply module pump pressure\nsensor voltage error (low)",
    "Supply module pump pressure\nsensor detected value error\n(upper limit error)",
    "Supply module pump pressure\nsensor detected value error\n(lower limit error)",
    "Aqueous urea hose heater\n(pressure) L-side VB short\ncircuit",
    "Aqueous urea hose heater\n(pressure) L-side GND short\ncircuit",
    "Aqueous urea hose heater\n(pressure) wiring break",
    "Aqueous urea hose heater\n(backflow) L-side VB short\ncircuit",
    "Aqueous urea hose heater\n(backflow) L-side GND short\ncircuit",
    "Aqueous urea hose heater\n(backflow) wiring break",
    "Aqueous urea hose heater\n(suction) L-side VB short circuit",
    "Aqueous urea hose heater\n(suction) L-side GND short\ncircuit",
    "Aqueous urea hose heater\n(suction) wiring break",
    "SCR catalyst upstream\ntemperature sensor voltage\nerror (high)",
    "SCR catalyst upstream\ntemperature sensor voltage\nerror (low)",
    "SCR catalyst upstream\ntemperature rise",
    "SCR catalyst upstream\ntemperature sensor detected\nvalue error (upper limit error)",
    "SCR catalyst upstream\ntemperature sensor detected\nvalue error (lower limit error)",
    "SCR catalyst upstream\ntemperature sensor detected\nvalue error at cold start check",
    "Supply module (pump motor)\nPWM signal wiring VB short\ncircuit",
    "Supply module (pump motor)\nPWM signal wiring GND short\ncircuit",
    "Supply module (pump motor)\nPWM signal wiring break",
    "Supply module (pump motor)\ndrive error 1",
    "Supply module (pump motor)\ndrive error 2",
    "DPF base material removal/DPF\ndifferential pressure sensor\nvalidity error",
    "Tank heating valve L-side GND\nshort circuit",
    "Tank heating valve wiring break",
    "ECU communication error\nbetween microcomputers (MSC\ncommunication error)",
    "ECU communication error\nbetween microcomputers (SPI\ncommunication error based on\natmospheric pressure sensor\nerror diagnosis)",
    "ECU communication error\nbetween microcomputers (SPI\ncommunication error based on\nmonitoring microcomputer\nerror diagnosis)",
    "ECU microcomputer A/D\nconverter error",
    "Abnormal injection stop path at\nECU microcomputer error",
    "Preheating lamp +B short\ncircuit",
    "Fault lamp +B short circuit",
    "Starter relay +B short circuit",
    "Hydraulic drop lamp +B short\ncircuit",
    "Amber warning lamp +B short\ncircuit",
    "Speed change display lamp +B\nshort circuit",
    "Exhaust temperature alarm\nlamp +B short circuit",
    "Engine coolant temperature\nalarm lamp +B short circuit",
    "Buzzer +B short circuit",
    "Red engine stop lamp +B short\ncircuit",
    "Isochronous lamp +B short\ncircuit",
    "DPF regeneration approval\nlamp +B short circuit",
    "DPF regeneration prohibition\nlamp +B short circuit",
    "DPF regeneration request lamp\n+B short circuit",
    "EGR system error (inducement\n1)",
    "EGR system error (inducement\n2)",
    "ECU system FS action\ninstruction 2",
    "SCR upstream NOx sensor\ndetected value error (O2\nconcentration)",
    "Starting aid relay wiring\nbreak/VB short circuit",
    "Starting aid relay GND short\ncircuit",
    "Air cleaner clogging",
    "Oil and water separator error",
    "Crankshaft signal error",
    "No signal from crankshaft",
    "Camshaft signal error",
    "No signal from camshaft",
    "DPF excessive PM accumulation\n(method C)",
    "DPF excessive PM accumulation\n(method P)",
    "DPF regeneration error\n(stationary regeneration failure)",
    "DPF regeneration error\n(stationary regeneration not\noperated)",
    "EGR motor coil short circuit",
    "EGR position sensor error",
    "EGR valve sticking",
    "EGR initialization error",
    "EGR high-temperature\nthermistor error",
    "EGR low-temperature\nthermistor error",
    "CAN reception timeout (TSC1\n(SA1))",
    "CAN reception timeout (TSC1\n(SA2))",
    "CAN reception timeout\n(Y_ECR1)",
    "CAN reception timeout (Y_EC)",
    "CAN reception timeout (Y_RSS)",
    "CAN reception timeout from\nEGR valve",
    "EGR target value out of range",
    "CAN reception timeout (EBC1)",
    "CAN reception timeout\n(Y_DRFIF)",
    "Dual accelerator sensor open\nposition error",
    "Dual accelerator sensor closed\nposition error",
    "High-pressure pump learning\nnot performed",
    "ECU CPU monitoring IC error",
    "ECU CPU error",
    "QR data correction input error",
    "Injector drive circuit charge\nerror (low charge)",
    "Injector drive circuit charge\nerror (overcharge)",
    "ECU flash ROM checksum error",
    "ECU sensor 5V circuit 1 voltage\nerror (low)",
    "ECU sensor 5V circuit 1 voltage\nerror (high)",
    "ECU sensor 5V circuit 2 voltage\nerror (low)",
    "ECU sensor 5V circuit 2 voltage\nerror (high)",
    "QR data not written",
    "QR data error",
    "No crankshaft speed\nsensor/camshaft speed sensor\ninput (simultaneous)",
    "CAN reception timeout from\nDCU",
    "Supply module (reverting valve)\nH-side VB short circuit",
    "Supply module (reverting valve)\nH-side GND short circuit",
    "Hose heater relay/Tank heating\nvalve H-side VB short circuit",
    "Hose heater relay/Tank heating\nvalve H-side GND short circuit",
    "Supply module (supply module\nheater) H-side VB short circuit ",
    "Supply module (supply module\nheater) H-side GND short\ncircuit ",
    "Supply module (supply module\nheater) wiring break",
    "Supply module (supply module\nheater) detected value error",
    "SCR system forced termination",
    "DCU supply voltage error (high\n1)",
    "DCU supply voltage error (low\n2)",
    "DCU supply voltage error (high\n2)",
    "DCU supply voltage error (low\n1)",
    "Main relay sticking",
    "Main relay early opening",
    "CAN reception timeout from\nSCR upstream NOx sensor",
    "CAN reception timeout from\nSCR downstream NOx sensor",
    "CAN reception timeout from\nECU ",
    "DCU sensor supply voltage\nerror",
    "DCU SPI communication error 1",
    "DCU SPI communication error 2",
    "Dosing module H/L-side short\ncircuit",
    "Dosing module wiring break",
    "Dosing module H-side VB short\ncircuit",
    "Dosing module GND short\ncircuit",
    "Dosing module valve sticking",
    "EEPROM memory reading error",
    "EEPROM memory writing error",
    "Hose heater relay L-side VB\nshort circuit",
    "Hose heater relay L-side GND\nshort circuit",
    "Hose heater relay wiring break",
    "Supply module (supply module\nheater) L-side VB short circuit ",
    "Tank heating valve L-side VB\nshort circuit",
    "SCR upstream NOx value rise",
    "SCR upstream NOx sensor\ninternal circuit short circuit",
    "SCR upstream NOx sensor\ninternal circuit wiring break",
    "SCR downstream NOx value\nrise",
    "SCR downstream NOx sensor\ninternal circuit short circuit",
    "SCR downstream NOx sensor\ninternal circuit wiring break",
    "SCR upstream NOx sensor\nincomplete heating",
    "SCR downstream NOx sensor\nincomplete heating",
    "Supply module (reverting valve)\nL-side VB short circuit",
    "Supply module (reverting valve)\nL-side GND short circuit",
    "Supply module (reverting valve)\nwiring break",
    "SCR system inefficient NOx\ncleaning",
    "Supply module (supply module\nheater temperature sensor)\ndetected value error",
    "Supply module (supply module\nheater temperature sensor)\ndetected value error at cold\nstart check",
    "Supply module (supply module\ntemperature sensor) detected\nvalue error",
    "Supply module (supply module\ntemperature sensor) detected\nvalue error at cold start check",
    "Supply module (supply module\nheater temperature sensor)\nfaulty value received for\ntemperature information duty\nvalue",
    "Supply module (supply module\nheater temperature sensor)\ninvalid value received for\ntemperature information duty\nvalue",
    "Supply module (pump motor)\ntemperature information PWM\ncycle error",
    "Supply module (pump motor)\ntemperature information PWM\nsignal error",
    "Supply module (supply module\ntemperature sensor) faulty\nvalue received for temperature\ninformation duty value",
    "Supply module (supply module\ntemperature sensor) invalid\nvalue received for temperature\ninformation duty value",
    "Supply module (pump motor)\nnot starting to measure\ntemperature",
    "Supply module (pump motor)\npressure rise 1",
    "Supply module (pump motor)\npressure reduction error",
    "Aqueous urea hose\nbackflow-side pressure rise",
    "Aqueous urea hose\npressure-side pressure rise",
    "Supply module (pump motor)\npressure stability error",
    "Supply module (reverting valve)\nfailure",
    "Supply module aqueous urea\nsuckback error",
    "Supply module (pump motor)\npressure rise 2",
    "Supply module pressure drop",
    "Supply module aqueous urea\npressure rise",
    "Aqueous urea tank temperature\nrise",
    "CAN reception timeout\n(A1DEFI)",
    "CAN reception timeout (AT1T1I)",
    "SCR system error (inducement\n1)",
    "SCR system error (inducement\n2)",
    "ECU system FS action\ninstruction 1",
    "Key switch wiring break",
    "Data verification error between\nECU and DCU (verification\ntimeout)"
	};

