





											

#define sf_FLASH_BLOCK1_ADDR		0x1FF0000
#define sf_FLASH_BLOCK2_ADDR		0x1F10000
#define sf_FLASH_PAGE_SIZE			256
#define sf_FLASH_SECTOR_SIZE		4096

 



#define sf_Addr_sSTART						0
#define sf_Addr_Count						10
#define sf_Addr_M7_UserIndex				16
#define sf_Addr_AUX1CurrentOutMode			17
#define sf_Addr_DTM_DateTime_Mode			18
#define sf_Addr_BG_Color					19
#define sf_Addr_LCD_BL_Day					20
#define sf_Addr_LCD_BL_Night				21
#define sf_Addr_SIUS_SEL_Flag				22
#define sf_Addr_HMV_HourMeter_Trip			23
#define sf_Addr_Option_Function_Rotate_Flag	24
#define sf_Addr_M7_UserSet0_A_Value			25
#define sf_Addr_M7_UserSet1_A_Value			26
#define sf_Addr_M7_UserSet2_A_Value			27
#define sf_Addr_M7_UserSet0_B_Value			28
#define sf_Addr_M7_UserSet1_B_Value			29
#define sf_Addr_M7_UserSet2_B_Value			30
#define sf_Addr_M7_UserSet0_P1_Value		31
#define sf_Addr_M7_UserSet1_P1_Value		32
#define sf_Addr_M7_UserSet2_P1_Value		33
#define sf_Addr_M7_UserSet0_ATT_State		34
#define sf_Addr_M7_UserSet1_ATT_State		35
#define sf_Addr_M7_UserSet2_ATT_State		36
#define sf_Addr_M7_UserSet0_Way_Opt			37
#define sf_Addr_M7_UserSet1_Way_Opt			38
#define sf_Addr_M7_UserSet2_Way_Opt			39
#define sf_Addr_M7_UserAUX24Set_C_Value		40
#define sf_Addr_M7_UserAUX24Set_D_Value		41
#define sf_Addr_M7_UserAUX24Set_P2_Value	42
#define sf_Addr_M7_UserAUX24Set_G_Value		43
#define sf_Addr_M7_UserAUX24Set_H_Value		44
#define sf_Addr_M7_UserAUX24Set_P4_Value	45
#define sf_Addr_Option_Function_AutoStopKey	46

#define sf_Addr_CC1_Brightness				50
#define sf_Addr_CC1_Contrast				51
#define sf_Addr_CC1_Saturation				52
#define sf_Addr_CC1_Hue						53
#define sf_Addr_CC1_Sharpness				54
#define sf_Addr_CC2_Brightness				55
#define sf_Addr_CC2_Contrast				56
#define sf_Addr_CC2_Saturation				57
#define sf_Addr_CC2_Hue						58
#define sf_Addr_CC2_Sharpness				59
#define sf_Addr_Device_UID					61
#define sf_Addr_PW100_PWD					81
#define sf_Addr_PW100_PW_OnOff				91
#define sf_Addr_M7_Lock_Data_Value0_Lock	92
#define sf_Addr_M7_Lock_Data_Value1_Lock	93
#define sf_Addr_M7_Lock_Data_Value2_Lock	94
#define sf_Addr_M7_Lock_Data_Value0_Show	95
#define sf_Addr_M7_Lock_Data_Value1_Show	96
#define sf_Addr_M7_Lock_Data_Value2_Show	97
#define sf_Addr_Lang_Flag					110
#define sf_Addr_Option_Function_AutoStop	130
#define sf_Addr_User_RegInfo_RegKeyNum		150
#define sf_Addr_User_RegInfo_RegFlag		170
#define sf_Addr_User_RegInfo_AccessAUX		190
#define sf_Addr_User_RegInfo_UserPassCode	210
#define sf_Addr_User_RegInfo_UserName		610
#define sf_Addr_sEND						4092
	
	
	
#define sf_Size_sSTART						4
#define sf_Size_Count						4
#define sf_Size_M7_UserIndex				1
#define sf_Size_AUX1CurrentOutMode			1
#define sf_Size_DTM_DateTime_Mode			1
#define sf_Size_BG_Color					1
#define sf_Size_LCD_BL_Day					1
#define sf_Size_LCD_BL_Night				1
#define sf_Size_SIUS_SEL_Flag				1
#define sf_Size_HMV_HourMeter_Trip			1
#define sf_Size_Option_Function_Rotate_Flag	1
#define sf_Size_M7_UserSet0_A_Value			1
#define sf_Size_M7_UserSet1_A_Value			1
#define sf_Size_M7_UserSet2_A_Value			1
#define sf_Size_M7_UserSet0_B_Value			1
#define sf_Size_M7_UserSet1_B_Value			1
#define sf_Size_M7_UserSet2_B_Value			1
#define sf_Size_M7_UserSet0_P1_Value		1
#define sf_Size_M7_UserSet1_P1_Value		1
#define sf_Size_M7_UserSet2_P1_Value		1
#define sf_Size_M7_UserSet0_ATT_State		1
#define sf_Size_M7_UserSet1_ATT_State		1
#define sf_Size_M7_UserSet2_ATT_State		1
#define sf_Size_M7_UserSet0_Way_Opt			1
#define sf_Size_M7_UserSet1_Way_Opt			1
#define sf_Size_M7_UserSet2_Way_Opt			1
#define sf_Size_M7_UserAUX24Set_C_Value		1
#define sf_Size_M7_UserAUX24Set_D_Value		1
#define sf_Size_M7_UserAUX24Set_P2_Value	1
#define sf_Size_M7_UserAUX24Set_G_Value		1
#define sf_Size_M7_UserAUX24Set_H_Value		1
#define sf_Size_M7_UserAUX24Set_P4_Value	1
#define sf_Size_CC1_Brightness				1
#define sf_Size_CC1_Contrast				1
#define sf_Size_CC1_Saturation				1
#define sf_Size_CC1_Hue						1
#define sf_Size_CC1_Sharpness				1
#define sf_Size_CC2_Brightness				1
#define sf_Size_CC2_Contrast				1
#define sf_Size_CC2_Saturation				1
#define sf_Size_CC2_Hue						1
#define sf_Size_CC2_Sharpness				1
#define sf_Size_Device_UID					20
#define sf_Size_PW100_PWD					10
#define sf_Size_PW100_PW_OnOff				1
#define sf_Size_M7_Lock_Data_Value0_Lock	1
#define sf_Size_M7_Lock_Data_Value1_Lock	1
#define sf_Size_M7_Lock_Data_Value2_Lock	1
#define sf_Size_M7_Lock_Data_Value0_Show	1
#define sf_Size_M7_Lock_Data_Value1_Show	1
#define sf_Size_M7_Lock_Data_Value2_Show	1
#define sf_Size_Lang_Flag					1
#define sf_Size_Option_Function_AutoStop	1
#define sf_Size_User_RegInfo_RegKeyNum		1
#define sf_Size_User_RegInfo_RegFlag		1
#define sf_Size_User_RegInfo_AccessAUX		1
#define sf_Size_User_RegInfo_UserPassCode	20
#define sf_Size_User_RegInfo_UserName		50
#define sf_Size_sEND						4
	
	
	

	
typedef struct _XoSaveConfig
{
	uint8_t *DataBuff;
	uint32_t FlashAddr;
	uint8_t UserNum;
	bool SaveFlag;
	bool ForceSave;
}XoSaveConfig;
	
	
	
	
	
	
	
	
	
	
	
	
	

