

////////////////   Back Screen  /////////////////////////////////


extern bool BS_PieceBoomCheck;	// 0:off , 1:on
extern bool BS_2anTo4th;		// 0:off , 1:on
extern uint32_t BS_PieceBoomCheckTime;
extern uint32_t BS_2anTo4thTime;


extern uint8_t SC_MI_SC5[3][7];
extern uint16_t SC_MI_SC4[6];
extern uint16_t SC_MI_SC3[8];
extern uint16_t SC_MI_SC2[8];
extern uint16_t SC_MI_SC1[9];


extern uint32_t SC_MI_SC5_Time[3];
extern uint32_t SC_MI_SC4_Time[6];
extern uint32_t SC_MI_SC3_Time[8];
extern uint32_t SC_MI_SC2_Time[8];
extern uint32_t SC_MI_SC1_Time[9];



extern uint8_t Regeneration_type_W; 	// 2:Normal , 1: Slow
extern uint8_t Regeneration_type_R; 	// 0:OK , 1:Bad condition , 2:Wait , ±âÅ¸: ¼û±è

extern uint8_t IMM_R_4B03b;