#if 0 	//  JPHong 2024-09-02 V0.19
#define WIYP1	6
#define WIYP2	77

#define WIYP1_H	2
#define WIYP2_H	2

IconInfo WarningIconA_Info[WARNING_ICON_CNT+1] = { 	{9	,WIYP1,cW_01_B},			//0
													{9	,WIYP1,cW_02_B},			//
													{78	,WIYP1,cW_03_B},			//
													{153,WIYP1,cW_04_B},			//
													{225,WIYP1,cW_05_B},			//
													{297,WIYP1,cW_06_B},			//5
													{369,WIYP1,cW_07_B},			//
													{441,WIYP1,cW_08_B},			//
													{513,WIYP1,cW_09_B},			//
													{585,WIYP1,cW_10_B},			//
													{657,WIYP1,cW_11_B},			//10
													{225,WIYP2,cW_12_B},			//
													{9	,WIYP2,cW_13_B},			//
													{9	,WIYP2,cW_14_B},			//
													{81	,WIYP2,cW_15_B},			//
													{81	,WIYP2,cW_16_B},			//15
													{81	,WIYP2,cW_17_B},			//
													{153,WIYP2,cW_18_B},			//
													{153,WIYP2,cW_19_B},			//
													{585,WIYP2,cW_20_B},			//
													{657,WIYP2,cW_21_B},			//20
													{729,WIYP2,cW_22_B},			//
													{726,WIYP1,cW_27_B},			//
													{-1,-1,-1},						//
													{-1,-1,-1},						//
													{-1,-1,-1},						//25
													{-1,-1,-1},						//26
													{-1,-1,-1}
												};

IconInfo WarningIconA_Info_H[WARNING_ICON_CNT+1] = {{7 ,WIYP1_H,cW_01_B},			//0
													{7 ,WIYP1_H,cW_02_B},			//
													{72,WIYP1_H,cW_03_B},			//
													{144,WIYP1_H,cW_04_B},			//
													{209,WIYP1_H,cW_05_B},			//
													{274,WIYP1_H,cW_06_B},			//5
													{339,WIYP1_H,cW_07_B},			//
													{404,WIYP1_H,cW_08_B},			//
													{469,WIYP1_H,cW_09_B},			//
													{534,WIYP1_H,cW_10_B},			//
													{599,WIYP1_H,cW_11_B},			//10
													{924,WIYP1_H,cW_12_B},			//
													{729,WIYP1_H,cW_13_B},			//
													{729,WIYP1_H,cW_14_B},			//
													{794,WIYP1_H,cW_15_B},			//
													{794,WIYP1_H,cW_16_B},			//15
													{794,WIYP1_H,cW_17_B},			//
													{859,WIYP1_H,cW_18_B},			//
													{859,WIYP1_H,cW_19_B},			//
													{924,WIYP1_H,cW_20_B},			//
													{1048,WIYP1_H,cW_21_B},			//20
													{1048,WIYP1_H,cW_22_B},			//
													{664,WIYP1_H,cW_27_B},			//
													{-1,-1,-1},						//
													{-1,-1,-1},						//
													{-1,-1,-1},						//25
													{-1,-1,-1},						//26
													{-1,-1,-1}
												};


IconInfo FunctionIconJ_Info[FUNCTION_ICON_CNT+1] = {
#ifdef NEW_GUI
													{ 344,92  ,	cF_01_B	},		//1
#else
													{ 354,94  ,	cF_01_B	},		//1
#endif		
													{ 15,663 ,	cF_02_B },		//2
													{ 15,663 ,	cF_03_B },
													{ 15,767 ,	cF_04_B },		//3
													{ 15,767 ,	cF_05_B },
													{ 128,767 ,	cF_06_B },		//4
													{ 241,767 ,	cF_07_B },		//5
													{ 241,767 ,	cF_08_B },
													{ 241,767 ,	cF_09_B },
													{ 354,767 ,	cF_10_B },		//6
													{ 354,767 ,	cF_11_B },
													{ 128,872 ,	cF_12_B },		//7
													{ 579,872 ,	cF_13_B },		//8
													{ 692,872 ,	cF_18_B },		//9
													{ 466,976 ,	cF_14_B },		//13
													{ 466,976 ,	cF_15_B },
													{ 579,976 ,	cF_16_B },		//14
													{ 579,976 ,	cF_17_B },
													{ 466,872 ,	cF_19_B },
													{ 680,976 ,	cF_20_B },
													{ 680,976 ,	cF_21_B },
													{ 680,976 ,	cF_22_B },
													{-1,-1,-1}
												};
IconInfo FunctionIconJ_Info_H[FUNCTION_ICON_CNT+1] = {
#ifdef NEW_GUI
													{ 469, 64  ,	cF_01_B	},		//1
#else
													{ 479, 99  ,	cF_01_B	},		//1
#endif		
													{ 18, 394 ,	cF_02_B },		//2
													{ 18, 394 ,	cF_03_B },
													{ 18, 506 ,	cF_04_B },		//3
													{ 18, 506 ,	cF_05_B },
													{ 128, 506 ,	cF_06_B },		//4
													{ 240, 506 ,	cF_07_B },		//5
													{ 240, 506 ,	cF_08_B },
													{ 240, 506 ,	cF_09_B },
													{ 572, 506 ,	cF_10_B },		//6
													{ 572, 506 ,	cF_11_B },
													{ 468, 506 ,	cF_12_B },		//7
													{ 890, 394 ,	cF_13_B },		//8
													{ 678, 618 ,	cF_18_B },		//9
													{ 468, 618 ,	cF_14_B },		//13
													{ 468, 618 ,	cF_15_B },
													{ 572, 618 ,	cF_16_B },		//14
													{ 572, 618 ,	cF_17_B },
													{ 786, 618 ,	cF_19_B },
													{ 904, 619 ,	cF_20_B },
													{ 904, 619 ,	cF_21_B },
													{ 904, 619 ,	cF_22_B },
													{-1,-1,-1}
												};												


#endif 	//  JPHong 2024-09-02 V0.19


