add_executable(${CMAKE_PROJECT_NAME}
    Layer_logo.c
    Layer_main.c
    Layer_EngnCool.c
    MenuTop_Layer.c
    Menu2_Layer.c
    Menu3_Layer.c
    Menu4_Layer.c
    Menu5_Layer.c
    Menu6_Layer.c
    Menu7_Layer.c
    M7S1_Layer.c
    S1_ATT_Layer.c
    M7S2_Layer.c
    M7S5_Layer.c
    M7S6_Layer.c
    M7S7_Layer.c
    M7S4_Layer.c
    M7_S11_Layer.c
    Menu8_Layer.c
    Menu9_Layer.c
    MenuBTop_Layer.c
    MenuB100_Layer.c
    MenuB200_Layer.c
    MenuB300_Layer.c
    MenuB400_Layer.c
    M7SU100_Layer.c
    M7SU200_EDIT_Layer.c
    M7SU300_NAME_Layer.c
    M7SU400_PASS_Layer.c
    M7SU500_RFID_Layer.c
    M7SU600_LEVEL_Layer.c
    MenuIM_Layer.c
    PW100_PASS_Layer.c
)

